### PR TITLE
Add bulk delete for purchase order line items

### PR DESCRIPTION
**Pull request by simonkuehling**
- Implements #4449 
- fixes a missing `var` definition in `order.js` line 917 from recent refactorings of pricing display

### CODE REVIEW

**Comment by simonkuehling** [comment]
@SchrodingersGat good catch, thanks! Commited a fix for that...

**Comment by SchrodingersGat** [comment]
@simonkuehling additionally can you add a simple unit test for the bulk-delete functionality for this endpoint?

**Comment by simonkuehling** [comment]
Sure, I will at least try - another first with this project :+1: 

I would imagine something like this
```py
class PurchaseOrderLineItemTest(OrderTest):
    """Unit tests for PurchaseOrderLineItems."""

    LIST_URL = reverse('api-po-line-list')

[...]

    def test_po_line_bulk_delete(self):
        """Test that we can bulk delete multiple PurchaseOrderLineItems via the API."""
        n = models.PurchaseOrderLineItem.objects.count()

        url = reverse(LIST_URL)

        # Try to delete a set of line items via their PKs
        response = self.delete(
            url,
            {
                'items': [1, 3, 4],
            },
            expected_code=204,
        )

        # We should have 3 less PurchaseOrderLineItems after deletign them
        self.assertEqual(models.PurchaseOrderLineItem.objects.count(), n - 3)
```

Does that look right? How can I call only one specific test in the docker dev setup?
If I try to run the complete suite I get an error:
```
$ docker compose run inventree-dev-server invoke test
[...]
Traceback (most recent call last):
  File "/home/inventree/InvenTree/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/inventree/data/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/inventree/data/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/inventree/data/env/lib/python3.9/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/home/inventree/data/env/lib/python3.9/site-packages/django/core/management/base.py", line 346, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/inventree/data/env/lib/python3.9/site-packages/django/core/management/base.py", line 320, in create_parser
    self.add_arguments(parser)
  File "/home/inventree/data/env/lib/python3.9/site-packages/django/core/management/commands/test.py", line 44, in add_arguments
    test_runner_class = get_runner(settings, self.test_runner)
  File "/home/inventree/data/env/lib/python3.9/site-packages/django/test/utils.py", line 324, in get_runner
    test_module = __import__(test_module_name, {}, {}, test_path[-1])
ModuleNotFoundError: No module named 'django_slowtests'

```

**Comment by SchrodingersGat** [comment]
The example test looks like it would work. To setup a test environment locally, run `invoke setup-dev`

**Comment by simonkuehling** [comment]
...should have read the contribution guidelines more carefully... thanks for the hint!

I can't get the test working right though - is using `self.delete()` the right request for this?
I always get `Method not allowed`for the test:
```
$ python ./manage.py test order.test_api.PurchaseOrderLineItemTest.test_po_line_bulk_delete
[...]
Method Not Allowed: /api/order/po-line/
F
======================================================================
FAIL: test_po_line_bulk_delete (order.test_api.PurchaseOrderLineItemTest)
Test that we can bulk delete multiple PurchaseOrderLineItems via the API.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/inventree/InvenTree/order/test_api.py", line 616, in test_po_line_bulk_delete
    response = self.delete(
  File "/home/inventree/InvenTree/InvenTree/api_tester.py", line 220, in delete
    self.assertEqual(response.status_code, expected_code)
AssertionError: 405 != 204

```

**Comment by simonkuehling** [comment]
oh no, that's embarrassing... took me way too long to figure out that I was adding the test on the wrong branch... the test runs just fine, commit will be pushed in a minute.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution :)

**Pull request merged**
