### PR TITLE
Reintroduce uv into CI actions

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Removed in https://github.com/inventree/InvenTree/pull/7305
- New version of `uv` has broken CI pipeline

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair I have raised this so we don't neglect to add `uv` back into the pipeline. But it looks like the recent updates to `uv` have ... broken things

**Comment by matmair** [comment]
Ok this seems somewhat intentional / not considered a bug https://github.com/astral-sh/uv/issues/3765#issuecomment-2125648857

**Comment by matmair** [comment]
And https://github.com/astral-sh/uv/pull/3767

**Comment by matmair** [comment]
At this point, I think we should either pin the latest working version or just go back to pip. There are 200 more important issues than fixing the CI every few uv updates

**Comment by SchrodingersGat** [comment]
I'd support just going back to pip. `uv` has caused a *lot* of headaches and I agree it is not worth our time chasing this down

**Pull request closed without merging**
