### PR TITLE
Various SAST fixes

### PR DESCRIPTION
**Pull request by matmair**
More small reliability/maintainability fixes from SAST warnings.

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat found the CI problem

**Comment by SchrodingersGat** [comment]
@matmair what was the issue?

**Comment by matmair** [comment]
@SchrodingersGat The StylishText component causes errors when getting empty children passed in so I reveres the change in that area

**Comment by SchrodingersGat** [comment]
Nice :) Happy for me to merge this then?

**Comment by matmair** [comment]
@SchrodingersGat yes, ready for merge

**Pull request merged**
