### PR TITLE
multilingual Stocktake actions

### PR DESCRIPTION
**Pull request by matmair**
PR for #1438

- [x] tests?
- [x] use right translations in UI
- [x] how to keep old translations around for backwards-compatibility

### CODE REVIEW

**Comment by matmair** [comment]
Default fallback when no translation available: English! Gets quite difficult to maintain otherwise - with vastly decreasing returns.

**Comment by SchrodingersGat** [comment]
@matmair I would suggest putting this one on hold for a little while. I am currently looking into how to remove the `StockItemTracking` model completely, in favor of a more robust "stock item history tracking" approach - see https://github.com/inventree/InvenTree/issues/1303

So this PR would conflict with that change a lot!

The same goes for - https://github.com/inventree/InvenTree/pull/1482

I'm keen to address both these issues but not until the stock history tracking framework is refactored.

**Comment by matmair** [comment]
@SchrodingersGat the functionality is done already, it just needs a bit of polishing / testing.

I have had bad experiences with rollbacks in django-simple-history in other projects before but maybe I can learn from your implementation.

**Comment by SchrodingersGat** [comment]
@matmair I have not settled on django-simple-history yet, if there's some issues you have come across I'd be interested to know!

**Comment by matmair** [comment]
I have posted my thoughts to #1303 as it seems that that is the issue regarding the implementation.

**Comment by matmair** [comment]
@SchrodingersGat made a PR with a better system in #1572.

**Pull request closed without merging**
