### PR TITLE
APIMixin: Add flag for passing data as json

### PR DESCRIPTION
**Pull request by matmair**
This PR adds the option to send data via the APIMixin in the form-encoded format.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3635"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I think that the way this is handled in the python requests library is a bit cleaner. You call the function with either a `data` or `json` kwarg (not both) and it works out how to handle the date from that context

**Comment by SchrodingersGat** [comment]
@matmair please address CI issues and I'm happy :)

**Comment by SchrodingersGat** [comment]
@matmair can you please look at the failing CI on this one?

**Comment by SchrodingersGat** [comment]
@matmair bump :) be nice to get this merged

**Comment by matmair** [comment]
@SchrodingersGat done

**Comment by SchrodingersGat** [comment]
Nice, thanks @matmair

**Pull request merged**
