### PR TITLE
Add content headers to config

### PR DESCRIPTION
**Pull request by matmair**
Make sure user media is served as attachments
https://huntr.dev/bounties/3a676adb-085f-4927-9e00-1283c1955f92/

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3731"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat we should test this well before merging - I have had a lot of problems with wrong headers in the past

**Comment by SchrodingersGat** [comment]
@matmair all the uploaded images (e.g. parts) are served via `/media/` also - are they OK because they are specifically loaded via `` tags in the HTML?

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair the demo server is now running using this fix, seems to be working quite well

**Comment by matmair** [comment]
@SchrodingersGat ok I think we can go ahead with the merge

**Pull request merged**
