### PR TITLE
Fixes for installer

### PR DESCRIPTION
**Pull request by matmair**
This PR fixes various issues with the package installer:
- move reqs file to contrib
- detect previously used python version and always use that
- safe extra requirements to INSTALLER_EXTRA (https://github.com/inventree/InvenTree/issues/6892)

This only fixes use cases that are deployed to the book, DO installs will need a few extra steps that I will document in #7336.

Closes https://github.com/inventree/InvenTree/issues/6892

### CODE REVIEW

**Comment by matmair** [comment]
Current builds of the fixed package can be found [here](https://packager.io/gh/matmair/InvenTree/refs/fix-installer). DO NOT run this on your prod instance, you will be updated to 0.16.dev - not a stable version

**Comment by SchrodingersGat** [comment]
@matmair the two major error messages that people seem to be getting are below:


```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/opt/inventree/.github/requirements.txt'
```

```
/opt/inventree/contrib/packager.io/functions.sh: line 96: jc: command not found
```

Does the `jc: command not found` error get addressed in this fix?

**Comment by matmair** [comment]
All linked errors get adressed

**Comment by SchrodingersGat** [comment]
@matmair thanks for this. Let's see how we go.

**Review by SchrodingersGat — APPROVED** [review]

**Pull request merged**
