### PR TITLE
[PUI] Table loading refactor

### PR DESCRIPTION
**Pull request by LavissaWoW**
Ties into #6009

Can eventually close said issue if the solution is acceptable.

Obviously disregard the `console.log`'s :>

### CODE REVIEW

**Comment by LavissaWoW** [comment]
By introducing the `useInstance` object to the table's JSX, we're able to stop table generation when the proper parameters are not yet present. React will trigger a re-render when this parameter changes, and since it's treated as a first-level parameter of the underlying `InvenTreeTable`, we can be assured that the table will render properly.

As mentioned in the issue, even though the InvenTreeTable component gets an updated `pk` for the relevant table after `useInstance` finishes, this does not constitute a re-render from React's side for some reason.

**Comment by LavissaWoW** [comment]
My initial thought was to simply use `id` rather than wait for the promise to resolve, as you suggest.
But I figured it's done this way intentionally, to allow for the browser given ID and `pk` to be different in the future? 

The first suggestion will solve the issue, given that the above is true.
I was initially thinking you'd want the panel to load even if the API was being slow. But thinking about it with a fresh head, if the instanceQuery is still fetching, the LoadingOverlay will be visible. So then that problem becomes moot.

**Comment by wolflu05** [comment]
> My initial thought was to simply use id rather than wait for the promise to resolve, as you suggest.
But I figured it's done this way intentionally, to allow for the browser given ID and pk to be different in the future?

I'm not sure if this makes sense in the future, because the `location.pk` is the same as the id. And afaik that's the only way to get a unique instance. Given the alternative implementations complexity I would go for the `id` approach, what do you mean @SchrodingersGat ?

**Comment by LavissaWoW** [comment]
@wolflu05 Ive read some issues asking for UUID based URLs. Basically asking for database PKs to be obfuscated. That's where I drew my reasoning from. But if @SchrodingersGat green-lights using the ID, I'll patch all the currently implemented tables in this manner and update the PR accordingly.

**Comment by LavissaWoW** [comment]
@SchrodingersGat I've exchanged PK for ID only on panels that did not already rely on the objects returned via `instanceQuery`.
The logic being that if a panel uses the object for something other than PK, it's waiting for the object anyhow.

> Sometimes the id does not "resolve" correctly (could be a dependency issue)
The table renders multiple times, first time without the correct id - and so you get a "flash" of incorrect data into the table.

I saw a few oddities just now, but they did not seem to be related to problems with the ID. 
It looks to me as if data from old table objects are re-used in new table objects. 

To reproduce my experience:
1. Open BO-0015 (platform/build/15)
2. Open "Completed Outputs" panel
3. Go back to "Details" panel
4. Go to Build Index (platform/build)
5. Go to  BO-0016 (platform/build/16)
6. Open "Completed Outputs" panel
7. You'll see a brief flash of 3x Green Chair in the table.

**Comment by SchrodingersGat** [comment]
@LavissaWoW I can definitely see the cached data appearing as you describe above. If you are confident that this is a different issue, I'm happy to merge this in when ready (but we really should make a new issue for the cached data behaviour).

**Comment by LavissaWoW** [comment]
`GET http://localhost:5173/api/stock/?build=-1&is_building=false&part_detail=true&location_detail=true&supplier_part_detail=true&limit=25&offset=0 400 (Bad Request)`

@SchrodingersGat the `InvenTreeTable` component doesn't care about `-1`, and proceeds to ask the API for -1. I'll remove these so the console doesn't generate errors on these cases.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@LavissaWoW LGTM - have you confirmed that the issue is now fixed?

**Comment by SchrodingersGat** [comment]
Ok, great!

Can you please address these javascript issues:

https://app.deepsource.com/gh/inventree/InvenTree/run/450df5eb-93ae-4a53-9a86-04669e8c5477/javascript/JS-0356?listindex=0

**Comment by LavissaWoW** [comment]
Of course. I suspect they were latent ones waiting to get triggered, as I didn't interact with those specifically. Just the file.
Commit inc. as soon as my slow af. devcontainer manages to do the pre-commit.

**Pull request merged**
