### PR TITLE
Yapf

### PR DESCRIPTION
**Pull request by eeintech**
[Yapf formatter](https://github.com/google/yapf) tests!

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
It is intriguing that the formatter seems to be doing opposite things in different instances:

e.g. list unrolling

image

vs

image

@eeintech can you comment on this?

**Comment by eeintech** [comment]
Ummm the changes looked "clean" for the ones I saw, but this one is bizarre...
I'll check more into yapf tomorrow to understand why would this happen.

**Comment by eeintech** [comment]
@SchrodingersGat Looks like the termination comma in the list matters:
* The first list is comma-terminated -> list is unrolled
* The second list is not -> list is rolled back

This behavior can be changed with the following option:
image

Disabling it (`disable_ending_comma_heuristic = true`) would re-roll all the lists, independently if they are comma-terminated or not.

I do prefer them **unrolled**, it creates much cleaner and visually obvious diffs, which means we would need to add a termination comma on all lists and keep that option disabled.

**Comment by SchrodingersGat** [comment]
Ah, at least there was a reason!

Is the idea here that yapf will just point out errors, or it will actually format the code on a check-in?

Also, I assume this is going on top of the flake8 checking which is already in place - that checks a lot of things over and above style issues.

**Comment by eeintech** [comment]
Yes yapf formats the code when called on a file, it won't point out errors unless maybe when it fails to run.

There is a bit of conflict between flake8 and yapf as I mentioned here: https://github.com/inventree/InvenTree/issues/1068#issuecomment-719064834

Maybe a code formatter tool was not the real idea behind that #1068 issue, however it was proposed and I wanted to get a look at what yapf is capable of.

**Comment by eeintech** [comment]
@SchrodingersGat Let's put this on the back burner for the time being, I'm actually pretty happy with the format of the code, you did a great job keeping it clean and I'm trying too. Unless more users start contributing to InvenTree more frequently I would say `yapf` or any other code formatter tools is not really needed right now.

**Pull request closed without merging**
