### PR TITLE
Stock Locations and Items Ownership

### LINKED ISSUE #1129: Stock location linked to user group
Hi!

At [fablab bcn](https://fablabbcn.org/) we are running an instance of [Inventree](https://inventory.fablabbcn.org/) - so far it's working great and we really appreciate the fantastic work.
Since we have various projects with different inventory locations, we wonder if there's the possibility (already implemented or not) to have a stock location linked to an user group. This facilitates the case in which an organization like ours has various projects in parallel with different teams, but you don't want them to have edit access to other stock locations, but yes view access. 

Would this be a potential enhancement? If not, we can always run different instances. 
Thanks!

### PR DESCRIPTION
**Pull request by eeintech**
If approved, fixes #1129 (and maybe #656)

## Global
* Added `owner` fields to `StockLocation` (ForeignKey to Django `Group`) and `StockItem` (ForeignKey to Django `User`)
* Added global setting for ownership control of stock locations and items (under "Stock" tab): enabling this setting enforces ownership for add/edit operation on stock locations/items

image

## Web Interface/Templates
* Only the stock item owner (user) can see "add/edit" item
* If user is member of stock location ownership (group), user can "add/edit" location

## Forms/Views
* The `Owner` field is shown in both stock location and item forms only **when the global setting is enabled** (otherwise hidden)
* Adding a stock location requires:
  * the owner field (group) to be set
  * if the location has a parent, the owner is automatically set to the parent's owner and can't be changed
* When editing a stock location's owner, all children locations are updated with the same owner
* Adding a stock item requires:
  * the owner field (user) to be set
  * If the location is set, only a user associated to location ownership (group) can be selected as owner

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @eeintech I've finally had a chance to look at your implementation here. In general, it looks pretty nice!

A couple of fine points to be clarified:

### Group vs User

I think it makes sense to allow some flexibility in determining "who" owns or controls a StockLocation or StockItem. I would like to see the ability to assign either a StockLocation or StockItem to a user *or* a group.

- Assign StockItem to group or single user
- Assign StockLocation to group or single user
- Cannot assign to both a user and a group

### Anonymous Items

In your current implementation, if "ownership" is enabled, can locations and/or items exist without an owner? Your description above seems to indicate that if ownership is enabled, then stock items and locations *must* have an owner assigned. Is this the case? I think that un-owned items and locations must still be supported in this case.

**Comment by eeintech** [comment]
@SchrodingersGat Thanks for having a look :+1:

Please check out the following table:

image

* `UC` stands for "Use-Case" (only for referencing each change)
* Red text is when a change was made by user
* Green text is when a location/item owner is automatically updated in database

#### Worth-to-mention notes
* Changing the location's owner forces changes of all items' owners at that location (UC#2, 4 and 6)
  * Unless the new location's owner is a **group** and the item's owner is part of that group (UC#10)
* Changing the item's location forces change of owner (UC#7)
* There is no memory from previous items' owners in the case stock location's owner changes (UC#8)

Does it cover all your suggestions?
If/when you approve, I will update this PR to cover all those use-cases.

**Comment by SchrodingersGat** [comment]
Thanks for putting this table together. I believe this covers the use cases I can think of.

How do you plan to implement the dual group/user ownership rules?

**Comment by eeintech** [comment]
My plan was to have two separate fields in the models (one for group owner, one for user owner) and only one of them can be set at a given time. I was thinking to use the `UniqueConstraint` ([ref](https://docs.djangoproject.com/en/3.1/ref/models/constraints/#uniqueconstraint)) along with a conditional check that either one if set, but not both at the same time (XOR-type of logic). That way, whichever model owner field (group or user) is set is the actual owner.

That would also mean logic in the form to gather both users and groups in the same "owner" field and in the model/view to handle the switch of owner.

What do you think?

**Comment by SchrodingersGat** [comment]
That sounds like a very sensible approach

**Comment by eeintech** [comment]
@SchrodingersGat I think this pull request is ready for review (round 2).

I have changed the default behavior for parts without owners when stock ownership is enabled, both locations and items are now only editable by an **Admin** user.
The reason for this is to enforce that each location/item has its owner set, and not leave the door open to malicious users wanting to play around because the admin/InvenTree manager hasn't set the owner yet.
Does it make sense?

Here is the updated table of use-cases (I did traverse most of it manually through the web interface, and the test cases also try to repoduce those use-cases):

image

Also, I don't know what's happening with the Travis hook but it seems way behind.
For reference, the result of the last build should show up here: https://travis-ci.org/github/inventree/InvenTree/builds/754194770

**Comment by eeintech** [comment]
@SchrodingersGat I realized that I forgot to mentioned how I implemented the "owner" field.
Instead of my original thoughts of using two separate database fields, I went with a [`GenericForeignKey` implementation](https://docs.djangoproject.com/en/3.1/ref/contrib/contenttypes/#generic-relations).

I created a "proxy" class conveniently called `Owner` in the `users` app.
An "owner" is a link to either a `User` or `Group` instance.
Owners creation and deletion is linked closely to users and groups, so that there is no discrepancy there (eg. owner pointing to deleted user or group, user or group missing an owner entry).

Now what's great about this implementation of ownership is that it can be re-use in other apps other than the stock management :smiley: 
It's also quite easy to add to existing models and forms as it is just one extra field!
I found it quite easy to retrieve authorized owners in templates too.

Take a look into `InvenTree/users/models.py` for more details, I hope you like it too!

**Comment by SchrodingersGat** [comment]
@eeintech thanks for your fantastic effort here. I should have some time to look over this in the next couple of days 👍

**Comment by SchrodingersGat** [comment]
Hey @eeintech sorry some recent merges have caused some conflicts here. Can you please fix and I'll review :)

**Comment by eeintech** [comment]
@SchrodingersGat Here you go! :wink:

**Comment by SchrodingersGat** [comment]
Hi @eeintech I like what you have implemented here. I do not see anything which would prevent me from merging this. Are you 100% happy for this to be merged now or are there any things you still need to work on?

**Comment by eeintech** [comment]
@SchrodingersGat Yes this is ready to be merged, I don't intend to add more for the time being.

**Comment by SchrodingersGat** [comment]
Fantastic, thanks for the great work on this. This (and the documentation in https://github.com/inventree/inventree-docs/issues/47) are all that I'm waiting on for the next major release :)

**Pull request merged**
