### PR TITLE
Refactor label/report template copying

### PR DESCRIPTION
**Pull request by matmair**
This PR is a first step towards https://github.com/inventree/InvenTree/issues/5841 and will help with #6478.
It factors out the `ready()` function of the `report` and `label` apps into a generic function that can also be used by plugins to ship their own default templating content.
This does not change the functionality around templating and is only a refactor to get functionality into one place.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair nice work, this will clean things up nicely for our future work

**Comment by wolflu05** [comment]
@matmair Does this also fixes the bug that if I change an InvenTree provided template, it gets crated again and I end up with duplicate templates?

**Comment by matmair** [comment]
@wolflu05 no, it is a pure internal refactor. The behaviour you describe is a more nuanced problem and will have to be discussed as the current way templates are handled (file based) has some problems when interacting with an API.

**Comment by wolflu05** [comment]
Ok. Yeah that's right.

**Pull request merged**
