### PR TITLE
Fix usage of old html tags

### PR DESCRIPTION
**Pull request by matmair**
This PR fixes the usage of old HTML tags in a sample template.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
You don't let me get away with anything ;)

**Comment by matmair** [comment]
@SchrodingersGat I would not mind but my CI checks for W3C compliance and fails till upstream is fixed

**Comment by SchrodingersGat** [comment]
Should we add that to our CI here?

**Comment by matmair** [comment]
@SchrodingersGat If you like never passing CIs - sure. TBH I would not recommend but I need it for compliance reasons.

**Pull request merged**
