### PR TITLE
[FR] Add API endpoint to activate plugins 

### LINKED ISSUE #4182: [FR] :checkered_flag: Add API endpoint to activate plugins
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

There is currently no endpoint to activate a plugin by a key

### Suggested solution

Add an endpoint `/api/plugin/activate` that is supplied with the key/slug of the plugin to enable them

### Describe alternatives you've considered

You could run a patch on the detail endpoint but a separate endpoint would be nice

### Examples of other systems

_No response_

### Do you want to develop this?

- [X] I want to develop this.

### PR DESCRIPTION
**Pull request by matmair**
This PR:
- integrate general plugin patterns into the plugin patterns 
- BREAKING moves all plugin management endpoints to `/api/plugins` instead of `/api/plugin`
- adds an endpoint to activate a plugin

Fixes #4182

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4186"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Is the breaking change ("plugins" vs "plugin") necessary here? This will cause at the least the app to break.

Also please bump the API version in `api_version.py`

**Comment by matmair** [comment]
@SchrodingersGat I think it has strong benefits as the current naming schema prevents some slugs from being used for plugin URLs and the number of 'reserved' slugs will only grow with time.
A clear separation between `/api/plugin` for plugin-provided URLs and `/api/plugins` for meta fields also makes sense to prevent accidentally overriding core functions.

**Comment by SchrodingersGat** [comment]
@matmair please increment the API version so external services (e.g. app) can determine which endpoint to call :)

**Comment by matmair** [comment]
@SchrodingersGat API version is bumped!

**Pull request merged**
