### PR TITLE
Data import API

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Closes https://github.com/inventree/InvenTree/issues/3101

Provides an API-based data import tool using [django-data-wizard](https://github.com/wq/django-data-wizard)

### Tasks

- [ ] Run data import using background worker
- [ ] Preview imported data and allow user to confirm
- [ ] Auto-assign columns based on previous import runs
- [ ] API endpoints
- [ ] Significant unit testing
- [ ] Remove old clunky import code
- [ ] Remove django-import-export integration entirely

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat does django-data-wizard also replace the export options of django-import-export?

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat does django-data-wizard also replace the export options of django-import-export?

Not directly, but if possible, I'd like to make use of our DRF serializers to format data for export. This way we remove a lot of duplication and custom code required to overcome the shortcomings of django-import-export

**Comment by matmair** [comment]
@SchrodingersGat seems like a lot of work to replace all the supported formats - especially excel - but interested to see how you go at it.

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat seems like a lot of work to replace all the supported formats - especially excel - but interested to see how you go at it.

It requires some investigation :)

**Comment by matmair** [comment]
@SchrodingersGat is this approach not working? Should I make a try?

**Comment by SchrodingersGat** [comment]
I accidentally deleted the wrong branch :) Still active, just waiting until PUI is a bit further along

**Pull request closed without merging**
