### PR TITLE
Implement structural stock locations

### PR DESCRIPTION
**Pull request by martonmiklos**
Similar change to the #3931  just for stock locations.

I tried to add filtering for the non-structural locations (where StockItems end up located) to the most places what I found on the frontend, but I do not  use extensively the build/source side of InvenTree so I might missed something. Let me know and I am going to fix it.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3949"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@martonmiklos you are on a streak, thank you!

**Comment by SchrodingersGat** [comment]
@martonmiklos looks like you've missed out a migration file here

**Comment by martonmiklos** [comment]
> @martonmiklos looks like you've missed out a migration file here

Hmm. I have added a migration file (InvenTree/stock/migrations/0090_stocklocation_structural.py), I have no idea why the SQLITE test generated an alter migrate (the rest DB tests passed.)

I have rebased to master, regenerated the migration, so let's see how it goes.

**Comment by matmair** [comment]
Seems like the migration now is included. I have to deal with this from time to time - you might want to check that your forks `master` branch is up to date with upstream.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@martonmiklos looks good. OK to merge?

**Comment by martonmiklos** [comment]
> @martonmiklos looks good. OK to merge?

Yes. I am not aware of any further location inputs where the structural = false filtering needs to be enforced.
If anyone came across one in the future we can address that in a new PR.

**Comment by martonmiklos** [comment]
> Seems like the migration now is included. I have to deal with this from time to time - you might want to check that your forks `master` branch is up to date with upstream.

Offtopic: I was thinking about adding an "developer best practices" section to the docs where these wisdoms could be collected.

Things what have in mind currently:

- invoke setup-dev
- How to run individual unit tests
- Rebase to the master branch before submitting PR
- Bump API version when needed

**Comment by SchrodingersGat** [comment]
> Shall I bump the API version here as well?

Oh yes, please do increment that.

As for best practices, we try to note those down in [contributing.md](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md) - you can make suggestions there as you see fit :)

**Comment by martonmiklos** [comment]
> Oh yes, please do increment that.

Done

> As for best practices, we try to note those down in [contributing.md](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md) - you can make suggestions there as you see fit :)

Ah finding something new again ;) Thanks!

**Comment by SchrodingersGat** [comment]
Thanks again for the contribution :)

**Pull request merged**
