### PR TITLE
Fix sidebar translation

### PR DESCRIPTION
**Pull request by matmair**
This PR fixes the missing translations for sidebar items
Fixes inventree#2347

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2350"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Ah yes, I see the problem now with the way the translations are performed here!

**Comment by matmair** [comment]
> Ah yes, I see the problem now with the way the translations are performed here!

Yeah my approach broke something too - working on a fix asap. We should really try to get code coverage up

**Comment by matmair** [comment]
@SchrodingersGat now it should work. Just waiting for the checks to go through

**Comment by matmair** [comment]
@SchrodingersGat @eeintech you should really try replacing all translation strings with xxx
grafik

**Comment by SchrodingersGat** [comment]
> you should really try replacing all translation strings with xxx

Can we make a "testing" language which does this automatically?

**Pull request merged**
