### PR TITLE
add report feature for stock locations

### PR DESCRIPTION
**Pull request by xeno27**
AS discussed here:  https://github.com/inventree/InvenTree/discussions/5110
I add a report feature for stock locations.

Closes #5110 

i have to add the stock location report template to demo_data.

now it is possible to press print location report on stock locations:
Screenshot from 2023-07-03 12-27-47

the demo report looks like this:

Screenshot from 2023-07-03 12-27-30

### CODE REVIEW

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@xeno27 thanks, this is a very comprehensive addition, nice work!

**Comment by xeno27** [comment]
Thanks @SchrodingersGat :) i tried to fix the flake8 errors.

**Comment by SchrodingersGat** [comment]
@xeno27 if you read through the [contributing guide](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md#setup-devtools) you can see how to setup your local install to fix most of these errors automatically :)

**Comment by SchrodingersGat** [comment]
> > @xeno27 if you read through the [contributing guide](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md#setup-devtools) you can see how to setup your local install to fix most of these errors automatically :)
> 
> I checked, but as i see invoke style is not working. (no endpoint in tasks.py ?)
> 
> "Code Style
> 
> Submitted Python code is automatically checked against PEP style guidelines. Locally you can run invoke style to ensure the style checks will pass, before submitting the PR. Please write docstrings for each function and class - we follow the [google doc-style](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) for python. Docstrings for general javascript code is encouraged! Docstyles are checked by invoke style."

Looks like the docs are out of date - the "invoke style" command is no longer available.

However these checks are performed as part of the git pre-commit hook.

Run `invoke setup-dev` to get this configured.

**Comment by SchrodingersGat** [comment]
@xeno27 you'll need to add the new model to `users/models.py` - https://github.com/inventree/InvenTree/blob/42fd4c7ee68167462a136da51e1763b066d77406/InvenTree/users/models.py#L56

**Comment by xeno27** [comment]
if this is fine i will add the function to copy the default templates. 
https://github.com/inventree/InvenTree/discussions/5164

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@xeno27 thanks for the contribution :)

**Pull request merged**
