### PR TITLE
Fix stock location structural check

### PR DESCRIPTION
**Pull request by bloemp**
Exclude sub stock location items from preventing that a stock location can be switched to structural.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4089"></a>

Closes https://github.com/inventree/InvenTree/issues/4087

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@bloemp thanks! Can you also make the same fix to the part category model:

https://github.com/inventree/InvenTree/blob/d9e99e38d2313ec0673986e2765915af37c1c36e/InvenTree/part/models.py#L151

**Comment by bloemp** [comment]
@SchrodingersGat modified the pull request to include a fix for the part categorie.
`        if self.pk and self.structural and self.partcount(False, False) > 0:
`
I've added both parameters to the partcount call, while not strictly needed... it seemed future proof (if anyone ever changes the default, the check still functions). But as a newbie to python, is this the best way to go?

**Comment by SchrodingersGat** [comment]
@bloemp looks good :)

**Comment by SchrodingersGat** [comment]
Thanks for your contribution @bloemp

**Pull request merged**
