### PR TITLE
BoM export: added option to export part parameters (#126) and stocks (#793)

### PR DESCRIPTION
**Pull request by eeintech**
Intention to fix both #126 and #793 
I have to admit I'm not quite sure the exported stock data is what @lookme2 was expecting, but at least the option is there and can be built on

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat Just to be clear, is this only gated by @lookme2 approval? What minor change were you referring to?

**Comment by SchrodingersGat** [comment]
The minor change is to alter the column heading from `Location` to `Default Location`

**Comment by eeintech** [comment]
Ok, I just did. Sorry I couldn't see your review, not sure where to find it at :thinking:

**Comment by SchrodingersGat** [comment]
Great, thanks for the fix @eeintech :)

**Pull request merged**
