### PR TITLE
Template cleanup

### PR DESCRIPTION
**Pull request by matmair**
This PR:
- makes the usage of quotes in templates uniform
- removes unneeded spaces

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2620"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat ready for merge

**Comment by SchrodingersGat** [comment]
@matmair  a few conflicts here that need fixing :)

**Comment by matmair** [comment]
@SchrodingersGat should be ready now

**Comment by SchrodingersGat** [comment]
@matmair this PR broke everything! (see https://github.com/inventree/InvenTree/issues/2625)

I must not have pulled it down properly to check, but I've reverted this change in master. Can you please re-submit?

**Pull request merged**
