### PR TITLE
Add dj-rest-auth

### LINKED ISSUE #3978: [FR] User registration via API
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

We currently do not support user registration via API - so the frontend must be used

### Suggested solution

Steps:
- [x] Add  an API endpoint under `/api/user/register` to registering users
- [x] Add unit testing for it

### Describe alternatives you've considered

N/A

### Examples of other systems

_No response_

### Do you want to develop this?

- [X] I want to develop this.

### PR DESCRIPTION
**Pull request by matmair**
This PR:
- Adds various endpoints to use the currently available auth/registering functions via the API
- Adds JWT as an auth method (simpler to use in SPA - related to #3901)

TODO:

- [x] test registering endpoint
- [x] add social connect endpoints
- [x] security review?
- [x] extend docs

Fixes #3978

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4187"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Does this work with existing SSO solutions?

**Comment by matmair** [comment]
@SchrodingersGat that is still TODO

**Comment by matmair** [comment]
@SchrodingersGat do we want to continue supporting all social connection options with #3901 or should we cut down the options for the first version?

**Comment by SchrodingersGat** [comment]
By "cut down" do you mean still supporting key ones (e.g. google / microsoft)?

**Comment by matmair** [comment]
@SchrodingersGat I think supporting the main ones (google, apple, microsoft, github, twitter, discord, keycloak, OIDC, saml) should be good enough for a start. There are a lot of providers by default.

**Comment by matmair** [comment]
@SchrodingersGat it took a bit but it seems like we can maintain support for almost all providers (all that support OAuth2).

Exceptions are:
```
Found handler that is not yet ready for platform UI: `bitbucket`
Found handler that is not yet ready for platform UI: `draugiem`
Found handler that is not yet ready for platform UI: `evernote`
Found handler that is not yet ready for platform UI: `500px`
Found handler that is not yet ready for platform UI: `flickr`
Found handler that is not yet ready for platform UI: `keycloak`
Found handler that is not yet ready for platform UI: `linkedin`
Found handler that is not yet ready for platform UI: `openid`
Found handler that is not yet ready for platform UI: `openstreetmap`
Found handler that is not yet ready for platform UI: `persona`
Found handler that is not yet ready for platform UI: `pocket`
Found handler that is not yet ready for platform UI: `steam`
Found handler that is not yet ready for platform UI: `telegram`
Found handler that is not yet ready for platform UI: `trello`
Found handler that is not yet ready for platform UI: `tumblr`
Found handler that is not yet ready for platform UI: `twitter`
Found handler that is not yet ready for platform UI: `vimeo`
Found handler that is not yet ready for platform UI: `xing`
```
I will work on adding support for Keycloak, OpenId and Twitter. Are you ok with waiting for FRs for the rest?

**Comment by matmair** [comment]
Ok, I have to revise that; there is a Twitter OAuth2 and OIDC  endpoint; I added keycloak so it should be good to go.
The only thing missing is an endpoint to get all available providers and a few small refactors.

**Comment by SchrodingersGat** [comment]
> I will work on adding support for Keycloak, OpenId and Twitter. Are you ok with waiting for FRs for the rest?

Absolutely - I don't think it makes sense to spend a bunch of effort for integrations that may never actually be used.

**Comment by SchrodingersGat** [comment]
Does this replace our existing SSO login views completely?

**Comment by matmair** [comment]
No, it just exposes them in another way. Under the hood the same functional code is used.

**Comment by matmair** [comment]
Closes https://github.com/inventree/InvenTree/issues/3978

**Comment by SchrodingersGat** [comment]
@matmair ready for merge?

**Comment by matmair** [comment]
@SchrodingersGat I got it to point where the settings do not need to change so no new docs needed.

**Comment by SchrodingersGat** [comment]
Well, great! Thanks :)

**Pull request merged**
