### PR TITLE
Fix task register

### PR DESCRIPTION
**Pull request by matmair**
This PR fixes the wrong call that was reverted in #3803
In detail:
- it enables multiple tasks lists (optional)
- uses function name instead of ref
- adds a step to collect tasks from apps

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3805"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat I tested it manually - should work as expected now. I looked into testing this e2e but that seems quite involved with the multiple servers etc.

**Comment by matmair** [comment]
@SchrodingersGat this should be ready to go

**Comment by SchrodingersGat** [comment]
@matmair just testing locally now :)

**Comment by SchrodingersGat** [comment]
Fingers crossed, but it looks good on my end.

**Pull request merged**
