### PR TITLE
[FR] User sessions

### LINKED ISSUE #2327: [FR] User sessions
**Problem**
Currently, sessions are base64 based so multi-browser sessions get difficult to handle.

**Suggested solution**
Add an ORM based solution to user sessions and management options in a user security tab.

- [x] new sessions backend
- [x] security tab for users
- [x] move MFA, SSO and password to the security tab
- [x] Sign out all option

**Describe alternatives you've considered**
The current solution works as a password change invalidates the session too.

**Examples of other systems**
Github, Nextcloud

**Do you want to develop this?**
Yes

### PR DESCRIPTION
**Pull request by matmair**
Fixes #2327

This PR adds user sessions in the DB - the normal session behaviour is not changed but the user can see their active sessions in the settings and log out all other devices.
It also moves language settings to display settings.
grafik

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2371"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair looking good!

you just have to add the new db model here: https://github.com/inventree/InvenTree/blob/82d5952ddde9ad507b111d81230d0346e626fc9c/InvenTree/users/models.py#L57

**Comment by SchrodingersGat** [comment]
Nice work @matmair very clean implementation :)

**Comment by matmair** [comment]
> Nice work @matmair very clean implementation :)

Was quite easy, is a good standard package by jazzband. I will start on some of my 0.7.0 stuff till plugins are ready as I need them for my remaining 0.6.0 issues.

**Comment by SchrodingersGat** [comment]
I'll have some time this week for another review of the plugin system :)

**Pull request merged**
