### PR TITLE
Configuration options for dbbackup

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Closes https://github.com/inventree/InvenTree/issues/4180

This PR adds some setup / configuration options for database backup.

Additionally, backup is no longer "forced" during the "invoke update" step. This allows the update step to be run without backup, in situations where the user might not want this, or where backup is misconfigured.

On some (lower end) systems the "backup" task can stall for a long period of time which can cause worker timeout.

Ref: https://github.com/inventree/InvenTree/discussions/4179

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4190"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair due to the change to the `invoke update` step, (which no longer calls "backup" by default) does the installer script need to be adjusted?

**Review by matmair — APPROVED** [review]
I would not recommend running migrations without a backup as that might destroy an instance permanently. You are the maintainer, if you think this is in the best intrest of the user/project I wont stand against it.

**Comment by matmair** [comment]
> @matmair due to the change to the `invoke update` step, (which no longer calls "backup" by default) does the installer script need to be adjusted?

The installer just calls the invoke task so no changes required. Maybe a migration that adds the backup option for exsisting installs would be good. Or a warning that this default changed could be sent to all superusers.

**Comment by MR-DOS** [comment]
Hi, the problem was not during "invoke update", but on regular startup of Inventree server. Updating went completely OK.
With these changes, I could theoretically start up the server with backups disabled with otherwise default settings. Then if I wanted to enable them, I would have to restart the server and run into the same deadlock issue again, have to decrease amount of background workers, start up the server, wait for it to get satisfied with creating backups, shut it down and restart again with full amount of bkg workers. Or am I mistaken?

**Pull request merged**
