### PR TITLE
Mention the API version bump in CONTRIBUTION.md

### PR DESCRIPTION
**Pull request by martonmiklos**
I had to lookup this again recently, so I think it has it's own place in the CONTRIBUTING.md

If necessary we can add more wording on what do we mean under API change?

### CODE REVIEW

**Comment by wolflu05** [comment]
Good idea, what we could also do is adding a pr template with a list of things one need to check. E.g.

- [ ] Have you incremented the api version if you made changes there
- [ ] Have you updated the relevant docs
- [ ] Have you added tests for the relevant parts
- [ ] ...

What do you think @inventree/maintainer ?

**Comment by matmair** [comment]
I am currently working on automated detections of API changes - https://github.com/inventree/InvenTree/issues/6269. If that triggers it will be an API bump

**Comment by martonmiklos** [comment]
> I am currently working on automated detections of API changes - #6269. If that triggers it will be an API bump

Dauh, I should be looking around before PR-ing :D. 
What do you think shall I close this PR, or the #6269 will take some time while this mention in the docs might be helpful?

**Comment by matmair** [comment]
A few lines in the docs won't hurt for sure - let's keep this one going

**Comment by martonmiklos** [comment]
> A few lines in the docs won't hurt for sure - let's keep this one going

Yeah, but in this case you need to take care removing them when the automation will be implemented.

**Comment by matmair** [comment]
The automation will just throw an error similar to the pre-commit CI for requirements

**Comment by SchrodingersGat** [comment]
Cheers @martonmiklos

**Pull request merged**
