### PR TITLE
Fix task timeout when news_feed is unreachable

### LINKED ISSUE #6071: News Feed task doesn't work behind proxy, impacting performance
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

The `update_news_feed` task attempts to fetch the RSS/Atom feed once daily. This, however, doesn't work behind a proxy server.

The result is that these tasks occupy workers all the time, and never complete.
Each worker is terminated roughly every 90 seconds due to this.

### Steps to Reproduce

1. Put the InvenTree backend on a network unable to reach `INVENTREE_NEWS_URL`
2. Trigger the task
3. Task will lead to continuous timeout termination of workers

### Expected behaviour

Task should finish with no new News entries added if URL is unreachable.

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.12.10

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by LavissaWoW**
Closes #6071 

Added some tests to assure the task behaves as expected

### CODE REVIEW

**Comment by LavissaWoW** [comment]
@SchrodingersGat Can you see what happened with CI here?

**Comment by SchrodingersGat** [comment]
> Can you see what happened with CI here?

I broke CI in https://github.com/inventree/InvenTree/pull/6244 - will need to work to fix it tonight!

**Comment by LavissaWoW** [comment]
@SchrodingersGat Merged in the CI fix. Ready for review

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair are you happy with this?

**Review by matmair — APPROVED** [review]
LGTM

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @LavissaWoW !

**Pull request merged**
