### PR TITLE
Database stats

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Fixes https://github.com/inventree/InvenTree/issues/617

Implements a new dialog view which shows some simple (for now) database stats.

### CODE REVIEW

**Comment by mtrazakhan** [comment]
Hi, I want a access management app in this inventory project separately for role based permissions(read, write, update and delete) permissions for users

**Comment by SchrodingersGat** [comment]
Have you looked into the Admin interface? This provides user and group management?

image

**Comment by mtrazakhan** [comment]
okay, how can I show group in navbar only when admin login and then at the time of adding user i can add this user in a particular group.

**Comment by mtrazakhan** [comment]
from outside of my admin panel

**Comment by SchrodingersGat** [comment]
Sorry for my difficulty in understanding - are you trying to replicate the admin functionality here? I do not see the point of duplicating this when the "admin" users can log into the admin interface directly.

**Comment by mtrazakhan** [comment]
Want something like this:-
createRole
EditRole
RoleListing

**Pull request merged**
