### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by matmair**
Bumps dependencies for the upcoming 0.13.0 release.

It also:
- fixes a few typos that are now detected by the CI
- makes a few changes to support v5.0 of `react-query`

### CODE REVIEW

**Comment by wolflu05** [comment]
I saw you pinned mantine below v7, is there any reason why not migrating to v7? Or does this includes big breaking changes which means this is better done in a separate pr?

**Comment by matmair** [comment]
It is a huge breaking change that completely changes how styles are handled and requires a lot of new tools.

**Comment by wolflu05** [comment]
But doesn't that mean better migrating yet, before our codebase grows rapidly and we have to make more code compatible with v7?

**Comment by matmair** [comment]
You are welcome to tackle this, I see no real benefit in it

**Comment by SchrodingersGat** [comment]
Thanks @matmair

**Pull request merged**
