### PR TITLE
PUI form framework: dependent field

### PR DESCRIPTION
**Pull request by wolflu05**
This PR implements the dependent field in the PUI form framework. This field is needed for e.g. machine printing to provide the options specified by a driver based on the selected machine.

https://github.com/inventree/InvenTree/assets/76838159/b0a9efb9-0582-451a-9076-21ff15d2c825

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@wolflu05 nice, looks very clean. Do we have something similar in CUI already, or is this concept completely new for PUI?

**Comment by wolflu05** [comment]
> Do we have something similar in CUI already, or is this concept completely new for PUI?

This is already working in CUI since the initial implementation with #5837, just the PUI implementation was outstanding.

If you want to test with the same example from the example video, just paste this driver somewhere in the code:
```py
class TestDependentFieldLabelPrinterDriver(LabelPrinterBaseDriver):
    """Label printer driver for testing the dependent field printers."""

    SLUG = "test-dependent-field-driver"
    NAME = "Test dependent field driver"
    DESCRIPTION = "Test dependent field driver for InvenTree"

    class PrintingOptionsSerializer(LabelPrinterBaseDriver.PrintingOptionsSerializer):
        select_type = serializers.ChoiceField(choices=[
            ("integer", "Integer"),
            ("char", "Char"),
        ])
        my_field = DependentField(depends_on=["select_type"], field_serializer="get_my_field")

        def get_my_field(self, fields):
            if fields["select_type"] == "integer":
                return serializers.IntegerField()
            if fields["select_type"] == "char":
                return serializers.CharField()

    def print_labels(self, machine: LabelPrinterMachine, label, items: QuerySet, request, **kwargs):
        """Print labels using a Dymo label printer."""
        printing_options = kwargs.get('printing_options', {})
        print(printing_options)
```

**Review by matmair — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@wolflu05 thanks for working on this :)

**Comment by wolflu05** [comment]
Since this is merged now, the machine printing interface is completely supported on PUI. Only the app is missing, there is this issue already for it: https://github.com/inventree/inventree-app/issues/472

**Pull request merged**
