### PR TITLE
Adjust pkgr.yml

### LINKED ISSUE #6154: APT Update to 0.13 fails with requirement for Python 3.9, when system uses 3.10
### Deployment Method

- [X] Installer
- [ ] Docker Development
- [ ] Docker Production
- [ ] Bare metal Development
- [ ] Bare metal Production
- [ ] Digital Ocean image
- [ ] Other (please provide a link `Steps to Reproduce`

### Describe the problem*

As very well documented in issue #6139, (closed by the submitter), the requirements for python3.9, python3.9-venv, and python3.9-dev prohibit using the command:  apt install --only-upgrade inventree on systems that are running python3.10, such as Ubuntu 22.04.   It seems to ME that if a system running 0.12.8 works okay with python3.10, then we should be able to upgrade to 0.13.  However, I'm not a programmer.  :-)  I'm wondering if the requirement for python3.9 was to avoid installation on python3.8 systems, or if it was intended to also avoid python3.10.

### Steps to Reproduce

0.  Running Inventree 0.12.8, originally installed using the Installer Script, on Ubuntu 22.04 with python3.10.
1.  Attempted update to Inventree to version 0.13 using  `apt install --only-update inventree` which had been used successfully to update to 0.12.8.
2. Update was not possible due to dependencies for python3.9

### Relevant log output

```bash
apt install --only-upgrade inventree
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inventree : Depends: python3.9 but it is not installable
             Depends: python3.9-venv but it is not installable
             Depends: python3.9-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### LINKED ISSUE #6563: Updating from 0.12.3 to latest version
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I have Inventree installed via installer.
I've tried to update Inventree by stopping Inventree (systemctl stop inventree) and then running:
`apt install --only-upgrade inventree`

but that leads to:
`The following packages have unmet dependencies:
 inventree : Depends: python3.9 but it is not installable
             Depends: python3.9-venv but it is not installable
             Depends: python3.9-dev but it is not installable
E: Unable to correct problems, you have held broken packages.`

I tried to install python3.9 but Inventree doesn't start after that.

Then I tried also running:
`inventree run invoke update`
but :
`sh: 1: exec: invoke: not found`

Nothing seems to work for updating the version

### Steps to Reproduce

1. re-running the commands won't work

### Expected behaviour

Can't update to latest version due to commands failing

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

InvenTree Version	0.12.3
API Version		127
Python Version		3.10.12
Django Version		3.2.19

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Ref: https://github.com/inventree/InvenTree/issues/6154#issuecomment-1970536725
- Ref: https://doc.packager.io/documentation/customizing-the-build/#dependencies

Attempting to enable the installer to work across all support python versions.

Closes #6154
Closes #6563

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair are you happy for me to merge this, or are you running some other tests and I should hold off?

**Comment by matmair** [comment]
@SchrodingersGat this is not functional. The package depends on the old nginx. While it builds it is not functional after install. Debugging the install pipeline with caddy is taking quite a while as I re-run my droplet pipeline for each change.

**Comment by SchrodingersGat** [comment]
Ok, I'll leave this open for now just for reference, and close when you have something to replace it with.

**Comment by matmair** [comment]
@SchrodingersGat caddy is not part of the default repos for ubuntu/debian so I have re-added the nginx config for now so we can publish. I have tested this config on new and already installed machines with debian 11, ubuntu 20.02 and ubuntu 22.04.

**Review by matmair — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair thanks for that :)

**Pull request merged**
