### PR TITLE
Add parent to the filterable fields of the StockLocations and PartCat…

### PR DESCRIPTION
**Pull request by martonmiklos**
…egories

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@martonmiklos LGTM. FYI you can already filter by `category` (for `PartCategory` API) and `location` (for `StockLocation` API). But I think a generic parent filter is a good addition

**Comment by martonmiklos** [comment]
> @martonmiklos LGTM. 

Ahm I put back to WIP because some tests are failing and I want fix them.
 

> FYI you can already filter by category (for PartCategory API) and location (for StockLocation API). But I think a generic parent filter is a good addition

Well I made this change to support some tool development based on the API.
Under the Stock location list I do not see the location filter:
kép

Am I missing something locally?

**Comment by SchrodingersGat** [comment]
> Am I missing something locally?

No. This is a very "old" part of the code which does not get introspected properly by the API generation - something we need to fix!

Actually, upon further inspection I see that the "parent" filter *is* actually already there - it just is a *hidden* field...

image

So what we need to do is:

- Move the "parent" filter into the appropriate `FilterSet` class (so that it gets exposed to the API docs)
- Work out how to support the "cascade" option (this is why it currently sits in the current `filter_queryset` method

Note that any custom filtering in the `filter_queryset` method does not get exposed to the API docs

**Comment by SchrodingersGat** [comment]
@martonmiklos I'm replacing this with https://github.com/inventree/InvenTree/pull/6536 - please refer to the code there :)

**Pull request closed without merging**
