### PR TITLE
Relation update

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Ref: https://github.com/inventree/InvenTree/discussions/8416
- Adds "note" field to PartRelated model
- Implement new table column in PUI

### CODE REVIEW

**Comment by wolflu05** [comment]
We might could also overengineer this by adding a second table like relation types which can be selected. That way we can keep this field much clear/filter/… by common relations types. E.g. show all additional equipment relations, …  But that’s just a thought

**Comment by matmair** [comment]
I think using a state would probably be user-friendly as custom states would make it easy to extend the selection without adding new interfaces that need management functionality and discovery

**Comment by turist79** [comment]
> Using a state would probably be user-friendly as custom states would make it easy to extend the selection without adding new interfaces that need management functionality and discovery. That could be added as a separate PR to keep this one in the imminent 0.17.0

Do you mean the same "states" used for stock items or some other feature?

**Comment by turist79** [comment]
> We might could also overengineer this by adding a second table like relation types which can be selected. That way we can keep this field much clear/filter/… by common relations types. E.g. show all additional equipment relations, … But that’s just a thought

Keeping both Note and Relation type as separate table (dictionary) is the best solution here. I have never seen an example when organizing things from the start wasn`t beneficial later. The Relation type thing colud contain: direction flag (A->B, or bi-directional), optional conversion rate. This approach would allow smooth implementation of a lot of usefull things actually.

Of course, just my 2c again :)

**Comment by matmair** [comment]
@turist79 happy to review PRs

**Comment by turist79** [comment]
> @turist79 happy to review PRs

sorry, but what does it mean?

**Comment by matmair** [comment]
> sorry, but what does it mean?

I am happy to review functiong and tested code that you submit for inclusion implemeting your complicated suggestion

**Pull request merged**
