### PR TITLE
Add codecov

### PR DESCRIPTION
**Pull request by matmair**
This adds codecov as a coverage tracking provider - seel #6966.

### CODE REVIEW

**Comment by matmair** [comment]
For this to work we will need to add the project on codecov and set repo token for upload; this is just here for visibility for now while I play with it in combination with #6947

**Comment by matmair** [comment]
This PR running in my fork publishes reports already so you can [check out the interface here](https://app.codecov.io/gh/matmair/InvenTree/tree/tests-add-codecov).

**Comment by matmair** [comment]
CI fails because of https://github.com/inventree/InvenTree/pull/6968

**Comment by wolflu05** [comment]
I would say, let's try it out for a few weeks. Not sure if I understand notification right? You mean a gh message in the corresponding pr?

**Comment by SchrodingersGat** [comment]
@matmair I have setup the InvenTree/Inventree org on codecov now, so you can use that in the workflows

**Comment by matmair** [comment]
@wolflu05 you can get comments on PRs stating the coverage information - we have that turned off for coveralls currently

**Comment by SchrodingersGat** [comment]
@matmair this appears to be working:

image

Happy to merge?

**Comment by matmair** [comment]
@SchrodingersGat we are still missing settings; do we want PR comments or not?

**Comment by SchrodingersGat** [comment]
Yes, let's add them in and see how they play. Can always adjust later if we don't want them

**Comment by matmair** [comment]
@SchrodingersGat good to merge!

**Comment by matmair** [comment]
@SchrodingersGat I have added some miminmum coverage and carryforward flags to match the current settings for coveralls.

**Pull request merged**
