### PR TITLE
Pricing tooltips

### LINKED ISSUE #1989: [FR] pricing: tooltips for pricing
@eeintech @sintech so a small tooltip with information what information was used for calculation would be ok? I would include multiple levels of information depending on the settings.

_Originally posted by @matmair in https://github.com/inventree/InvenTree/issues/1957#issuecomment-902925980_

### PR DESCRIPTION
**Pull request by matmair**
This PR adds a tooltip with warnings etc. to pricing.

Closes #1989

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/1991"></a>

### CODE REVIEW

**Comment by eeintech** [comment]
Nice, let me know what's to review (where in the UI and how-to test it) and I can go over :+1:

**Comment by matmair** [comment]
@eeintech thanks - will ping you when I have fixed some performance issues with complex multilevel BOMs.

**Comment by matmair** [comment]
@eeintech so there is just one thing to check: if a part has a BOM the BOM pricing should now feature a tooltip like below with information how the pricing is created.
grafik

**Comment by SchrodingersGat** [comment]
@eeintech have you had a chance to review this one?

**Comment by matmair** [comment]
@eeintech thanks for reviewing. I will add some levels to it and experiment with settings for LOD.

@SchrodingersGat I would like to add a js-dependency (popper JS) for better / html tooltips.

**Comment by SchrodingersGat** [comment]
@matmair popperjs looks pretty good! I'm happy with that

**Comment by eeintech** [comment]
@matmair Seems like a low-key feature so maybe bring this into `0.6.x` later on? Or do you think you'll have time to push on in the coming days?

**Comment by matmair** [comment]
@eeintech I will try finishing it today, LDO and popper.js are already in my local repo so I just need to polish stuff up

**Comment by matmair** [comment]
@eeintech I ran into problems; we will have to postbone this.

**Comment by eeintech** [comment]
Why did you close this one @matmair ?

**Comment by matmair** [comment]
> Why did you close this one @matmair ?

I experimented a bit with this today and I think it will not work with more than a few parts. So not really a great fit.

**Pull request closed without merging**
