### PR TITLE
Add missing part import fields

### LINKED ISSUE #2181: Can't import all data fields when importing excel file of parts
**Describe the bug**
Dear All,
I'm using lastest InvenTree version on Ubuntu LTS 20.04 Server ( automatic dowload when install as described is doc https://inventree.readthedocs.io )
I've created parts manually and then export to excel file to get I/O excel files format, then I tried to upload all our stock ( of resistors ).
Only a few fields are availables in the graphical parser ( lack at least stock, stock min, price, location, etc ... )

**To Reproduce**
1. Having a minimum filled database with parts and parts categories, and options for import excel set to on
2. Try to upload excel file with parts within a subcategory
3. Try to choose fields names

**Expected behavior**
I expect to be able to import all the available fiels of database's dataset "part"

**Screenshots**
If applicable, add screenshots to help explain your problem ; I'll give them if needed, with pleasure.

**Deployment Method**
Bare Metal ( local, dev )

**Last but no least**
How to communicate with each others ? Only github ? no mailing list ?
How to contibute with testing ? Where to start ?
How to contribute with features ? Where to start ?
We are EMS so InvenTree can be our daily S/W and of course we are self-motivated to contribute in proposing features, maybe coding features, but where to start to "enter into the code" ?

Regards,
Lea & JCh.

### PR DESCRIPTION
**Pull request by matmair**
This PR adds all (possible) fields that were missing from part imports:
- part attributes
- variant of - field
- base cost
- multiple
- stock count

If stock count is set a new stock item is created - if a default location is set that location will be used for the new stock item.

Closes #2181

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2193"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@tse-tarn-france does the implementation by @matmair meet your expectations now?

**Comment by tse-tarn-france** [comment]
Well @SchrodingersGat @matmair, Supplier does exists in my DB, but it did not import them from the part import wizard.

I suppose something is not as tested by Matthias, as he says it's OK.

As it is we will soon start to use inventree at work so user's cases will appear, we'll better declare bugs or fr regarding real use cases and not only test pattern.

My conclusion is : leave it like this for the moment.

Many thanks Matthias for this mod.

**Comment by matmair** [comment]
> 
> I suppose something is not as tested by Matthias, as he says it's OK.
>
Could you prvde me wth a test-dataset so I can reproduce? A few lines should be enough. Just the lines you want to import and the exports for the suppliers that make problems.
> As it is we will soon start to use inventree at work so user's cases will appear, we'll better declare bugs or fr regarding real use cases and not only test pattern.
> 
We are happy for feedback and suggestions!

**Comment by SchrodingersGat** [comment]
Many thanks @matmair for the fix :)

@tse-tarn-france please feel free to open a new issue for any other problems

**Pull request merged**
