### PR TITLE
Fix set user

### PR DESCRIPTION
**Pull request by matmair**
2 small fixes for adding a user via ENVs:
- fix error message
- adds a test to ensure that duplicated users can not be added (requires a small fix to how plugins raise errors)

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2746"></a>

### CODE REVIEW

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Looks like some failing tests need addressing here :)

**Comment by matmair** [comment]
> Looks like some failing tests need addressing here :)

This is a tricky one - I am not able to reproduce this locally. Breaks in wired places too.

**Comment by SchrodingersGat** [comment]
Fixed it! Well done :) good to go?

**Comment by matmair** [comment]
> Fixed it! Well done :) good to go?

If the test ho through now yes. I ripped out the additional tests earlier. To isolate the problem.

**Comment by matmair** [comment]
@SchrodingersGat should run now - I removed the new test again. Only contains the fixed error message and debug messages to debug errors with plugin testing

**Pull request merged**
