### PR TITLE
Show part delete button when part still active

### LINKED ISSUE #2072: [FR] Deleting a part is not discoverable
**Problem**
At first glance, there is no way to delete a part. Requires marking a part as inactive first before revealing the "delete part" button. Makes deleting a part very undiscoverable in the ui.

**Suggested solution**
Show the delete part button even when a part is still active. When selected, prompt the user to mark the part as inactive first (or suggest the user leave the part as inactive instead of deleting).

**Describe alternatives you've considered**
 * A comment in the part attributes "active" toggle switch to indicate making the part inactive will allow you to delete it.
 * Update the docs on how to delete a part.

### PR DESCRIPTION
**Pull request by eeintech**
Fixes #2072

### CODE REVIEW

**Review by matmair — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@eeintech looks great, I'd suggest you remove the "Submit" button though

image

**Comment by SchrodingersGat** [comment]
@eeintech I think this is the last one we are waiting on for `0.5.0` :)

**Comment by eeintech** [comment]
My bad, it's done now!

Let's do this!

**Comment by SchrodingersGat** [comment]
Awesome, thanks :)

**Pull request merged**
