### PR TITLE
[React] Order tables

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Improvements to the order tables, including some API changes to annotate more useful information

### CODE REVIEW

**Review by matmair — APPROVED** [review]
lgtm;
would it maybe make sense to add optional attributes to column definitions to define common formaters like project code, data, money, user, owner?

**Comment by SchrodingersGat** [comment]
> lgtm; would it maybe make sense to add optional attributes to column definitions to define common formaters like project code, data, money, user, owner?

I was just wondering that, there is certainly a lot of repetition.

**Comment by matmair** [comment]
> > lgtm; would it maybe make sense to add optional attributes to column definitions to define common formaters like project code, data, money, user, owner?
> 
> I was just wondering that, there is certainly a lot of repetition.

Should I create a follow-up PR to this and #5771 to make that happen?

**Review by matmair — APPROVED** [review]
LGTM

**Pull request merged**
