### PR TITLE
Feature/icons for PartCategory and StockLocation

### LINKED ISSUE #3522: [FR] Icons for stock locations
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Having a big tree for storage locations can get quick very messy to differentiate between rooms/boxes/sections/...

### Suggested solution

It would be cool if we could assign each location a font awesome icon. To implement this, I have two ideas:
1. add a field to the `StockLocation` model and save the font awesome icon name in there
2. add a separate table where we can create presets of locations which can then be selected in the `StockLocation`. Suggestion for the `StockLocationPreset` table:
   | id | name| icon |
   | --- | --- | --- |
   | `0` | `garage` | `fas fa-garage` |
   | `1` | `warehouse` | `fas fa-warehouse-alt` |
   | `2` | `box` | `box-alt` |

The advantage of the second variant would be, that we can change the icons later without going through each location which has the box icon.

One further improvement of the second would be that we can add custom icons, because fontawesomes iconset is very limited what storage containers/locations concerns.

### Screendesigns

I Imagine this feature looking something like this: 
image

### Describe alternatives you've considered

\-

### Examples of other systems

_No response_

### Do you want to develop this?

- [X] I want to develop this.

### PR DESCRIPTION
**Pull request by wolflu05**
### Description

This adds the icons like proposed in #3522 to the PartCategory and StockLocation table.

### Screenshots

<details>
image
image
image
image
image
</details>

### Fixes

fixes #3522 

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3542"></a>

### CODE REVIEW

**Review by matmair — APPROVED** [review]
looks good @wolflu05

**Comment by matmair** [comment]
@wolflu05 you have some styling issues - please look into the logs of the JS style check

**Comment by wolflu05** [comment]
> @wolflu05 you have some styling issues - please look into the logs of the JS style check

@matmair I saw that, but didnt know, why `blocktrans` is an prohibited tag. Do you have an idea?

**Comment by matmair** [comment]
I am not sure if js files support blocktrans

**Comment by wolflu05** [comment]
@matmair but its working as you can see in the screenshots. This seemed like a reasonable way to have an a href inside of a translation. I got this from this [forum](https://groups.google.com/g/django-users/c/QT1AgDJjHu4).

**Comment by wolflu05** [comment]
@SchrodingersGat fixed it in 5f0fdc9 , but somehow the workflows need an approval to run.

**Comment by wolflu05** [comment]
@SchrodingersGat Common 😂, sorry I forgot `endblocktrans`

**Comment by matmair** [comment]
@SchrodingersGat do you have memory if it the block tags were left out intentional?

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat do you have memory if it the block tags were left out intentional?

Not sure. I think it was probably just an omission.

**Comment by wolflu05** [comment]
@SchrodingersGat How can we avoid it. Do you have an idea in my case?

**Comment by SchrodingersGat** [comment]
@wolflu05 I think your simplification is probably the best approach

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@wolflu05 I'm happy to merge this in if you think it is complete

**Comment by wolflu05** [comment]
@SchrodingersGat Yes, it's also ready from my side. Thank you for all, we can merge this. 🎉

**Pull request merged**
