### PR TITLE
fixing a bug where the stock dont change unless refresh happen

### PR DESCRIPTION
**Pull request by atnomoverflow**
not sure if this is the right way to fix it since it's happening in all pages.
Edit:
it seems that i am doing the totale sum of the modfied parts instead of the totale sum of the all available parts

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@atnomoverflow thanks for the submission.

There is a much cleaner way to handle this :) As you are on the "Part" detail page, you can perform a single API call to the "part" detail (i.e. `/api/part/123/`) and this endpoint contains all relevent stock information:

- Total in stock
- Total required for orders
- Total allocated to orders
- Total on order from suppliers

And from these data you can calculate the "available" stock also

I would suggest that:

1. Add a function called `updatePartQuantityTotals` in [part.js](https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/part.js)
2. This function performs an API request
3. Update the various elements on the screen (see below)

image

**Comment by atnomoverflow** [comment]
Thanks for the heads up !
I am still getting femilliare with code base.

**Comment by SchrodingersGat** [comment]
No worries @atnomoverflow :) Please be aware that in the not too distant future we will be shifting to React for frontend

**Comment by atnomoverflow** [comment]
@SchrodingersGat Sorry to bother you but how can i calculate the can build quantity can't warp my head around or is there a param i can use to the get the prority in the responce also i dont know why but the rerender causes the icon to be way bigger than they should and this happen only to the icons that are below the first one
.

**Comment by SchrodingersGat** [comment]
Do you mean:

- The quantity currently being build
- The quantity required for outstanding build orders

**Comment by atnomoverflow** [comment]
image

**Comment by SchrodingersGat** [comment]
The "can build" is not currently available to the API. Best approach for now is to leave this field alone :)

**Comment by SchrodingersGat** [comment]
@atnomoverflow you'll need to merge master branch in and fix conflicts :)

**Comment by atnomoverflow** [comment]
@SchrodingersGat  sorry to bother you but how can lint this project

**Comment by atnomoverflow** [comment]
@SchrodingersGat  I did rebase but  it seems it dont go well with fork PR

**Comment by atnomoverflow** [comment]
@wolflu05 Thx !

**Comment by SchrodingersGat** [comment]
@atnomoverflow sorry that this one did not receive any attention. We have been busily working on moving the entire web interface to react, which will address this anyway.

**Pull request closed without merging**
