### PR TITLE
Bump docker image alpine base from 3.18 to 3.20

### PR DESCRIPTION
**Pull request by matmair**
Our base image uses a year-old alpine (https://endoflife.date/alpine) that has some os-level vulnerabilities. I would like to propose a move to 3.2o - which does not have those vulnerabilities and seems stable.

### CODE REVIEW

**Comment by matmair** [comment]
@wolflu05 thoughts on this?

**Review by wolflu05 — APPROVED** [review]
LGTM, I think we should just mention such updates at the top of the change list. Also if we bump the python version, as paths to the pip libraries could change.

**Comment by SchrodingersGat** [comment]
Lgtm thanks @matmair

**Comment by SchrodingersGat** [comment]
@matmair unfortunately the change in postgres is causing incompatibility with existing datasets.

For example, even just updating the devcontainer to run the latest setup, but using existing data, gives the following error:

image

This is a pretty big deal. Given that we only made this change yesterday, would the simplest approach be to roll back to `postgres:13` (and plan a migration path in the future?)

This would also address this issue: https://github.com/inventree/InvenTree/issues/7715

@matmair @wolflu05

**Comment by SchrodingersGat** [comment]
Ok looks like from https://github.com/inventree/InvenTree/pull/7717 that postgres:13 is not compatible with the updated alpine image?

**Comment by wolflu05** [comment]
Oh right, totally forgot that migrating a Postgres db requires to export-import the data as the different versions are not upwards compatible. We would need to document something like this: https://thomasbandt.com/postgres-docker-major-version-upgrade

**Comment by matmair** [comment]
Sad to hear this, I only tested on my dev cluster and there docker swarm deployed docker image of postgres seemed to auto-updated the postgres database version without problems. Glad this got caught so quickly though.

IMO it makes sense to completely revert this PR and re-discuss the update path for postgres (alpine seems to not present a problem but maybe my testing of that was also faulty)

**Comment by SchrodingersGat** [comment]
Any migration will need to have some robust checks for data migration!

**Pull request merged**
