### PR TITLE
docker: push both multiple image tags

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Fix for currently broken docker tags

Ref: https://github.com/inventree/InvenTree/pull/6562#issuecomment-1974010882

### CODE REVIEW

**Review by wolflu05 — COMMENTED** [review]
I think you now need to disable one of the matrix entries so that the docker image is only built and uploaded once.

**Comment by SchrodingersGat** [comment]
> I think you now need to disable one of the matrix entries so that the docker image is only built and uploaded once.

Yes, the matrix strategy does not seem appropriate here. Waiting for @matmair to comment on this

**Comment by wolflu05** [comment]
I think at the end the matrix strategy is not a bad choice (especially when we can build on m1 arm runners), we just would need a way to combine both builds and upload them at once under one tag.

**Comment by SchrodingersGat** [comment]
> I think at the end the matrix strategy is not a bad choice (especially when we can build on m1 arm runners), we just would need a way to combine both builds and upload them at once under one tag.

That sounds like a good idea for the next release

**Pull request merged**
