### PR TITLE
[FR] Check for docstrings optionally in CI

### LINKED ISSUE #2652: [FR] Check for docstrings optionally in CI
check for docstrings optionally in CI

_Originally posted by @matmair in https://github.com/inventree/InvenTree/issues/2493

### PR DESCRIPTION
**Pull request by matmair**
Fixes #2652

This PR adds stylechecking for docstrings. There are 3 possible styles:
- pep257 [example](https://www.python.org/dev/peps/pep-0257/#id6)
- numpy [example](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard)
- google [example](https://google.github.io/styleguide/pyguide.html#244-decision)

@SchrodingersGat which style would you prefer? I tend to use pep257, your more recent docstrings mostly comply with google - style from what I saw.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2653"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair great idea. I do much prefer the google standard, if you're happy to work with that :)

**Comment by matmair** [comment]
@SchrodingersGat you are the maintainer - I will use what the project uses. As long as there are standards I am happy 😇

**Comment by SchrodingersGat** [comment]
I'm assuming this one is going to require a *lot* of work :)

**Comment by matmair** [comment]
Yes, the PRs earlier were preparations for it, we have to go over each file in the project. Also, we def. need some kind of frontend unit or integration testing. Looking into that now.

**Comment by matmair** [comment]
@SchrodingersGat how do you feel about:
`
D200 One-line docstring should fit on one line with quotes
`

This would mean the following
```python
class PurchaseOrderReportDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    API endpoint for a single PurchaseOrderReport object
    """

    queryset = PurchaseOrderReport.objects.all()
    serializer_class = PurchaseOrderReportSerializer
```
needs to be reformated to
```python
class PurchaseOrderReportDetail(generics.RetrieveUpdateDestroyAPIView):
    """API endpoint for a single PurchaseOrderReport object"""

    queryset = PurchaseOrderReport.objects.all()
    serializer_class = PurchaseOrderReportSerializer
```

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat how do you feel about: `D200 One-line docstring should fit on one line with quotes`
> 
> This would mean the following
> 
> ```python
> class PurchaseOrderReportDetail(generics.RetrieveUpdateDestroyAPIView):
>     """
>     API endpoint for a single PurchaseOrderReport object
>     """
> 
>     queryset = PurchaseOrderReport.objects.all()
>     serializer_class = PurchaseOrderReportSerializer
> ```
> 
> needs to be reformated to
> 
> ```python
> class PurchaseOrderReportDetail(generics.RetrieveUpdateDestroyAPIView):
>     """API endpoint for a single PurchaseOrderReport object"""
> 
>     queryset = PurchaseOrderReport.objects.all()
>     serializer_class = PurchaseOrderReportSerializer
> ```

I don't feel strongly either way, so let's conform to it then?

**Comment by matmair** [comment]
@SchrodingersGat I will wait for the major PRs to close / merge and then tackle this.

**Comment by matmair** [comment]
Will be merged into #3000

**Pull request closed without merging**
