### PR TITLE
Update django-allauth version

### PR DESCRIPTION
**Pull request by SchrodingersGat**
### Overview

This PR provides updates to the django-allauth dependency - recent library updates have fixed some significant issues with social authentication

Closes https://github.com/inventree/InvenTree/issues/5866

### References

- https://github.com/inventree/InvenTree/discussions/5966#discussioncomment-7787934
- https://github.com/inventree/InvenTree/issues/6037
- https://docs.allauth.org/en/latest/release-notes/recent.html
- 
### Further Reading

From the [django-allauth documentation](https://docs.allauth.org/en/latest/socialaccount/provider_configuration.html#provider-configuration) it appaers that our current documentation is incorrect. We suggest a mix of configuring provider info in `settings.py` (via `config.yaml`) and also adjusting settings in the database (using the `SocialApp` model). The docs advise to use either one or the other.

It looks like the `SocialApp` approach is "friendlier" (can be done via the web interface) but the `config.yaml` approach is better from a security perspective - as there are no "leaks" of secrets such as client secrets into the database.

### CODE REVIEW

**Comment by mianumar** [comment]
Now it's look fine

**Comment by SchrodingersGat** [comment]
@mianumar did you pull down these changes and confirm?

**Comment by matmair** [comment]
@SchrodingersGat does this also address https://github.com/inventree/InvenTree/issues/4715 / could it be adapted to do that?

**Comment by SchrodingersGat** [comment]
@matmair I'm not sure I fully understand the problem in #4715 

Is it just that the OIDC settings need to be editable via the database? I think that if the admin sets up an SSO app on the db then it should be possible right?

**Pull request merged**
