### PR TITLE
Server pagination

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Adds server-side pagination for (some) data tables which **significantly** speeds up the UI - especially when there are a large number of records.

Fixes https://github.com/inventree/InvenTree/issues/310

The query is limited on the database side.

For a dataset of ~1000 records, this reduces query time from 6,000ms to ~100ms.

- [x] Check that the "limit" functionality still works for the home page
- [x] Unit testing for the stock list API
- [x] Unit testing for the part list API
- [x] Refactor duplicated "queryParams" function for inventreeTable

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat Wow very impressive! Nice work!

Seems like large BOM loading is still slow, any idea why?

**Comment by SchrodingersGat** [comment]
That's pretty slow indeed. With only 67 items I'd say there is something more serious going on that needs to be looked at.

For reference, before I added server-side pagination for the "parts" list, loading *all* parts on my test database (~1000) took around 6 seconds.

**Comment by eeintech** [comment]
You're right, we have 200+ parts in our database and the part list is loading almost instantaneously. I'll have to investigate why our BOM doesn't follow the same logic...

**Comment by SchrodingersGat** [comment]
Using the django debug toolbar, I was actually able to replicate this. The issue is *not* the data loading into the table

The server request to generate the page takes about 18s

image

But the subsequent database request is reasonably fast:

**Comment by SchrodingersGat** [comment]
On further inspection it appears that *any* of the part detail views are very slow (~15 seconds just to load the "part detail" page).

**Pull request merged**
