### PR TITLE
0.5.0

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Stable release of 0.5.0

This is the first time we are doing a "proper" process of creating a release candidate branch that will be merged into the "stable" branch.

For the next release, each feature merge request into master will also be applied to branch 0.6.0, rather than a single large branch like we are doing here. Hopefully will be cleaner that way for 0.6.0

### CODE REVIEW

**Review by matmair — APPROVED** [review]
@SchrodingersGat the project has changed a lot since the last release! To be honest I only skimmed through the 179 changed files as most of it is already in master but looks great.
I am especially excited about the new git-flow, naming schema and the added actions- this project is quite professional!

**Comment by SchrodingersGat** [comment]
It is definitely becoming a lot more polished - in no small part thanks to your efforts @matmair  :)

**Comment by eeintech** [comment]
Sweet, happy to see we're getting there!

@SchrodingersGat How do you see us testing this?

**Comment by SchrodingersGat** [comment]
As this was pulled from top of master I'll simply leave a period of time for any critical bugs to be reported and potentially fixed in master branch. If by the end of the month there's nothing outstanding against the 0.5.0 milestone I'll make the release

**Comment by eeintech** [comment]
Nice, in the meantime I'm trying to tackle some doc for the release :+1: 

I'll report any bug I'm finding too

**Pull request merged**
