### PR TITLE
Make tests faster

### PR DESCRIPTION
**Pull request by matmair**
This PR implements a few minor speed improvements for tests.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4181"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair how much faster does this make the tests?

**Comment by matmair** [comment]
@SchrodingersGat around 10-20 secs in my tests. So not really big seeing the tests run 14mins on my setup

**Comment by SchrodingersGat** [comment]
@matmair still interested in this? The other recent changes got testing down to ~20 minutes which is a huge improvement

**Comment by matmair** [comment]
Not really, the improvements here are minuscule.

**Pull request closed without merging**
