### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by SchrodingersGat**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair  HELP! It is ALIVE!

Clearly I've set the file filters up incorrectly here...

**Comment by SchrodingersGat** [comment]
image

**Comment by matmair** [comment]
@SchrodingersGat did you select Inventree/Inventree not Inventree/translation -> master? I can not open integrations as it would use your token for that
grafik

**Comment by matmair** [comment]
> 
> 
> @SchrodingersGat did you select Inventree/Inventree not Inventree/translation -> master? I can not open integrations as it would use your token for that
> grafik



> 
> 
> image

that amount of changes is why I suggested a separate repo and squashing

**Comment by SchrodingersGat** [comment]
Yes, I'm still playing around with it.

I'm not quite sure how it would work with a separate repo? After the commits are made back to the InvenTree/translation repo, how do those changes get merged back into the InvenTree/InvenTree repo?

**Comment by SchrodingersGat** [comment]
Ah you've addressed this in the other issue thread I see

**Comment by matmair** [comment]
You could make a PR into the inventree master each time you want to get all updated translations

**Pull request closed without merging**
