### PR TITLE
Build Order Updates

### PR DESCRIPTION
**Pull request by SchrodingersGat**
A long-needed overhaul of the build and build allocation system. 

This PR adds a new build database model, the "BuildLine"

- Represents an instance of a BOM item against a BuildOrder
- Is generated once when a BuildOrder is created
- If the BOM changes (after the build is created) the items required for the build order *do not change*
- Will help with speed of API queries against build orders
- Will allows users to "break out" subassemblies into a top-level flat build order
- Other advantages will fall out too
- Allows calculation of "overage"

------------

- Closes https://github.com/inventree/InvenTree/issues/340
- Closes https://github.com/inventree/InvenTree/issues/3940

### TODO

- [x] Fill out description
- [x] Data migration for existing adding BuildLine objects to build orders
- [x] Add data migration for assigning existing BomItem objects
- [x] Add migration for removing `BuildItem.build` column
- [x] Add migration for removing `BuildItem.bom_item` column
- [x] Unit testing for data migrations
- [x] Refactor `subtract_allocated_stock`
- [x] Refactor `scrap_build_output`
- [x] Refactor `complete_build_output`
- [x] Refactor `trim_allocated_stock`
- [x] Annotate "available" quantity to BomLine serializer
- [x] Annotate "allocated" quantity to BomLine serializer
- [x] Perform "remaining quantity" calculation on each `BuildLine` instance
- [x] Refactor "auto allocate" functionality
- [x] Refactor "unallocate" functionality
- [x] Refactor existing build reports
- [x] Recalculate required quantities if the total build quantity is adjusted
- [x] Update BuildLine objects when a BomItem is saved
- [x] Refactor all references to `has_untracked_bom_items`
- [x] Refactor all references to `incomplete_bom_items`
- [x] Unit testing
- [x] Documentation
- [x] Check calculation of overage in build orders
- [x] Fix "required for build orders" queryset annotation (should be a lot simpler now)
- [x] UI updates
- [x] API updates
- [x] Data migration for demo dataset - https://github.com/inventree/demo-dataset/pull/48
- [x] Ensure new API annotations on BuildLine model do not take O(n) time
- [x] Remove `build.required_quantity` method
- [x] Refactor `build.has_overallocated_parts` method
- [x] Refactor `build.required_parts_to_complete_build` method
- [x] Refactor `build.unallocateStock` method
- [x] remove old `loadBuildOutputAllocationTable` javascript function

### CODE REVIEW

**Review by matmair — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair we are hitting the same migration issues in this PR also - plugin tests not running correctly etc.

**Comment by matmair** [comment]
@SchrodingersGat seems like a general migration error; [bb37a97](https://github.com/inventree/InvenTree/pull/4855/commits/bb37a97e0b28b1fb648a095d0878f8381f63b4f2) seems fine except for 2 non-migration errors. Can you check the error is not in https://github.com/inventree/InvenTree/pull/4855/commits/a9d974bebd295d4ca11dc256f23fe76c82f3c4e5?

**Comment by SchrodingersGat** [comment]
@matmair can you give your 2 cents on this issue?

https://github.com/inventree/InvenTree/actions/runs/5250684787/jobs/9484929933?pr=4855

image

For some reason, running the unit testing is generating a new migration file in the "InvenTree" app. IIRC you recently added some migration stuff here, maybe?

**Comment by matmair** [comment]
The interesting part is why the migration checks go through

**Comment by SchrodingersGat** [comment]
If I run the full CI suite locally, I get a new migration file (under InvenTree/migrations) for each run through

**Comment by matmair** [comment]
Do you have the contents?
________________________________

**Comment by SchrodingersGat** [comment]
image

@matmair for example

If I run the CI tests again, I get another migration each time, i.e. 0003, 0004, 0005

**Pull request merged**
