### PR TITLE
[PUI] Add 2FA login

### LINKED ISSUE #6200: [PUI] Enable 2FA for new interface
Need to enable 2FA functionality via the API, and implement for:

- React interface
- Mobile app
- etc

In addition to implementing 2FA support via API endpoints, need to setup the user interface elements for the new platform UI

### PR DESCRIPTION
**Pull request by matmair**
This PR adds the option to use the CUI 2FA login method for PUI. The user is automatically send to the appropriate screen, can enter their default 2FA method (TOTP code, backup code, HOTP) and is then redirected to the PUI home screen.

https://github.com/inventree/InvenTree/assets/66015116/d723d5ef-a6e4-4c5a-b33a-6352bfe83415

This method respects CRSF and is stateless - which should make it pretty hard to circumvent.

Closes #6200

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair seems like a very good approach to work around this issue

**Comment by wolflu05** [comment]
Awesome that you implemented this, this was stopping me from using 2FA on my home instance. The question is just, what are we gonna do if we deprecate CUI? Will we still keep that view for entering the TOPT code? Or is there a possibility, we can directly implement that into PUI?

**Comment by matmair** [comment]
@wolflu05 my plan is to leave this in when we remove CUI, it is only a very small part - you can check out what this removal would look like here: https://github.com/matmair/InvenTree/pull/174

I do not think we should implement the different 2fa factors ourself (we support 3 rn) as that would create a lot of surfaces to make costly security issues.

**Comment by matmair** [comment]
This is ready for review/merge - testing the frontend is proving to be very hard because we can't add MFA methods via API (yet - that is coming with https://github.com/inventree/InvenTree/pull/6293)

**Comment by wolflu05** [comment]
> In the long run I really want to switch to allauths new included methods

But this would enable use to build our own 2FA input directly in PUI and really get rid of all CUI code. In your linked allauth roadmap they mention: 
> Add first-class API support. As part of the delivering the API, an OpenAPI specification and example React example application will be delivered, showcasing full SPA access to all of the django-allauth flows.

If they support 2FA via API, its not "our responsibility" with custom API code to built it secure anymore, because as I understand, they want to implement the critical backend API layer we could just use, and build our own frontend around it?

**Comment by matmair** [comment]
Yes, the switch will enable that. It will however require a complete review and possibly rewrite of our auth processes/integrations. This might take a while as it has grown over the years.

**Comment by SchrodingersGat** [comment]
@matmair nice work, thanks for the fix

**Pull request merged**
