### PR TITLE
Code structure refactor

### PR DESCRIPTION
**Pull request by matmair**
This PR implements #5578 and reorganises the code base more scalable. This is the first PR in a string of PRs needed, see #5578.
- [x] move container things into contrib/docker
- [x] move Django stuff into src/backend
- [x] add docs about structure to CONTRIBUTING
- [x] move misc things out
- [x] test docker build
- [x] test package build
- [x] update docs for bare metal git install

closes https://github.com/inventree/InvenTree/issues/5578

### Breaking Change

This is a significant breaking change as it rearranges a lot of source files. Any developers who are using the devcontainer setup will need to do a complete rebuild (without cache) of the devcontainer.

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat I can not find any usage of these CI checks:
- check_api_endpoint
- check_locale_files
 any idea why?

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat I can not find any usage of these CI checks:
> 
> * check_api_endpoint
> * check_locale_files
>   any idea why?

These are both outdated now:

- check_api_endpoint is now handled by `invoke wait`
- check_locale_files is now defunct since moving to crowdin

**Comment by SchrodingersGat** [comment]
@matmair in general this looks OK - what still to do?

**Comment by matmair** [comment]
@SchrodingersGat not really, I still need to add docs - should be good to go end of week.

**Comment by SchrodingersGat** [comment]
@matmair this will be a good target once `0.13.0` is released, giving us some free air to make sweeping changes

**Comment by matmair** [comment]
@SchrodingersGat this would be ready for review. The errors in the docs check are there because I adapted the links to the new paths (which do not exist on master at the point of the checks running).

This is breaking

**Comment by matmair** [comment]
@SchrodingersGat please ping me when you are ready to review this, I will stop resolving the merge conflicts for now

**Comment by SchrodingersGat** [comment]
@matmair fair call. I did say that I'd do it last week, but life... Hopefully this week :)

**Comment by SchrodingersGat** [comment]
Hey @matmair let's get this one done (sorry for the repeated delays). 

If you can fix these final conflicts (a lot of package dependency stuff) then I'll freeze other features until we get this merged in.

**Comment by SchrodingersGat** [comment]
@matmair I have made some tweaks so that the devcontainer works again

**Comment by matmair** [comment]
Ok this seems to work with docker and devcontainer - the documentation issues are because of the already adapted github source links. Happy for another review

**Comment by SchrodingersGat** [comment]
Do we need to keep the empty `requirements.txt` in the top level directory?

**Comment by matmair** [comment]
In my tests the packaging mechanism stopped detecting that the project uses python if I removed it.

**Comment by SchrodingersGat** [comment]
@matmair I have reviewed locally again and it all seems to be working well. I will merge this in, however we should all be on the lookout for any issues stemming from this. This is a *huge* change to the codebase so there may well be problems.

The `0.15.x` release target is for the end of the month, so let's take care until then.

**Comment by matmair** [comment]
@SchrodingersGat I expect some small surprises but most bases should be covered with the CI tests

**Pull request merged**
