### PR TITLE
Mark stale PRs / issues

### PR DESCRIPTION
**Pull request by matmair**
This PR adds a check for stale PRs / issues starting from everything created 2022. This helps to keep the backlog clean of things that have no interested stakeholders.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2495"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@inventree/maintainer @inventree/triage this was not listed in #2493 but also helps to declutter. Mass closures of the backlog could hide away interesting ideas that were created a long time ago.
This would mark issues / PRs with 60 days without activity as stale and close them 7 days afterwards. Those are the default values by Github, I find them reasonable but am not set on them.
Before merging a new tag 'no-activity' would need to be added

**Comment by eeintech** [comment]
> Mass closures of the backlog could hide away interesting ideas that were created a long time ago.

How do you think that closing all old, stale issues help "revealing" the interesting ideas? By forcing people to keep them open? I don't think that's going to work out well...

**Comment by SchrodingersGat** [comment]
A lot of the "stale" PRs are due more to lack of developer time than anything else.. I think we should just keep working our way through them as we are now

**Comment by matmair** [comment]
> > Mass closures of the backlog could hide away interesting ideas that were created a long time ago.
> 
> How do you think that closing all old, stale issues help "revealing" the interesting ideas? By forcing people to keep them open? I don't think that's going to work out well...

I think I did not formulae that well. Old issues would not be touched, only new things (starting 2022-01-01). Mass closures are bad in my opinion.
Forcing ppl. to interact all ~2 Months to keep something on a roadmap helped a lot in work projects I am involved with. It keeps things that were not well thought out to a minimum and reduces uneccesarry dev work.
Once something gets assigned a milestone or assignee it would not be affected by the action, only things that are not on a roadmap and are not 'owned' by any dev - so no one want's to do it and there is no timeline.

**Comment by matmair** [comment]
> A lot of the "stale" PRs are due more to lack of developer time than anything else.. I think we should just keep working our way through them as we are now

I think there are a lot of issues that the OP is not even interested in anymore (see the none responses in #1421). I think bumping ppl. would help keep them engaged somewhat and keep the backlog clean of stuff without stakeholders.

**Comment by eeintech** [comment]
> I think I did not formulae that well. Old issues would not be touched, only new things (starting 2022-01-01).

Oh I see, I guess in that sense I would be voting in favor :+1:

**Comment by SchrodingersGat** [comment]
@matmair understood, yes now it seems like a very good idea!

**Pull request merged**
