### PR TITLE
Last Connection date for user in admin panel

### PR DESCRIPTION
**Pull request by Bbillyben**
Hi, there, 
I'm not sure on which branch to pr this tiny modif, let me know.
That's my first step in django workflow.

It's not really usefull, even not from a FR, but that's something I was looking for, and find a way in my django readings.

This simple addition to display last connection for each user in user admin panel.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3747"></a>

### CODE REVIEW

**Comment by matmair** [comment]
Hi there @Bbillyben !
Thanks for your contribution. Two suggestions:
-a) Please create a new branch for each contribution - that way your changes are kept clean even if merging takes longer
-b) You can check for the errors that keep happening by setting up the dev environment: https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md#bare-metal

**Comment by Bbillyben** [comment]
Hi @matmair 

Thanks for the suggestions. 

a/ Would you mean create a new branch in my fork ? 

b/ Sorry for the errors, I've set up the docker dev env. but the "invoke style" commands is unknown (`No idea what 'style' is!` )
..... and i haven't swith repo yet, so not commit in my fork yet

**Comment by matmair** [comment]
@Bbillyben 
a/ yes
b/ if you run the setup command your git is modified to run the command on commit, no need for `inv style`.

**Comment by Bbillyben** [comment]
Ok noted @matmair,

I'm currently making some test on pre-commit process ang git. 

Should I have to close this one and re-PR ?

**Comment by Bbillyben** [comment]
Thanks @SchrodingersGat, I got the point 1/ pre-commit test 2/ dedicated branch !

**Pull request merged**
