### PR TITLE
BOM - show purchase price

### LINKED ISSUE #1889: Use purchase_price for BOM cost calculation
Current BOM pricing approach implies that all BOM items should be supplier parts with pre-filled price breaks. And it gives you the cost of item if you buy all parts from corresponding suppliers.
While in my case, I assemble my projects from parts I already have. So I would like to know how much it will cost to assemble this item based on parts I have in stock (purchase price).

Please consider replacing supplier price with purchase price for the BOM pricing view. This could be the global/user settings option.
@matmair what do you think?

### PR DESCRIPTION
**Pull request by matmair**
Shows purchase prices for a BOM in the pricing modal and prices tab.
Suggested by @sintech

Fixes #1889

### CODE REVIEW

**Comment by sintech** [comment]
Thank you @matmair looks exactly what I needed.
Unfortunately it gives me an error on my test BOM Part
image
image

**Comment by sintech** [comment]
Thank you @matmair looks exactly what I needed.
Unfortunately it gives me an error on my test BOM Part:
image

It fails for sub-parts without purchase price, I think some check is needed.

**Comment by matmair** [comment]
@sintech should work now.
The question is if there should be some kind of warning if not all parts are covered by purchase prices. The current method is to then use BOM and buy prices.

**Comment by sintech** [comment]
> The question is if there should be some kind of warning if not all parts are covered by purchase prices. The current method is to then use BOM and buy prices.

I think it should be ok to have parts with no pricing info at all and purchase price in particular. They just have to be excluded from BOM price calculation.

**Comment by eeintech** [comment]
@matmair So in this example:

image

Maybe we should have some kind of warning stating that the "Cost" lines are based on incomplete pricing information?
I guess same for the "Purchase Price" line?

**Comment by matmair** [comment]
@eeintech @sintech so a small tooltip with information what information was used for calculation would be ok? I would include multiple levels of information depending on the settings.

**Comment by sintech** [comment]
@matmair I think a tooltip about what prices was used for pie chart is also needed. I mean the precedence: supplier cost > internal > purchase.
And that `Unit cost` includes supplier cost + internal cost.

**Comment by matmair** [comment]
@sintech moved this tooltip FR into a new issue

**Comment by matmair** [comment]
@sintech does this PR work for you now?

**Comment by sintech** [comment]
@matmair it is strange but it gives me an error
image

Maybe it's because I dont have any stock item for this part anymore :(
image

**Comment by sintech** [comment]
@matmair seems to be working now. I had git issues...
It is pity that all purchase price info has lost with deletion of stock...

**Comment by matmair** [comment]
@SchrodingersGat this would be ready for review and merge

**Comment by SchrodingersGat** [comment]
Thanks @matmair this looks good on my end.

**Pull request merged**
