### PR TITLE
Add sanitation for SVG attachments

### PR DESCRIPTION
**Pull request by matmair**
This PR adds sanitation for SVG files.

See huntr

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3701"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Nice, this looks very clean. Is there a simple unit test (i.e. a dodgy svg file) we could throw at it?

**Comment by matmair** [comment]
@SchrodingersGat I will add some tests once the CI is run through

**Comment by SchrodingersGat** [comment]
@matmair friendly bump that CI has passed here :)

**Comment by matmair** [comment]
@SchrodingersGat was already writing them - those should be enough for now.

**Pull request merged**
