### PR TITLE
Use error report fork

### LINKED ISSUE #4848: Admin panel error_report HTML iFrame "refused to connect"
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Chrome displays error "localhost refused to connect" in the HTML iFrame window of errors in the admin view.

console putput as follows:
Refused to display 'http://localhost:8000/' in a frame because it set 'X-Frame-Options' to 'deny'.

### Steps to Reproduce

1. Set up your server with docker
2. Produce an error
3. Look at the page

### Expected behaviour

Showing the frame

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.0 dev
Django Version: 3.2.19
Commit Hash: f2ee65e83
Commit Date: 2023-05-18
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by matmair**
This PR switches django-error-report to a maintained fork. That fork also addresses #4848.
Closes #4848

### CODE REVIEW

**Review by SchrodingersGat — APPROVED** [review]

**Comment by matmair** [comment]
Still needs a live test but should be ready @LavissaWoW

**Comment by SchrodingersGat** [comment]
@matmair CI is failing here, might need a closer look

**Comment by SchrodingersGat** [comment]
@matmair be nice to merge this one in if you have a chance to look at the issues :)

**Comment by matmair** [comment]
@SchrodingersGat this is ready for review and merge

**Comment by SchrodingersGat** [comment]
Thanks @matmair :)

**Pull request merged**
