### PR TITLE
Move more paths to basic path

### PR DESCRIPTION
**Pull request by matmair**
Refactor to remove unnecessary usage of re_path

### CODE REVIEW

**Comment by wolflu05** [comment]
Does this help to reduce the open api spec generation warnings? And how much regex paths do we use now?

**Comment by matmair** [comment]
That was not the goal, I have not looked into the effects on schema generation. After merge there will be 22 re_paths left. All of those use some form of regex matching.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by wolflu05** [comment]
Ok, thanks for checking. I like the change, but I'm curious what your intention then is behind? 

I now also checked the impact on schema generation warning, but it seems like it doesn't change much, it adds a few more warnings, but that has to be fixed all differently.

**Comment by matmair** [comment]
To make it harder to introduce errors with paths. Re_path where it is not needed always bothers me.

**Comment by matmair** [comment]
I had to roll back a few paths (label/report printing routes) as I do not want to touch the API methods/behaviour in this PR. This would be ready for a review now.

Note: The PR lowers the coverage a bit as the total LoC is lowered

**Comment by wolflu05** [comment]
Is there any option so that one don't need the / at the end? I think that is really weird, and I always forgot about that and wonder why the api route doesn't work. Is this actually a standard? I never seen this on other REST apis. The only thing I can find about it is this [quote](https://stackoverflow.com/a/76750369).

**Comment by matmair** [comment]
Trailing slash is the default behaviour in DRF applications. No idea why but I have no intention to change it with this PR as that would be a new API iteration and a breaking change.

**Comment by SchrodingersGat** [comment]
Thanks @matmair

**Pull request merged**
