### PR TITLE
Bump python version

### PR DESCRIPTION
**Pull request by matmair**
This PR bumps the python version for the translation workflow to fix the currently failing test.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2994"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
If we are changing to 3.9 here should we upgrade this across the board?

**Comment by matmair** [comment]
I bumped the check action as well

**Comment by matmair** [comment]
@SchrodingersGat 3.8 would be fine too. 3.7 is from 2018 and needs fills for a bunch of stuff.

**Comment by SchrodingersGat** [comment]
Would you agree that we should also:

- update python version in docker image
- update min required python version in the docs (for bare-metal install)

**Comment by matmair** [comment]
@SchrodingersGat alpine 3.13 is containing python 3.8.8 currently - so it should be fine.  PR updating the docs is otw.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by matmair** [comment]
Hopefully, the CI now runs through.

**Pull request merged**
