### PR TITLE
Add support for using Redis as a cache and a broker

### PR DESCRIPTION
**Pull request by nwns**
- [x] Check if the TCP socket options work on windows (if InvenTree supports windows)
- [x] Figure out how to create or modify a test action to test this code path

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2165"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Nice @nwns  - what still needs to be implemented here?

**Comment by SchrodingersGat** [comment]
@nwns this is still marked as a draft - is there anything else you want to implement?

**Comment by nwns** [comment]
@SchrodingersGat Trying to work out how to get one of the tests (probably the postgres one or a separate test) to use redis to make sure that the code path of storing in Redis is tested.

**Comment by SchrodingersGat** [comment]
No worries, let me know if you need any assistance working that out

**Comment by nwns** [comment]
@SchrodingersGat This should be good to go.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Thanks @nwns :) looks good!

**Pull request merged**
