### PR TITLE
Cleaner part details

### PR DESCRIPTION
**Pull request by eeintech**
To build up on the part page refactoring started in #1811 

## Screenshots

image

image

image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I'd like to see the available stock status a bit more "obvious" - it looks like your changes here have made it a lot smaller.

**Comment by eeintech** [comment]
@SchrodingersGat What about this:

image

image

image

**Comment by sintech** [comment]
But do we really need this table with duplicate info below?
Why don't just move table and all the switches to separate tab (or modal) and leave current part name and description untouched.
Because it is more compact and visually separates description from name.

**Comment by eeintech** [comment]
@SchrodingersGat Let me know what do you think about the new details panel.

For reference, this is what the same part looks like with `master` and a lot of options enabled:

image

**Comment by eeintech** [comment]
@SchrodingersGat Not sure why the "Python Bindings" action is failing, haven't changed anything related to python...

**Comment by SchrodingersGat** [comment]
This has been fixed now.

**Comment by eeintech** [comment]
@SchrodingersGat Not sure what is your verdict on this new layout, I thought letting the user decide if the part details should be shown would be a good idea, also added IPN and name to the list for easy copy-paste using the copy shortcut button.

image

image

The show/hide setting is persistent in the local session :smiley:

**Comment by SchrodingersGat** [comment]
@eeintech sorry this one had dropped off my radar. I like the new addition of the drop-down button.

**Comment by eeintech** [comment]
@SchrodingersGat No problem, I hope you like it!

**Pull request merged**
