### PR TITLE
Add tests for report API

### PR DESCRIPTION
**Pull request by miggland**
Adds more tests for report and label API.

Prompted by https://github.com/inventree/InvenTree/issues/6213

### CODE REVIEW

**Comment by miggland** [comment]
Currently stuck with 403 results

**Comment by SchrodingersGat** [comment]
Something strange is going on with the permissions. The API endpoints should determine required permissions based on the model type. You can tweak the permissions assigned to the test user here:

https://github.com/inventree/InvenTree/blob/9b1a310ffe2416ed8e7ffd282ec36103e301e844/InvenTree/InvenTree/unit_test.py#L111

Note that when I run these tests with `superuser = True` added to the test class, the 403 errors go away.

**Comment by miggland** [comment]
I was expecting the PATCH on build to fail, since I have not merged the the fix from #6218 into this branch yet. However, it seems to work through the API test methods.

The data-export failure is another surprise though.. manually running `export-records` and then `import-records` seems to work fine.

**Comment by SchrodingersGat** [comment]
@miggland please note I am working on a fix for the data importing errors:

https://github.com/inventree/InvenTree/pull/6253

**Comment by miggland** [comment]
I added similar tests for labels as well, since those api tests were limited (and marked with "TODO".. )

**Comment by SchrodingersGat** [comment]
Thanks @miggland !!

**Pull request merged**
