### PR TITLE
Optimize test statistic queries

### PR DESCRIPTION
**Pull request by martonmiklos**
Replace individual queries with joins in the test statistic queries

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@martonmiklos for some reason when testing this I am getting a 404 error which I did not seem to be getting before:

image

This is using part 903 on the demo dataset

image

Note that I also get the same 404 on master branch - so it is not related to this PR.

Note also that the "by-build" API endpoint seems to function correctly still:

image

**Comment by martonmiklos** [comment]
> @martonmiklos for some reason when testing this I am getting a 404 error which I did not seem to be getting before:
> 
> image
> 
> This is using part 903 on the demo dataset
> 
> image
> 
> Note that I also get the same 404 on master branch - so it is not related to this PR.
> 
> Note also that the "by-build" API endpoint seems to function correctly still:
> 
> image

I will look into it, I kept the PR in WIP because I want to add API tests.

**Comment by martonmiklos** [comment]
> @martonmiklos for some reason when testing this I am getting a 404 error which I did not seem to be getting before:

Well I have to admit that I seriously messed it up here:

https://github.com/inventree/InvenTree/pull/7789/files#diff-0f0aa474fda00aebc321caa9ea7f5e241333dcee07579fad73074ed6e559663bL1323

My django knowledge appraching zero from the negative side, I would be glad if you could check whether my approach is proper here too:
https://github.com/inventree/InvenTree/pull/7789/files#diff-d4349f553750c97015938a8c71f6b6a6e6d285bd1855b35454b10d4b99c08a08L888

**Comment by matmair** [comment]
@martonmiklos can you be bit more specific what you are trying to do in the linked row? Maybe comment on the code in the PR

**Comment by martonmiklos** [comment]
> @martonmiklos can you be bit more specific what you are trying to do in the linked row? Maybe comment on the code in the PR

Could you please link the row?

**Comment by matmair** [comment]
Could you link what specifically you want to be reviewed (what are your concerns) in which code section?

**Comment by martonmiklos** [comment]
> Could you link what specifically you want to be reviewed (what are your concerns) in which code section?

There are two things: the part statistic queries accumulated the pass-fail counts by iterating over the affected build outputs. This had been optimized by using filters which translates to joins in the SQL.

The other issue what had been highlighted by  was higlighted [here](https://github.com/inventree/InvenTree/pull/7789#issuecomment-2264378910) with accessing the serializer here:
https://github.com/inventree/InvenTree/pull/7789/files#diff-0f0aa474fda00aebc321caa9ea7f5e241333dcee07579fad73074ed6e559663bL1323

**Comment by SchrodingersGat** [comment]
@martonmiklos now that the new user interface supports proper plugins (you can see [an example here](https://github.com/inventree/inventree-order-history)) I would like to consider whether the "test statistics" could be offloaded to a plugin. In my opinion it is not quite a "core" feature but would certainly be useful to some users!

If you are open to this, I can help set it up as a plugin, and dedicate some time to looking into what is going on with the query efficencies here...

**Comment by martonmiklos** [comment]
> @martonmiklos now that the new user interface supports proper plugins (you can see [an example here](https://github.com/inventree/inventree-order-history)) I would like to consider whether the "test statistics" could be offloaded to a plugin. In my opinion it is not quite a "core" feature but would certainly be useful to some users!
> 
> If you are open to this, I can help set it up as a plugin, and dedicate some time to looking into what is going on with the query efficencies here...

Hi @SchrodingersGat 

Sure I am open to transforming it to plugin. The main intention is to decouple it from the main repo to get rid from it to reduce the maintenance burden, or the plan is the same as the printing plugins: making them optional?

I did not have time to work on InvenTree recently, but I hope this will change in the near future.

**Pull request closed without merging**
