### PR TITLE
[PUI] SSO improvments

### PR DESCRIPTION
**Pull request by matmair**
This addresses various ux issues/bugs in the SSO implementation in PUI.

Fixes https://github.com/inventree/InvenTree/issues/7972

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat @wolflu05  this now works but is not very beautiful; is this changeset ok or should we (I) search for a different solution?

**Comment by SchrodingersGat** [comment]
@matmair can you please provide a simple overview of what the issue was that you are fixing here?

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair any comments on the changes in `social_auth_urls.py`?

**Comment by matmair** [comment]
The current arrangement of URL definitions leads to errors in the discovery of the OIDC endpoints, the new one fixes that.

**Pull request merged**
