### PR TITLE
CI-Actions: Security fixes

### PR DESCRIPTION
**Pull request by matmair**
This PR:
- updates the shared actions to run on a current version of node
- defines the workflow permission for actions on the top-level to ensure OIDC tokens are issued with the lowest possible permissions

### CODE REVIEW

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair I believe that this PR has broken the [translations workflow](https://github.com/inventree/InvenTree/blob/master/.github/workflows/translations.yml)

You can see that the workflow [has been broken since then](https://github.com/inventree/InvenTree/actions/workflows/translations.yml)

I assume it is due to the permissions change. Should we revert this for this file, or add an additional permission?

**Comment by matmair** [comment]
You are right, will create a PR to address this

**Comment by SchrodingersGat** [comment]
@matmair great, much appreciated :)

**Comment by matmair** [comment]
PR created, dumb error

**Pull request merged**
