### PR TITLE
Form focus

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Closes https://github.com/inventree/InvenTree/issues/7005
- Adds ability to focus on a particular field

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@wolflu05 does not seem to be working, but perhaps I am calling `form.setFocus` in the wrong place?

**Comment by wolflu05** [comment]
Have you tried initially loading the form and then just make a slight change to the code (e.g. add a console log) and then hit cmd s to trigger fast refresh? Then try to focus the browser window (don't click inside otherwise the focus is lost again), and see if the field is focused now?

I suspect that when this useEffect normally runs the field is not already registered. You could find that out by also logging form.getValues() before the setFocus call.

**Comment by SchrodingersGat** [comment]
Is there a hook which runs only after the form has been opened / initially rendered?

**Comment by wolflu05** [comment]
Have you tried adding the setFocus method to the `useEffects` dependencies, and also use a sperate effect?

```tsx
useEffect(() = {
  console.log("Here", form.getValues())
  form.setFocus(focus);
}, [form, focus]); // and also try form.setFocus directly
```

If nothing helps, the only idea I have is to schedule a timer, but that's not a great solution:

```tsx
useEffect(() = {
  const id = setTimeout(() => {
    console.log("Here", form.getValues())
    form.setFocus(focus);
  }, 1); // normally 1ms should work here as this then gets executed on the next tick after the first render, but make sure to also test some significantly longer values just to make sure (e.g. 1000). 
  return () => clearTimeout(id);
}, [form, focus]);
```

**Comment by SchrodingersGat** [comment]
@wolflu05 thanks, seems to work pretty well now :)

**Comment by wolflu05** [comment]
Im not sure if adding the fields to the useEffect dependencies has some side effects. E.g. in forms where a state is connected to a field'a value, the fields variable changes all the time and so entering a text in such a input field results in focusing the focus field after each keypress. (But I have not tested it)

**Comment by SchrodingersGat** [comment]
The form focus should only happen once, I think. Once it is set it is not tested again. But let's keep an eye out for any issues

**Pull request merged**
