### PR TITLE
Shipment Reports

### PR DESCRIPTION
**Pull request by fuzeman**
This pull request implements sales order shipment reports which will enable greater flexibility for the generation of packing lists.

I found some previous discussions in #5232 and #62 around packing lists, but the solutions discussed appeared to be only suitable for generating a packing list of an entire sales order. I usually have long-running sales orders with weekly shipments requiring individual packing slips and it will be great to have this integrated inside InvenTree.

-----

**Sample Report (included in pull request):**

SalesOrderShipment

### CODE REVIEW

**Review by matmair — APPROVED** [review]
Looks good to me, thank you for the PR. Let's see if all style checks pass - this is good to merge from my POV

**Comment by SchrodingersGat** [comment]
@fuzeman nice addition, thanks!!

**Comment by fuzeman** [comment]
Thanks.

I've been using InvenTree almost daily for build orders and stock management over the last 3 years and finally had the push to make my first contribution. Hopefully more PR's to come when time allows.

**Comment by SchrodingersGat** [comment]
Contributions are always welcome 🤗 And it is wonderful to hear such feedback

**Comment by fuzeman** [comment]
Just noticed that the "Attach to Model on Print" functionality probably won't work as `SalesOrderShipment` doesn't support attachments. It would be simple enough to enable attachments on `SalesOrderShipment`, but I'm not sure how we would view them. Maybe they should be aggregated and displayed under the `SalesOrder` attachment list?

I'll take a look, but let me know if you have any thoughts.

**Comment by fuzeman** [comment]
After taking a closer look at how attachments are implemented, the simplest option would probably be a custom `create_attachment` implementation on `SalesOrderShipment` which stores the attachments on the parent `SalesOrder` instance. The only remaining concern would be if `SalesOrderShipment` should have `InvenTreeAttachmentMixin` which would create a redundant `SalesOrderShipment` model type on the `Attachment` model.

**Comment by SchrodingersGat** [comment]
@fuzeman I think your suggested approach is reasonable, but could we have a situation where a user could manually create an attachment against a `SalesOrderShipment`? Probably not, or not easily, I'd imagine. In which case the redundant model type is likely fine. There is nowhere where the user has to manually select which model to upload an attachment against.

**Comment by fuzeman** [comment]
@SchrodingersGat Thanks. See PR #8231.

**Pull request merged**
