### PR TITLE
Update django money / py-moneyed dependencies

### PR DESCRIPTION
**Pull request by 30350n**
These dependencies are quite outdated and seemingly only, because InvenTree depends on the deprecated (and now removed) `moneyed.localization` module for formatting `Money` objects. This PR replaces said function with a modified version of `babel`s `format_currency` function, which allows for setting the number of decimal places.

I've also dropped the `include_symbol` argument from the `render_currency` function, as it hasn't been used anywhere as far as I can tell and including it would make the implementation of the new `format_money` function more complicated.

Instead, the `format_money` function offers a `format` argument, which can be used to exactly define the formatting according to the [babel pattern syntax](https://babel.pocoo.org/en/latest/numbers.html). This argument doesn't get used rn, but could be made available in the settings, to completely customize the currency formatting.

The main motivation for updating is me not being able to import build order BOMs from suppliers like DigiKey, because they include the currency symbol (in my case `€`) in their `.csv` files. I've already looked into this a while back, so I don't remember the exact behavior anymore, but I think it couldn't parse anything containing `€` at all while `EUR` worked fine (no currency symbol also does). From my testing I gathered that this would just work with `django-money>=3.0`, but that breaks the formatting completely, thus this PR. (I'm currently running an ugly fix which just gets rid of the `€` on my instance.)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@30350n seems reaonsble, not opposed to this. Can you please add some simple unit tests to ensure that the new `format_money` function returns the expected results?

**Comment by 30350n** [comment]
Yep, will do! I thought I'd just create the PR first to run through all the existing tests first because I'm fully expecting them to fail ^^

**Review by matmair — COMMENTED** [review]
Nice of you to tackle this @30350n.
2 things come to my mind regardings this:
- early release of the upgrade pymoney threw problems while doing currency conversions (at least in the CI)
- I do not fully see the point of the migrations. Could you look into what has changed in the backend that those are required? We have instrumented the default model functions a bit so there might be breaking things here.

Glad you are taking this on, thank you for your continued engagement

**Comment by 30350n** [comment]
> I do not fully see the point of the migrations. Could you look into what has changed in the backend that those are 

I honestly also don't really know. From what I can tell, it seems like the only thing that got added was the `null=True` option for the `CurrencyField`, not sure if that's required/desired even? If the migrations aren't required, how do I stop the pipeline from acting up?

> early release of the upgrade pymoney threw problems while doing currency conversions (at least in the CI)

CI tests seem to pass (except for the migrations part). I'll add the currency formatting tests requested and also take a look at the currency conversion tests. Once that's done I can also just deploy this on my private instance and see if everything seems fine there.

**Comment by matmair** [comment]
> I honestly also don't really know. From what I can tell, it seems like the only thing that got added was the `null=True` option for the `CurrencyField`, not sure if that's required/desired even? If the migrations aren't required, how do I stop the pipeline from acting up?

I do not think we need that change - we will have to change that on a model level to not create migrations

> CI tests seem to pass (except for the migrations part). I'll add the currency formatting tests requested and also take a look at the currency conversion tests. Once that's done I can also just deploy this on my private instance and see if everything seems fine there.

The migrations test probably use the old function still; if we have full coverage of all new code and test against currencies from around the globe we should be fine

**Comment by SchrodingersGat** [comment]
@30350n you could try explicitly setting `null=False` in the `__init__` method of `InvenTreeModelMoneyField`:

https://github.com/inventree/InvenTree/blob/8308f36923a53ffc56be6bfd90c99e09493bb9e4/InvenTree/InvenTree/fields.py#L65

**Comment by 30350n** [comment]
Here we go!

I also threw together a quick script to test the new and old functions against each other exactly (and managed to find a bug while doing so).

For reference:
```py
import moneyed
from moneyed import Money
from moneyed.localization import format_money, _sign, DEFAULT

from babel import Locale
from babel.numbers import parse_pattern

from random import seed, uniform, choices

def format_money2(money: Money, decimal_places: int = None, format: str = None) -> str:
    locale = Locale("EN")
    if format:
        pattern = parse_pattern(format)
    else:
        pattern = locale.currency_formats["standard"]
        if decimal_places is not None:
            pattern.frac_prec = (decimal_places, decimal_places)

    return pattern.apply(
        money.amount,
        locale,
        currency=money.currency.code,
        currency_digits=decimal_places is None,
        decimal_quantization=decimal_places is not None,
    )

_sign(DEFAULT, moneyed.EUR, prefix="€")   # original: _sign(DEFAULT, moneyed.EUR, suffix=' €')
_sign(DEFAULT, moneyed.GBP, prefix="£")   # original: _sign(DEFAULT, moneyed.GBP, prefix='GB£')
_sign(DEFAULT, moneyed.CAD, prefix="CA$") # original: _sign(DEFAULT, moneyed.CAD, prefix='C$')
_sign(DEFAULT, moneyed.CHF, prefix="CHF") # original: _sign(DEFAULT, moneyed.CHF, prefix='Fr.')
_sign(DEFAULT, moneyed.CNY, prefix="CN¥") # original: _sign(DEFAULT, moneyed.CNY, prefix='¥')

seed(1337)
results = []
for value in [uniform(0.000001, 1) for _ in range(50)] + [uniform(1, 1000000) for _ in range(50)]:
    for currency in ("USD", "EUR", "JPY", "GBP", "AUD", "CAD", "CHF", "CNY"):
        for decimal_places in range(0, 6):
            money = Money(value, currency)
            old = format_money(money, decimal_places=decimal_places, locale="EN_US")
            new = format_money2(money, decimal_places=decimal_places)
            results.append((value, currency, decimal_places, new))
            if old != new:
                print(old, new, value, currency, decimal_places)

```

So the only thing that should change with this is the position of the currency symbols (as it's dependent on the language set now) and in some cases the symbols themselves. For the currencies I tested the changes are:

- `" €"` suffix -> `"€"` prefix
- `"GB£"` -> `"£"`
- `"C$"` -> `"CA$"`
- `"Fr."` -> `"CHF"`
-  `"¥"` -> `"CN¥"`

**Comment by 30350n** [comment]
> @30350n you could try explicitly setting `null=False` in the `__init__` method of `InvenTreeModelMoneyField`:
> 
> https://github.com/inventree/InvenTree/blob/8308f36923a53ffc56be6bfd90c99e09493bb9e4/InvenTree/InvenTree/fields.py#L65

That won't help as it's `django_money`s `CurrencyField` which is causing the migrations to happen, not the `InvenTreeModelMoneyField`, right?

**Comment by SchrodingersGat** [comment]
> > @30350n you could try explicitly setting `null=False` in the `__init__` method of `InvenTreeModelMoneyField`:
> > https://github.com/inventree/InvenTree/blob/8308f36923a53ffc56be6bfd90c99e09493bb9e4/InvenTree/InvenTree/fields.py#L65
> 
> That won't help as it's `django_money`s `CurrencyField` which is causing the migrations to happen, not the `InvenTreeModelMoneyField`, right?

I think it should work. All our money fields use `InvenTreeModelMoneyField` which use `CurrencyField` under the hood

**Comment by 30350n** [comment]
> I think it should work. All our money fields use `InvenTreeModelMoneyField` which use `CurrencyField` under the hood

The money fields aren't the problem. Also they are based on `ModelMoneyField`, not `CurrencyField` from what I can tell. The `CurrencyField`s in question are used as is, there's no wrapper around them.

**Comment by SchrodingersGat** [comment]
The disconnect here is that the `InvenTreeModelMoneyField` is actually *two* fields wrapped into one. 

Example here is `order.PurchaseOrderLineItem.purchase_price`:

https://github.com/inventree/InvenTree/blob/dfc4fa7584b0dd5a0c75d19f1ab64e1dbc0b4201/InvenTree/order/models.py#L1205

Note how we do not defined a `purchase_price_currency` field, but this is what is getting touched in the migration. Behind the scenes, the djmoney "money" field is really two fields

**Comment by 30350n** [comment]
Ah okay, gotcha! Thanks for explaining that.

Looking at it though ... it seems like everywhere `InvenTreeModelMoneyField` gets used, `null` is already set to `True`. From what I can tell, the migrations get triggered by [this](https://github.com/django-money/django-money/commit/a8c5d60464f7ae68adb433eeeeacfabe657e1902#diff-0b1ce35a3277e63b0a1f1bd7c798dbc656d3ab504c188d6d9553095759caf800L275) change in `django_money`. Which kinda makes me think they might just be correct?

Searching further [this](https://github.com/django-money/django-money/blob/9e3442ab3e6cc89c4662206c6c3f454ba4eca169/djmoney/models/fields.py#L115) also seems to point in that direction.

**Comment by 30350n** [comment]
Also I don't think it's possible to somehow circumvent this migration via changes in the `__init__(...)` method, but something like this would work:

```py
    def contribute_to_class(self, cls, name):
        null_before = self.null
        self.null = False
        super().contribute_to_class(cls, name)
        self.null = null_before
```

That still leaves [this](https://github.com/inventree/InvenTree/pull/5778/files#diff-01dde0b9421f6001cbbe1ac91146bdcd1b5f0c59ce95beba8dc549fd3d588e08R1) migration though, which seems to have gone through the same change multiple times already 😅 

(added with 0038_auto_20201112_1737.py)
`field=djmoney.models.fields.CurrencyField(choices=common.settings.currency_code_mappings(), default=common.settings.currency_code_default(), editable=False, max_length=3),`
=> (altered in 0047_auto_20210701_0509.py)
`field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),`
=> (altered in 0053_auto_20201110_0513.py)
`field=djmoney.models.fields.CurrencyField(choices=common.settings.all_currency_codes(), default=common.settings.currency_code_default(), editable=False, max_length=3)`
=> (altered in 0065_auto_20210701_0509.py)
`field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),`
=> (would be altered again now in the new migration, though without seemingly changing anything)
`field=djmoney.models.fields.CurrencyField(choices=[], default='', editable=False, max_length=3),`

**Comment by 30350n** [comment]
@matmair The `test_patterns` in `.deepsource.toml` seem to be messed up.

This should be correct:

```
test_patterns = [
  "**/test_*.py",
  "**/test.py",
  "**/tests.py"
]
```

**Comment by SchrodingersGat** [comment]
Not sure why it is generating an unchanged migration...

**Comment by matmair** [comment]
I was wondering why that was not registering every time. In many cases, it worked, so not sure if they are using regex on the full file path and the filename.

**Comment by 30350n** [comment]
> I was wondering why that was not registering every time. In many cases, it worked, so not sure if they are using regex on the full file path and the filename.

They aren't using regexes at all, but glob patterns.

**Comment by 30350n** [comment]
> @matmair The `test_patterns` in `.deepsource.toml` seem to be messed up.
> 
> This should be correct:
> 
> ```
> test_patterns = [
>   "**/test_*.py",
>   "**/test.py",
>   "**/tests.py"
> ]
> ```

Can somebody just directly push a commit that fixes this to master or should I create a separate PR? Probably shouldn't be part of this.

**Comment by SchrodingersGat** [comment]
@30350n have made a separate PR for that - https://github.com/inventree/InvenTree/pull/5812

Where are we at with this one?

**Comment by 30350n** [comment]
> @30350n have made a separate PR for that - #5812

Gotcha, just reverted the change.

> Where are we at with this one?

Imo, this would be ready to merge. I think the migrations are fine/necessary the way they are.

**Comment by SchrodingersGat** [comment]
Nice work again @30350n , thanks for the contribution. I'll merge when all checks pass

**Comment by 30350n** [comment]
Wait, stuff parsed here. Eh, got an error from some pipeline running on my fork for some reason. Reverted that again, let's see if this parses again now.

**Comment by SchrodingersGat** [comment]
@30350n thanks for this :)

**Comment by SchrodingersGat** [comment]
@30350n unfortunately merging this has broken our docker builds

```
2023-10-31T12:26:03.6320807Z ======================================================================
2023-10-31T12:26:03.6321472Z ERROR: test_ref_field (order.test_migrations.TestRefIntMigrations)
2023-10-31T12:26:03.6322398Z Test that the 'reference_int' field has been created and is filled out correctly.
2023-10-31T12:26:03.6323197Z ----------------------------------------------------------------------
2023-10-31T12:26:03.6323713Z Traceback (most recent call last):
2023-10-31T12:26:03.6324913Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/contrib/unittest_case.py", line 54, in tearDown
2023-10-31T12:26:03.6325843Z     self._migrator.reset()
2023-10-31T12:26:03.6326845Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/migrator.py", line 76, in reset
2023-10-31T12:26:03.6327879Z     call_command('migrate', verbosity=0, database=self._database)
2023-10-31T12:26:03.6329005Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
2023-10-31T12:26:03.6329928Z     return command.execute(*args, **defaults)
2023-10-31T12:26:03.6330878Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
2023-10-31T12:26:03.6331720Z     output = self.handle(*args, **options)
2023-10-31T12:26:03.6332763Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
2023-10-31T12:26:03.6333581Z     res = handle_func(*args, **kwargs)
2023-10-31T12:26:03.6334623Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
2023-10-31T12:26:03.6335540Z     post_migrate_state = executor.migrate(
2023-10-31T12:26:03.6338837Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
2023-10-31T12:26:03.6340225Z     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6341782Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
2023-10-31T12:26:03.6343351Z     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6344881Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
2023-10-31T12:26:03.6346136Z     state = migration.apply(state, schema_editor)
2023-10-31T12:26:03.6347321Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
2023-10-31T12:26:03.6348653Z     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
2023-10-31T12:26:03.6350341Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
2023-10-31T12:26:03.6351357Z     self.code(from_state.apps, schema_editor)
2023-10-31T12:26:03.6352521Z   File "/home/***/InvenTree/order/migrations/0079_auto_20230304_0904.py", line 50, in update_purchase_order_price
2023-10-31T12:26:03.6353540Z     order.total_price = total_price
2023-10-31T12:26:03.6354491Z   File "/usr/local/lib/python3.10/site-packages/djmoney/models/fields.py", line 111, in __set__
2023-10-31T12:26:03.6355454Z     and self.field._currency_field.null
2023-10-31T12:26:03.6356474Z AttributeError: 'InvenTreeModelMoneyField' object has no attribute '_currency_field'
```

and

```
2023-10-31T12:26:03.6213495Z ======================================================================
2023-10-31T12:26:03.6214442Z ERROR: test_po_migration (order.test_migrations.TestAdditionalLineMigration)
2023-10-31T12:26:03.6218592Z Test that the the PO lines where converted correctly.
2023-10-31T12:26:03.6219539Z ----------------------------------------------------------------------
2023-10-31T12:26:03.6230801Z Traceback (most recent call last):
2023-10-31T12:26:03.6232400Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/contrib/unittest_case.py", line 54, in tearDown
2023-10-31T12:26:03.6233453Z     self._migrator.reset()
2023-10-31T12:26:03.6234576Z   File "/home/***/data/env/lib/python3.10/site-packages/django_test_migrations/migrator.py", line 76, in reset
2023-10-31T12:26:03.6235724Z     call_command('migrate', verbosity=0, database=self._database)
2023-10-31T12:26:03.6237039Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
2023-10-31T12:26:03.6238038Z     return command.execute(*args, **defaults)
2023-10-31T12:26:03.6239094Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
2023-10-31T12:26:03.6240025Z     output = self.handle(*args, **options)
2023-10-31T12:26:03.6241046Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 89, in wrapped
2023-10-31T12:26:03.6241952Z     res = handle_func(*args, **kwargs)
2023-10-31T12:26:03.6243037Z   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 244, in handle
2023-10-31T12:26:03.6244024Z     post_migrate_state = executor.migrate(
2023-10-31T12:26:03.6245073Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 117, in migrate
2023-10-31T12:26:03.6246307Z     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6247749Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
2023-10-31T12:26:03.6249947Z     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
2023-10-31T12:26:03.6251232Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
2023-10-31T12:26:03.6252179Z     state = migration.apply(state, schema_editor)
2023-10-31T12:26:03.6253385Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 126, in apply
2023-10-31T12:26:03.6254496Z     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
2023-10-31T12:26:03.6255893Z   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
2023-10-31T12:26:03.6257036Z     self.code(from_state.apps, schema_editor)
2023-10-31T12:26:03.6258039Z   File "/home/***/InvenTree/order/migrations/0079_auto_20230304_0904.py", line 50, in update_purchase_order_price
2023-10-31T12:26:03.6258883Z     order.total_price = total_price
2023-10-31T12:26:03.6260130Z   File "/usr/local/lib/python3.10/site-packages/djmoney/models/fields.py", line 111, in __set__
2023-10-31T12:26:03.6261078Z     and self.field._currency_field.null
2023-10-31T12:26:03.6261878Z AttributeError: 'InvenTreeModelMoneyField' object has no attribute '_currency_field'
```

**Pull request merged**
