### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by awiswasi**
Update Django to prevent a possible vulnerability to SQL injections, which was fixed in v4.0.4 that was released just 9 days ago. Also updating django-debug-toolbar to 3.2.1.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2849"></a>

### CODE REVIEW

**Comment by eeintech** [comment]
> Please fix conflicts with latest master :)

What are the conflicts? Seems like only the `requirements.txt` file has changed.
Is it possible to allow CI to run?

**Comment by SchrodingersGat** [comment]
@awiswasi it appears that these critical bug fixes have been backported to `3.2.13`:

https://docs.djangoproject.com/en/4.0/releases/3.2.13/

So, rather than having to deal with the headache of updating to django-v4, please adjust this PR to only update `django==3.2.13`

**Comment by eeintech** [comment]
Also the latest version of `django-debug-toolbar` is `3.2.4` and not `3.2.1` as pointed to in the updated `requirements.txt` file

**Review by matmair — CHANGES_REQUESTED** [review]
This would be a major version change in the underlying framework - this needs to be checked by all core-devs before any work goes ahead!

**Comment by matmair** [comment]
Ah I see everybody was here already.

@awiswasi thank you for looking out for security concerns!
Django is the framework everything builds on and follows semver - therefore there are a lot of breaking changes /depreciations associated with this PR. I can understand the suggested change but would very much prefer to switch to the patched version instead of a new major release.

**Comment by awiswasi** [comment]
> @awiswasi it appears that these critical bug fixes have been backported to `3.2.13`:
> 
> https://docs.djangoproject.com/en/4.0/releases/3.2.13/
> 
> So, rather than having to deal with the headache of updating to django-v4, please adjust this PR to only update `django==3.2.13`

You're right. I missed that last night and just realized there was no need for v4.0.4 so I apologize.
I'm pretty new to version control and to be fair, I have only ever made a few contributions before as I am still learning, so don't mind me if I miss something haha. I'm a C++ developer but I've been learning Python for the past 4 years and I'm just getting into security and code optimization!

With that being said, my take on this is that we are going to go with `django@v3.2.13` and `django-debug-toolbar@v3.2.4` correct?

**Comment by SchrodingersGat** [comment]
> With that being said, my take on this is that we are going to go with django@v3.2.13 and django-debug-toolbar@v3.2.4 correct?

Yep, this is correct thanks

**Review by awiswasi — COMMENTED** [review]
django@v3.2.13 and django-debug-toolbar@v3.2.4

**Comment by SchrodingersGat** [comment]
There are still conflicts as the requirements file has recently been changed. Please rebase this commit from the latest master

**Comment by awiswasi** [comment]
I tried to rebase but I got "Updates were rejected because the remote contains work that you do not have locally."
Wasn't `requirements.txt` changed correctly? Sorry if I'm missing something

**Comment by SchrodingersGat** [comment]
You will need to pull down the changes from the remote master/main branch before pushing back upstream

**Pull request closed without merging**
