### PR TITLE
[PUI] form enter key to submit

### LINKED ISSUE #7014: [FR] Pressing Enter key in input fields of forms regardless of input type should execute the Submit action
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I'm not really sure if it is to be treated as a bug or a feature request. When I edit a part's parameter where the input type is string (that can be typed), then pressing Enter when that input field has focus submits the form.

If, however, the field is a drop-down list with predefined choices, then pressing Enter when that field is focused has no effect (at least in Firefox).

It would be nice if the Enter key worked to submit the form in that case as well (without having to reach for the mouse and aim for that Submit button), as that's a standard and normally expected UI behavior.

parameter

parameter1

### Suggested solution

Will probably need a dedicated JS handler to get it done, not sure what modern frontend tech has to offer.

### Describe alternatives you've considered

n/a

### Examples of other systems

_No response_

### Do you want to develop this?

- [ ] I want to develop this.

### PR DESCRIPTION
**Pull request by timmyhadwen**
WIP potential fix for #7014. Adds onKeyDown handler to text fields so that when they are highlighted enter submits the form. Checks validation of form before submitting.

There is a potentially nicer solution for this by having the keydown event trigger whenever the form is visible, however this would mean that pressing enter inside a drop down (to select an item) would then submit the form without some complex focus logic.

Closes #7014

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@timmyhadwen thanks for the submission! Can you please fix the conflicts here, and ping me again so I can review

**Review by matmair — APPROVED** [review]
LGTM, good first PR!

**Comment by matmair** [comment]
@SchrodingersGat i solved the conflicts, ready for review and merge

**Comment by SchrodingersGat** [comment]
Thanks @timmyhadwen @matmair

**Comment by timmyhadwen** [comment]
Thanks for sorting that! Sorry haven't had a chance to get back to it!

**Pull request merged**
