### PR TITLE
SSO!

### LINKED ISSUE #625: Enhancement, SSO log-in
I work for a local startup that was/is in need of an inventory/BOM solution for our products. We found Inventree, and so far its been fantastic. 
 
We have Inventree securely hidden behind an SSO sign-in reverse proxy called [Pomerium](https://github.com/pomerium/pomerium), which is essentially our solution to not having a conventional intranet (and for working remotely).

This means we have to log in twice, once through google SSO, and a second time with InvenTree.

Is there a way to 1) unify the accounts (inventree SSO login) and/or 2) or have some other sort of automated log in? 

Thanks

### LINKED ISSUE #634: Registration and authentication improvements
I'm thinking of something in lines of what [django-allauth](https://github.com/pennersr/django-allauth) provides. Here's a description of some of the flows:

- Signup of both local and social accounts
- Connecting more than one social account to a local account
- Disconnecting a social account – requires setting a password if only the local account remains
- Optional instant-signup for social accounts – no questions asked
- E-mail address management (multiple e-mail addresses, setting a primary)
- Password forgotten flow
- E-mail address verification flow

### LINKED ISSUE #1421: Integrating with 3rd party PO/SO generation
First off, really impressive piece of software that fills a large hole in the open source community for SMB needs!  I have a question regarding 3rd party integration.  I would assume a large amount of people using InvenTree are small companies that use QB Online to handle purchase orders and Shopify/WooCommerce to handle sales orders.  I know InvenTree has an API, but I wasn't able to find any discussions on how people have specifically integrated InvenTree with other common applications.

Has anyone come up with a script to push PO's from Inventree to QB online, and/or pull sales orders from Shopify/WooCommerce into Inventree?  Or the more general question would be: how are people handling POs/SOs in multiple systems?

### PR DESCRIPTION
**Pull request by matmair**
This PR adds in SSO for #1421.

Changes / additions:
- [x] uses django-allauth -> activates contrib.sites apps
- [x] adds a few new urls for callbacks from external APIs
- [x] adds user settings for the connected social accounts
- [x] adds config-value for the providers
- [x] replace current email-flow with django-allauth's one
~~- [ ] adds admin settings which providers should be shown on login / signup~~Out of scope

Closes #634
Closes #625
Closes #1421

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat functionally this should be it - I have a few cosmetic things and a lot of settings / starting checks left to do.
- [ ] setting to turn on registration
- [ ] setting to turn on sso login
- [ ] setting to require email verification
- [ ] setting to disable password-forgot
- [ ] docs for all the settings
- [ ] examples for docs

Optional (would you like those)
- [ ] setting for selecting new users group-membership
- [ ] require self-registered users to be approved
- [ ] some solution to better customize the color of login buttons for the providers
- [ ] nicer e-mail templates

**Comment by matmair** [comment]
@eeintech input welcome

**Comment by matmair** [comment]
@eeintech thanks for checking!

- [x] 1.	Done
- [x] 2.	Done
- [x] 3.	Made crispy –> There will be a setting to make email required
- [x] 4.	Done
- [x] 5.	Made crispy -> This way is recommended for (securities sake)[ https://django-allauth.readthedocs.io/en/latest/views.html#logout-account-logout]; 
- [ ] 6.	TODO (banner go away)
- [ ] 7.	TODO (change to login – page)

**Comment by eeintech** [comment]
@matmair Sorry one more form I missed that really begs to be crispy-ed :smile: 

image

Everything looks good except 7. I guess I must not have been so clear about it and it might also be a security concern.
Instead of this step:

image

Can the login page be automatically loaded either immediately or after a few seconds?
Or at least have a button to return to the login page?

Right now the redirect to login page has to be done through changing the URL... Not user-friendly :grimacing:

**Comment by matmair** [comment]
@eeintech seems like i forgot to push the login changes - should work now. Also fixed the styling.

**Comment by eeintech** [comment]
@matmair  I'll take a look soon!

**Comment by eeintech** [comment]
Password reset form still not crispy?

image

That page still does not redirect / offer a way to return to login page:

image

**Comment by matmair** [comment]
@eeintech are you sure you were running the latest version? For me it looks like this:
grafik
and the redirection is also working

**Comment by eeintech** [comment]
@matmair This is the email and type of URL I'm getting when going through the "Forgot Password?" steps:

```

Hello from example.com!

You're receiving this e-mail because you or someone else has requested a password for your user account.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.

http://127.0.0.1:8000/accounts/password/reset/key/1-XXX-YYY/

In case you forgot, your username is Admin.

Thank you for using example.com!
example.com
```

When I browse `http://127.0.0.1:8000/accounts/password/change/` I get the same form as you:

image

But I'm not sure how can one access this form from the UI? :thinking:

**Comment by matmair** [comment]
Closes #634
Closes #625

**Comment by matmair** [comment]
> 
> 
> @matmair This is the email and type of URL I'm getting when going through the "Forgot Password?" steps:
> 
> ```
> 
> Hello from example.com!
> 
> You're receiving this e-mail because you or someone else has requested a password for your user account.
> It can be safely ignored if you did not request a password reset. Click the link below to reset your password.
> 
> http://127.0.0.1:8000/accounts/password/reset/key/1-XXX-YYY/
> 
> In case you forgot, your username is Admin.
> 
> Thank you for using example.com!
> example.com
> ```
> 
> When I browse `http://127.0.0.1:8000/accounts/password/change/` I get the same form as you:
> 
> image
> 
> But I'm not sure how can one access this form from the UI? 🤔

@eeintech ok now I understand what's happening. Sorry, I thought you meant the other view. I will take a look at this and fix it.

**Comment by matmair** [comment]
@eeintech fixed it now

**Comment by eeintech** [comment]
Yup looks good!

The confirmation form also needs to be crispy-ed :smiley: 

image

How do I access the password change URL from the UI? `http://127.0.0.1:8000/accounts/password/change/`

**Comment by matmair** [comment]
> 
> 
> Yup looks good!
> 
> The confirmation form also needs to be crispy-ed 😃
> 
> image
> 
> How do I access the password change URL from the UI? `http://127.0.0.1:8000/accounts/password/change/`

we have an integrated changing dialog so we dont

**Comment by eeintech** [comment]
Oh okay that's what I thought, but I had a doubt after you sent me a screenshot of the form and wanted to make sure I tested that too

**Comment by matmair** [comment]
@SchrodingersGat would be ready to review, doc follows shortly

**Comment by SchrodingersGat** [comment]
@matmair I'll have a look at this one soon. Been super busy these last couple of weeks.

**Comment by matmair** [comment]
> @matmair I'll have a look at this one soon. Been super busy these last couple of weeks.

@SchrodingersGat no problem. The docs are in a PR so maybe you can check if it is enough and understandable.

**Comment by matmair** [comment]
@SchrodingersGat when do you think we can pull this into a release branch? I would suggest targeting 0.6.0 .
The PR should be ready and docs are done.

**Comment by eeintech** [comment]
I'll let @SchrodingersGat go over that one, I did review a lot of it already. Unless you changed anything since last time?

**Comment by matmair** [comment]
@eeintech only unittest and merging in master

**Comment by SchrodingersGat** [comment]
Thanks for the reminder @matmair - it's on my list to look at very soon :)

**Comment by SchrodingersGat** [comment]
Ok, got it up and running, but I've hit an error screen pretty quickly ;)

I logged out, and hit the "reset password" button, and then entered my email address

**Note:** *I do not have an email backend running on my dev setup*

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/accounts/password/reset/

Django Version: 3.2.5
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'InvenTree.apps.InvenTreeConfig',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownx',
 'markdownify',
 'django_admin_shell',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q',
 'formtools',
 'allauth',
 'allauth.account',
 'allauth.socialaccount']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'error_report.middleware.ExceptionProcessor']



Traceback (most recent call last):
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/core/mail/message.py", line 82, in sanitize_address
    token, rest = parser.get_mailbox(addr)
  File "/usr/lib/python3.8/email/_header_value_parser.py", line 1791, in get_mailbox
    token, value = get_name_addr(value)
  File "/usr/lib/python3.8/email/_header_value_parser.py", line 1760, in get_name_addr
    if value[0] in CFWS_LEADER:

During handling of the above exception (string index out of range), another exception occurred:
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/allauth/account/views.py", line 102, in post
    response = self.form_valid(form)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/allauth/account/views.py", line 690, in form_valid
    form.save(self.request)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/allauth/account/forms.py", line 561, in save
    get_adapter(request).send_mail(
  File "/home/inventree/dev/env/lib/python3.8/site-packages/allauth/account/adapter.py", line 136, in send_mail
    msg.send()
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 121, in _send
    from_email = sanitize_address(email_message.from_email, encoding)
  File "/home/inventree/dev/env/lib/python3.8/site-packages/django/core/mail/message.py", line 84, in sanitize_address
    raise ValueError('Invalid address "%s"' % addr)

Exception Type: ValueError at /accounts/password/reset/
Exception Value: Invalid address ""
```

**Comment by SchrodingersGat** [comment]
And a similar error if I try to sign up a new account (with the "allow self sign up" option enabled):L

image

Looks like there is no catch for a missing email backend?

**Comment by matmair** [comment]
@SchrodingersGat I put in 2 levels of checks now. Should work without errors now.

**Pull request merged**
