### PR TITLE
[PUI] Add view of all defined units to Admin center

### LINKED ISSUE #7858: Is there a list of known units?
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

I was hoping to add "box" as a custom unit and got an error.
I think it's a custom unit but I can't add it.

### Steps to Reproduce

1. Go to Settings page
2. Go to Physical Units
3. Add a Unit
4. Name is `Box`, Definition is `box`
5. Definition got an error: `'box' is not defined in the unit registry`

### Expected behaviour

Successfully added this unit

### Deployment Method

- [ ] Docker
- [ ] Package
- [X] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.17.0 dev
Django Version: 4.2.14

Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Platform: Linux-6.1.0-23-amd64-x86_64-with-glibc2.36
Installer: None

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by matmair**
This PR:
- Adds an API endpoint to list all units (a lot of info, not very performant in API docs viewer due to rendering)
- Adds a list to the Admin Center

Closes #7858

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat ready for review and merge

**Comment by SchrodingersGat** [comment]
@matmair when I pull the code and run locally I get a 500 error:

image

**Comment by matmair** [comment]
@SchrodingersGat I have fixed the issue (the new version of pint has removed a function I was using) and added CI testing for the new API endpoint.

**Comment by SchrodingersGat** [comment]
Ok, is working now. 

Some further issues I can see:

### Pagination

Currently the table does not respect pagination - and delivers a *very very long table* with almost 1,000 entries

### Search

Along with pagination, it would be great to add search ability to narrow down results

**Comment by matmair** [comment]
I have turned both off, we can not guarantee stable responses from the API so implementing those could lead to flaky responses. I will adapt the url

**Comment by SchrodingersGat** [comment]
Ok, I suppose that this is low priority enough that this is OK. In that case, can you disable pagination on the PUI table? The pagination UI elements are still there even though they do nothing.

**Comment by matmair** [comment]
@SchrodingersGat I have changed the InvenTree table to display as follows with pagination disabled. Completely removing the footer seems not possible from docs/code.
grafik

**Pull request merged**
