### PR TITLE
Add setting to disable IPN editing after part is created (web only)

### PR DESCRIPTION
**Pull request by eeintech**
I wanted a way to prevent users to edit an auto-generated IPN number after part is created.

The title says "web only" because I think the API request should still be able to edit it.
That's because an automated API app may want to grab the part's primary key after creation and generate the IPN based on the PK (like in Ki-nTree :smile: ).

To keep the current behavior (IPN edit is allowed) I set this setting default to True (eg. Editing IPN is allowed).

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat Looks like Travis got disconnected?

**Comment by eeintech** [comment]
Looking good now!

**Comment by SchrodingersGat** [comment]
@eeintech I'm relatively happy with this, although I don't think I would use the feature personally. Can you please add a PR to the docs explaining this new feature?

**Comment by eeintech** [comment]
Added the PR https://github.com/inventree/inventree-docs/issues/82, I will get on the doc soon 👍

**Comment by eeintech** [comment]
For the doc, see https://github.com/inventree/inventree-docs/pull/83

**Comment by SchrodingersGat** [comment]
Thanks @eeintech

**Comment by eeintech** [comment]
No problem!

**Pull request merged**
