### PR TITLE
Refactor model helpers into own file

### PR DESCRIPTION
**Pull request by wolflu05**
This PR refactors all helpers that access models to its own file so we can directly use helpers at places where the models are not loaded yet (e.g. AppConfig => `apps.py`). 

Ref: https://github.com/inventree/InvenTree/pull/4824#discussion_r1209448718

<details open>
<summary>Error that would appear if we use helpers in AppConfig</summary>

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/apps/config.py", line 212, in create
    mod = import_module(mod_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/InvenTree/InvenTree/plugin/apps.py", line 13, in <module>
    from InvenTree.helpers_model import getSetting
  File "/workspaces/InvenTree/InvenTree/InvenTree/helpers_model.py", line 14, in <module>
    from djmoney.contrib.exchange.models import convert_money
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/djmoney/contrib/exchange/models.py", line 12, in <module>
    class ExchangeBackend(models.Model):
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/apps/registry.py", line 136, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

</details>

### CODE REVIEW

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
This is a nice refactor. Will be interesting to see if https://github.com/inventree/InvenTree/pull/4814 passes CI with these changes integrated in

**Comment by matmair** [comment]
@wolflu05 do you think you could also expand tests to have full coverage for the refactored code? Or should we put this into a new issue?

**Comment by wolflu05** [comment]
Sorry, tbh getting the tests cover 100% of the `helpers_model.py` looks not that easy. It contains the disabled test for the http status api that sometime failed. If you want to give it a go feel free to commit to my branch or make your own pr, but I don't think I can solve this easily.

**Comment by SchrodingersGat** [comment]
Thanks @wolflu05 for the improvements here :)

**Pull request merged**
