### PR TITLE
Add 'Tag' management

### LINKED ISSUE #83: 'Tag' management
Parts (or 'things' in general?) should have custom tags

### PR DESCRIPTION
**Pull request by matmair**
This PR adds tag, based on django-taggit, to several models:
- Part, SupplierPart, ManufacturerPart
- StockItem, StockLocation

Tags are also added to the (full) serializers for those models. They are not meant for frontend usage but to add taints/tags to parts for usage with plugins. That way objects can be marked and filtered for actions for eg.

Fixes #83

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair please address conflicts and I'll take a look :)

**Comment by SchrodingersGat** [comment]
@matmair trying to add new tags via the API throws an error:

image

In general I think we need some unit testing applied here:

- Test that tags show up in the API endpoints
- Test that tags can be adjusted via the API endpoints

**Comment by SchrodingersGat** [comment]
@matmair I'm going to bump this to the next release cycle, LMK if you have some time to work on this again

**Comment by matmair** [comment]
@SchrodingersGat I had to increase the query assertations by 1 (to 9 from 8) for part categories. Do you think that is ok?

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat I had to increase the query assertations by 1 (to 9 from 8) for part categories. Do you think that is ok?

As long as it's N(1) that's fine :)

**Comment by matmair** [comment]
That it is

**Comment by matmair** [comment]
@SchrodingersGat this should be ready

**Comment by matmair** [comment]
@SchrodingersGat have you seen this coveralls.io error before?

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat have you seen this coveralls.io error before?

Nope, it's breaking everything. Working on a [fix](https://github.com/inventree/InvenTree/pull/4735)

**Comment by matmair** [comment]
Ok except the known docs issues everything is on green now @SchrodingersGat

**Comment by SchrodingersGat** [comment]
Now that the docs are in the same repo, and we have [documented metadata](https://docs.inventree.org/en/latest/extend/plugins/metadata/) can you also add similar docs here for the tags feature? :)

**Comment by SchrodingersGat** [comment]
Additionally can we add API filters for tags?

Like `/api/part/?tag=banana`

**Comment by matmair** [comment]
Docs finished

**Comment by SchrodingersGat** [comment]
Cheers @matmair  :) 

Do you think it is possible to add in the API filtering also?

**Comment by matmair** [comment]
I will have to look into that

**Comment by matmair** [comment]
@SchrodingersGat your wish is my command

**Comment by SchrodingersGat** [comment]
Thanks @matmair this is a great new feature :)

**Pull request merged**
