### PR TITLE
Workflow remaster

### PR DESCRIPTION
**Pull request by matmair**
Fixes the skipping, maybe squash this @SchrodingersGat 

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2416"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Happy to squash and merge? :)

**Comment by SchrodingersGat** [comment]
Hmm still has the same outcome:

image

Maybe we should just put the version checks into their own action, (revert to how that file was previously) and then keep all the other ones in QC checks?

**Comment by matmair** [comment]
@SchrodingersGat I think it is time to cut our losses and do that. Also can we please switch to azure devops? I deploy with that system at work in I spend more time doing this pipeline than this whole year at work.

**Comment by SchrodingersGat** [comment]
I'd rather not change the CI pipeline again (moving from travis to github was already enough work). The current pipelines work well (even better now that you've refactored them!)

**Pull request merged**
