### PR TITLE
configurable ldap group classes

### PR DESCRIPTION
**Pull request by jacobfelknor**
Addresses https://github.com/inventree/InvenTree/issues/6101

Allow more granular LDAP group configuration. If no action is taken, this behaves as it did before due to defaults.

### CODE REVIEW

**Comment by wolflu05** [comment]
This should also address: https://github.com/inventree/InvenTree/discussions/8365#discussioncomment-11072737

**Comment by jacobfelknor** [comment]
Force pushed to amend commit author which was incorrect, my apologies

**Comment by matmair** [comment]
I do not have a non-prod setup with LDAPS right now, I would have to build something up in my lab so if Lukas has something I would let him test it.

**Comment by jacobfelknor** [comment]
For reference, these are the new setting values I used to make this work in my environment

```yaml
INVENTREE_LDAP_GROUP_OBJECT_CLASS: group
INVENTREE_LDAP_GROUP_TYPE_CLASS: NestedMemberDNGroupType
INVENTREE_LDAP_GROUP_TYPE_CLASS_ARGS: member
INVENTREE_LDAP_GROUP_TYPE_CLASS_KWARGS: '{"name_attr": "cn"}'
````

**Comment by wolflu05** [comment]
Sorry, I have currently also no testing setup and very limited time, so this will take me some time to get to it. I'd appreciate if someone of you could test this.

**Comment by SchrodingersGat** [comment]
@jacobfelknor can you confirm that the new settings are working for your setup?

**Comment by jacobfelknor** [comment]
Yes, I'm currently using these settings in my instance and it works with my environment

**Comment by SchrodingersGat** [comment]
Ok, can you please fix the style issues and I'm happy to merge. If there are any issues which arise you may get tagged :)

**Comment by jacobfelknor** [comment]
Okay, I think that should fix the styling

**Comment by SchrodingersGat** [comment]
@jacobfelknor thanks for the contribution :)

**Pull request merged**
