### PR TITLE
Bump pre commit versions

### PR DESCRIPTION
**Pull request by matmair**
This is mainly a maintenance chore with one important change: uv now supports including the `# via packagename` lines making dependabot diffsets much easier to read. To make the diff even smaller I have moved the config for uv to the pyproject.yaml file.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair looks like this is causing a CI failure on python `3.12`

**Comment by SchrodingersGat** [comment]
@dependabot rebase

**Comment by matmair** [comment]
I cant seem to get regex running - it seems like it could be https://github.com/mrabarnett/mrab-regex/issues/413 but not sure.

**Comment by matmair** [comment]
Interesting observation: something in the pipeline is not Python version agnostic although we pass versions through every I can think of

**Comment by SchrodingersGat** [comment]
@matmair I have a new PR here to hopefully fix the playwright issue - https://github.com/inventree/InvenTree/pull/7511

**Pull request merged**
