### PR TITLE
[WIP] Site ID Fixes

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR is a work in process to fix / simplify the site URL / multi-site support for InvenTree.

This fixes a few bugs and addresses some shortcomings of how the "site_url" parameter is configured.

Additionally, multi-site support is now disabled by default (a "breaking" change but most users would not use this feature at all). Disabling multi-site support makes a lot of things much simpler...

- Fixes https://github.com/inventree/InvenTree/issues/6133

### TODO

- [x] Add documentation around enabling multi-site support
- [x] Update SSO documentation (much simpler with multi-site support disabled)

### References

- https://github.com/inventree/InvenTree/issues/6133
- https://github.com/inventree/InvenTree/issues/5585

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat great improvement. Do you think adding site control to the admin view might be in-scope for this?

**Comment by SchrodingersGat** [comment]
> Do you think adding site control to the admin view might be in-scope for this?

Do you mean the PUI admin view? Site control is already available in the Django Admin view

**Comment by SchrodingersGat** [comment]
I do not see the value here - it would be a very small user set (if any) who are using multi-site support. There is still always the Django Admin site available if absolutely required to setup?

**Comment by matmair** [comment]
I think you are right, we can add it later

**Pull request merged**
