### PR TITLE
[PUI] Make actions recognisable

### PR DESCRIPTION
**Pull request by matmair**
Action Dropdowns are not very recognisable right now. Therefore, I propose adding indicators similar to the screenshots below to buttons with more than 1 action. I am not sure how to style that, below solution is not the final goal - maybe a single indicator could be enough for example.

Current
grafik

Proposed
grafik

Fixes https://github.com/invenhost/InvenTree/issues/98

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Maybe a "down caret" indicator would be clearer here? It seems a bit more "traditional". But I agree with the concept in general

**Comment by wolflu05** [comment]
I like the suggestion from @SchrodingersGat

**Comment by matmair** [comment]
What do we think about this: 
grafik

**Comment by SchrodingersGat** [comment]
That's pretty clean IMO

**Comment by wolflu05** [comment]
I think no its really hard to tell, which "down caret" belongs to what action, maybe an outline would help to add some separation, but not sure how that will look like.

**Comment by matmair** [comment]
It looks atrocious with an outline
grafik

**Comment by wolflu05** [comment]
That's true. Maybe its just me having problems to see the separation.

**Comment by SchrodingersGat** [comment]
What about a mantine indicator with the caret attached directly to the button

https://mantine.dev/core/indicator/

**Comment by matmair** [comment]
I have tried another thing: `light` 
grafik

**Comment by matmair** [comment]
I find vertical dots also match the flow better:
grafik

**Comment by matmair** [comment]
And the same thing in dark mode with dots instead of chevrons
grafik

**Comment by SchrodingersGat** [comment]
Light with chevrons is my pick :)

**Comment by matmair** [comment]
Ok then this is ready for merge - light with chevron is the current state of the PR.

> And maybe we add the chevron to the vertical dot menu too?

I would not add chevrons to the dot menu, I think that 3 dots are universally understood as "more" - that is why I suggested usage of them in the first place.

**Comment by SchrodingersGat** [comment]
> I would not add chevrons to the dot menu, I think that 3 dots are universally understood as "more" - that is why I suggested usage of them in the first place.

In this case, should we add a special dropdown menu just for the "more" actions - I see that you have added a lot of instances of `noindicator` - this could be refactored into a special dropdown with the *dots* icon and no indicator?

**Comment by matmair** [comment]
Sure, I can look into that.

**Comment by matmair** [comment]
@SchrodingersGat I have added a special dropdown to adress this

**Comment by matmair** [comment]
@SchrodingersGat this is ready for review and merge

**Comment by SchrodingersGat** [comment]
Nice work, thanks for this!

**Pull request merged**
