### PR TITLE
Model render refactor

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Removes duplicate model rendering code in the new react interface

### CODE REVIEW

**Comment by matmair** [comment]
To me it seems we lose functionality with this refactor. My renderers had the option to link to the object they were rendering while yours were just text/images. This greatly reduces the clicks needed to get to a specific object - I think that should be reintroduced.

**Comment by SchrodingersGat** [comment]
@matmair happy to add that in. But not happy for two ways to render a single model! If you think this has rescued functionality please make a PR :)

**Comment by matmair** [comment]
Yeah most of my WIP UI stuff seems to break after this, I will have to read the diff a bit deeper an reintroduce a few things

**Comment by wolflu05** [comment]
Yes, the api changes will also break my WIP things.

**Comment by matmair** [comment]
this removed so much of the interactivenes of renderes, I will revert this for my code base and work with the old variant for now to meet my deadlines

**Pull request merged**
