### PR TITLE
One workflow for PR checks

### PR DESCRIPTION
**Pull request by matmair**

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat base structure is done, will add some docs inline and try using caches to reduce build times overall

**Comment by matmair** [comment]
@SchrodingersGat ok caching etc. should be working now; could you check if the execution flow of the jobs is ok with you?

**Comment by SchrodingersGat** [comment]
Looking good! Will we need to change the test result badges in README.md?

**Comment by matmair** [comment]
@SchrodingersGat No, should be functionally the same.

**Comment by SchrodingersGat** [comment]
Sure thing. Are you happy for me to merge this in then?

**Comment by SchrodingersGat** [comment]
hmmm requires some further attention

https://github.com/inventree/InvenTree/actions/runs/1534131058

**Comment by SchrodingersGat** [comment]
This is very cool though:

image

**Comment by matmair** [comment]
> hmmm requires some further attention
> 
> https://github.com/inventree/InvenTree/actions/runs/1534131058

ok will take a look asap

**Comment by SchrodingersGat** [comment]
The "version number" check should *not* be run on a push (only a pull request):

image

**Pull request merged**
