### PR TITLE
[BUG] Confirmation Email uses local ip for link URL

### LINKED ISSUE #3827: [BUG] Confirmation Email uses local ip for link URL
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

When sending a verification email, it shows the local IP not the set base URL

Eg. mywebsite.com

Hello from InvenTree!

You're receiving this e-mail because user kyle has given your e-mail address to register an account on https://mywebsite.com

To confirm this is correct, go to http://192.168.1.111:83/accounts/confirm-email/MQ:1olnC0:UXQyFESkK7GxGnQOOEJcP8AXY1gkd-bbeIK02tDoxoo/

Thank you for using InvenTree!
https://mywebsite.com

### Steps to Reproduce

1. Set base URL
2. Add an email
3. Send a verification email

### Expected behavior

URL should respect the base URL setting

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.8.3
Django Version: 3.2.15
Commit Hash: f9d2b14
Commit Date: 2022-09-23
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by matmair**
Fixes #3827

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3829"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair probably hard to automate testing for this, but have you tested manually?

**Comment by matmair** [comment]
@SchrodingersGat yes, currently looking into testing. I am sure there is a way

**Comment by matmair** [comment]
Interesting side-fact: the template already uses the right URL in 2 places, just the login link is false.

**Comment by SchrodingersGat** [comment]
@matmair I'm going to merge this one in, if you get a chance to look at unit testing for this that'd be great :)

**Pull request merged**
