### PR TITLE
[PUI] Switch linting to biome

### PR DESCRIPTION
**Pull request by matmair**
Currently eslint and prettier are setup up (probably incorrectly as they do not seem to work) in pre-commt for PUI linting/formatting. This PR replaces both with biome, which is faster, does basically the same things, and seems to work.

It also adds auto fixes for various stuff like consistent quote styles or removing unused imports.

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat @wolflu05 thoughts on this? No idea why eslint is not working but this fixes it.

**Comment by SchrodingersGat** [comment]
Nice this looks great @matmair

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@wolflu05 any thoughts on this one?

**Comment by SchrodingersGat** [comment]
@matmair are you happy for me to merge this?

**Comment by wolflu05** [comment]
I have never used biome before, but it seems like a cool tool after a quick look. (it's also rust based, which promises speed). So sure we can try it out.

I would suggest adding some config for vscode to use biome as a formatter, so it works smoothly together with format on save.

**Comment by SchrodingersGat** [comment]
> I would suggest adding some config for vscode to use biome as a formatter, so it works smoothly together with format on save.

How would you suggest doing that?

**Comment by wolflu05** [comment]
Seems like they have a guide about it: https://biomejs.dev/reference/vscode/

**Comment by matmair** [comment]
I have added a extension accommodation and base settings

**Comment by wolflu05** [comment]
Thanks 👍

**Comment by matmair** [comment]
Thank you for your input @wolflu05  - it is valued as this whole frontend tech stuff is not really my forte.
@SchrodingersGat this is ready for review and merge from my side

**Comment by SchrodingersGat** [comment]
Awesome, great work as always @matmair

**Pull request merged**
