### PR TITLE
settings fixes

### PR DESCRIPTION
**Pull request by matmair**
Fixes two major problems that I found with the new settings.js if the database was migrated a lot:
- empty key fields are possible in the setting; fix: only include setting in allValues() that have a key
- old settings stay in the database; fix: a clean-up function

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Good catch. Let me know when it is ready

**Comment by sintech** [comment]
Please also add check for unescaped chars in string values. 
I had an apostrophe in site name which caused rendering issues.

**Comment by matmair** [comment]
@sintech will look into that. Normally all strings should be escaped by Django but maybe that's turned off somewhere

**Comment by matmair** [comment]
@sintech escaping was not considered in the code till now, I added it for settings via databases. Please check out if your case works now and report what makes errors if not.

**Comment by sintech** [comment]
@matmair, yes it works fine now. Apostrophe got HTML entity encoded in settings.js. 
`INVENTREE_INSTANCE: 'Sintech&#x27;s InvenTree server'`

**Pull request merged**
