### PR TITLE
Raise error if version fails

### LINKED ISSUE #3789: [Plugin] Raise error message if plugin fails version check
If a particular plugin fails version check during loading, it currently silently loads (but is inactive).

It would be helpful to add an error message to alert the user that the plugin has failed to load, due to a version incompatibility.

### PR DESCRIPTION
**Pull request by matmair**
Raise an error message if the plugin fails the version check.

Closes #3789

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3792"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat does this cover what you had in mind?

**Comment by SchrodingersGat** [comment]
@matmair I was actually thinking of a simpler display message here:

image

But I like your approach too! Perhaps it makes sense to have admin users notified on any plugin load crash?

**Comment by matmair** [comment]
@SchrodingersGat did not even think of the error stack, I only use that during development. Will add a message there too.

Doing admin notifications might be good too. At least in dev environments that might create a lot of messages - a bunch of sample plugins raise errors.

**Comment by matmair** [comment]
@SchrodingersGat aaaand I just remembered why there is a simple error stack: database calls while initialising plugins are problematic and also slow. I switched back to the simple message;

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Looks like CI needs some attention here

**Comment by SchrodingersGat** [comment]
@matmair ready to merge?

**Comment by matmair** [comment]
@SchrodingersGat yes

**Pull request merged**
