### PR TITLE
Add API Calendar for Return Orders

### PR DESCRIPTION
**Pull request by miggland**
Activate the calendar for return orders

### CODE REVIEW

**Review by SchrodingersGat — APPROVED** [review]

**Review by matmair — APPROVED** [review]
Clean change; would it make sense to make the event body customizable?

**Comment by matmair** [comment]
Regarding milestones. We normally push new features only to the new release, not the bugfix channel so that would be 0.12.0 right now

**Comment by miggland** [comment]
> Clean change; would it make sense to make the event body customizable?

I thought about that, but didn't figure out a simple enough way to do this.

> Regarding milestones. We normally push new features only to the new release, not the bugfix channel so that would be 0.12.0 right now

Fair enough. In this case, one could argue that it is a bug-fix, since the link was missing for the Return Order.. However, 0.12.0 is fine with me.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@miggland LGTM - ready for merge?

**Comment by miggland** [comment]
Yep, ready.

**Comment by SchrodingersGat** [comment]
Great :) thanks for the continuing contritbutions!

**Pull request merged**
