### PR TITLE
Bump weasyprint

### PR DESCRIPTION
**Pull request by matmair**
This removes the pin as the issue that caused the pin seems to be resolved in django-waesyprint.
Might also close https://github.com/inventree/InvenTree/issues/4936, pending confirmation by @miggland 

Closed https://github.com/inventree/InvenTree/issues/4936

### CODE REVIEW

**Comment by miggland** [comment]
This issue was blocking using an upgraded `django-weasyprint`: https://github.com/fdemmer/django-weasyprint/issues/71 . The fix was merged (https://github.com/fdemmer/django-weasyprint/pull/70), but not released?

Either way: if Weasyprint can be successfully upgraded, #4936 can be closed.

**Comment by matmair** [comment]
You are right @miggland, we will have to push this

**Comment by SchrodingersGat** [comment]
The fix in django-weasyprint has actually been merged, but the release was not pushed to GitHub:

https://pypi.org/project/django-weasyprint/

**Comment by miggland** [comment]
Well spotted @SchrodingersGat  -  but as of 13 hours ago, that's been corrected as well it seems!

**Comment by SchrodingersGat** [comment]
@miggland yes I reached out to the maintainer of the project :)

**Comment by SchrodingersGat** [comment]
It appears that the rendered PDF does not contain the exact same information. If you are able to test that the generated PDF files are still good, we can adjust the single failing test

**Comment by miggland** [comment]
I have tried out (again) with the dev branch: SVGs don't show up.
With this branch, they look correct! All of the PDFs I've created in my test setup look fine. I used the standard demo data and made a few different labels/reports (also on sheets, or concatenated reports). The only thing I changed was to add an example with the SVG.

So: this seems to fix #4936, and looks good otherwise.

The test: I guess a more robust test would be to try and open the PDF with some tool (eg PikePDF), eg:
`pdf = pikepdf.open(labelpath)`
which gives exception `pikepdf.PdfError` if there is something wrong with PDF:

Alternative: pdftotext:
```
with open(labelpath, "rb") as f:
    pdf = pdftotext.PDF(f)
    filetext = " ".join(pdf)  # Join for multiple pages
```
But that will only work if there is actually text in the PDF..
   
Of course, both require installation of extra packages..

**Comment by matmair** [comment]
I am not sure adding a dependency is great but I also can not find a better solution, pretty much on the same page as @miggland.

I did not work with pikepdf - which is smaller than what I tried. I will adapt this PR to add a test based on it.

**Comment by matmair** [comment]
@miggland I added a co-author credit for you as the change is basically what you suggested above

**Comment by matmair** [comment]
The order of objects seems flaky between DBMS, a fix will follow shortly.

**Comment by matmair** [comment]
@SchrodingersGat this would be ready for review

**Comment by SchrodingersGat** [comment]
Thanks @matmair

**Pull request merged**
