### PR TITLE
Clipboard UI

### PR DESCRIPTION
**Pull request by matmair**
Implements the functions for #997 and - as an example - copy-buttons in the part-detail view (/part/pk/).

If you want to add copy-functionality to any element just add `{% include "clip.html"%}` in the that elements text. This will include html-code that shows a button that copies the text-content of this element. The text is fetched at event-time so dynamic texts are no problem. The btton is light-grey till hvered and floats right.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Looks pretty good! Two small requests:

- Please add a mouse-over text (translated) to the effect of "copy to clipboard"
- When you hover over the button, the css padding changes and causes elements on the screen to shift around a bit

**Comment by SchrodingersGat** [comment]
May as well address this issue too - https://github.com/inventree/InvenTree/issues/725

**Comment by SchrodingersGat** [comment]
Thanks @matmair

**Comment by eeintech** [comment]
Nice stuff @matmair !

**Pull request merged**
