### PR TITLE
Update sponsors.yml

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Fix target branch

### CODE REVIEW

**Comment by wolflu05** [comment]
Why do we need this deployment to gh pages?

**Comment by SchrodingersGat** [comment]
> Why do we need this deployment to gh pages?

We don't I think I am doing it wrong. I just am trying to auto-update README.md with the sponsors :|

**Comment by wolflu05** [comment]
Then you need to use a commit action, to commit those changes to the main branch or open a pr like we do with crowdin

**Comment by SchrodingersGat** [comment]
Yep, you are right. I blindly followed their demo example 👎

**Pull request merged**
