### PR TITLE
Workflow remaster

### PR DESCRIPTION
**Pull request by matmair**
Only run version check if on pullrequest

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2415"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks for the fix @matmair we'll see if this works :)

**Comment by SchrodingersGat** [comment]
image

Looks like the subsequent tests are not being run, as the "version" check isn't running.

**Comment by matmair** [comment]
@SchrodingersGat I am still checking with merging into my master branch, pleas do not merge till i ping you

**Comment by SchrodingersGat** [comment]
Sorry, jumped the gun :)

**Comment by matmair** [comment]
@SchrodingersGat now it should work

**Pull request merged**
