### PR TITLE
Code style improvements

### PR DESCRIPTION
**Pull request by matmair**
This PR:
- adds a check for list comps (flake8-comprehensions)
- adds a check for common bugs (flake8-bugbear)
- adds a check for clean imports (flake8)

All these checks are run with pre-commit before git commit and with the CI

### CODE REVIEW

**Comment by matmair** [comment]
Adding more static checks is part of #4558

**Comment by matmair** [comment]
@SchrodingersGat this is ready once the checks run through

**Comment by SchrodingersGat** [comment]
@matmair sorry looks like there's a merge conflict. Please address this and I'm happy to merge :)

**Comment by matmair** [comment]
@SchrodingersGat  Merge conflict solved

**Pull request merged**
