### PR TITLE
[BUG] Unable to create build output

### LINKED ISSUE #2663: [BUG] Unable to create build output
**Describe the bug**
On a fully allocated Build Order, I'm unable to create a build output.

**Steps to Reproduce**

1. Create any new Build Order
2. Fully allocate the stock as normal
3. Under the "Pending Items" tab, click "New Build Output"
4. Populate the Quantity field, check "Confirm" then click Submit

**Expected behavior**
The Build Output would be created.

**Actual Behavior**
Blocker: The application presents "Form errors exist" and no further action can be taken (as the required fields are complete)
image

Further inspection of the network in DevTools, shows a post to /api/build/1/create-output/ with the response:
```json
{"auto_allocate":["This field may not be null."]}
```

**Deployment Method**
- Docker

**Version Information**
InvenTree-Version: 0.6.0
Django Version: 3.2.12
Commit Hash: 37bd573
Commit Date: 2022-02-21
Database: postgresql
Debug-Mode: False
Deployed using Docker: True

### PR DESCRIPTION
**Pull request by matmair**
Fix if no auto_allocate value is set
Fixes #2663

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2666"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Have you checked the behaviour when a null value is supplied?

I'd like to see a quick unit test here to check that an explicit "null" value (as opposed to a missing value) is handled correctly (and treated as false)

**Comment by SchrodingersGat** [comment]
@matmair I needed this fix for work, so merging it in now :)

**Comment by matmair** [comment]
> @matmair I needed this fix for work, so merging it in now :)

@SchrodingersGat I understand. Sorry for the delay, pretty slammed rn with work

**Comment by SchrodingersGat** [comment]
I know the feeling...

**Comment by matmair** [comment]
Not to complain, I freaking love what I do. I just would also love it  if it was less of it 😇

**Pull request merged**
