### PR TITLE
[P UI] Make base url configurable

### PR DESCRIPTION
**Pull request by matmair**
This PR makes the base URL (by default platform) configurable. This way the admin can select under which subpath P UI should be server (or if it should not use a subpath at all).

### CODE REVIEW

**Comment by lippoliv** [comment]
Does it also support Ports ("http://some-nas:1337")? Because 0.12.7 doesn't :/

**Comment by matmair** [comment]
Ports already work, our dev environments work that way.

PRs are not the right place to report problems if you want help though. That would be either discussions or issues.

**Comment by lippoliv** [comment]
Agreed. I'll collect information and report a bug. I just thought it's a full makeover so a bug would be obsolete. Thanks 🙏

**Comment by SchrodingersGat** [comment]
Seems like a straightforward change, thanks @matmair

**Comment by matmair** [comment]
@SchrodingersGat I am just splitting out all the side noice from #5559 so you can review that ;-)

**Pull request merged**
