### PR TITLE
Add config option to fully disable installing plugins

### LINKED ISSUE #6531: [FR] Add config option to fully disable installing plugins
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

System admins (with write access to ENV / config.yaml) currently can only disable plugins but not only installing plugins

### Suggested solution

Add an option to disable just installing - leaving admins the option to using nix or similar tools to amend the `plugins.txt` file.

### Describe alternatives you've considered

n.A.

### Examples of other systems

_No response_

### Do you want to develop this?

- [X] I want to develop this.

### PR DESCRIPTION
**Pull request by matmair**
This PR adds a file-level setting to disable plugin (un)installing via the REST/python API. This makes it much harder for (super) users without server access to manipulate the venv.

Closes #6531

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair I'd like to see the "install plugin" buttons disabled (in CUI and PUI) too...

**Comment by matmair** [comment]
@SchrodingersGat added the changes for PUI and CUI

**Review by SchrodingersGat — APPROVED** [review]

**Comment by matmair** [comment]
Conflict is resolved

**Comment by matmair** [comment]
I do not think this option is something 99% of deployments need but I will add a short bit about it.

**Pull request merged**
