### PR TITLE
Refactor fix formatting exclusion

### PR DESCRIPTION
**Pull request by matmair**
There was a mistaken config in the ruff settings that disabled ruff and auto-formatting in the build/ subdir

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair recent merge has introduced some conflicts, please address those!

**Comment by matmair** [comment]
@SchrodingersGat fixed

**Comment by SchrodingersGat** [comment]
@matmair sorry, the merge from https://github.com/inventree/InvenTree/pull/8738 has caused another conflict with the API version

**Comment by matmair** [comment]
@SchrodingersGat fixed now

**Pull request merged**
