### PR TITLE
Added first example to plugin unit test

### PR DESCRIPTION
**Pull request by SergeoLacruz**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@SergeoLacruz is this intended to replace https://github.com/inventree/InvenTree/pull/8616 ?

**Comment by SergeoLacruz** [comment]
This was meant to be an addition. But git adds all the unmerged commits.

**Comment by SchrodingersGat** [comment]
Ok, so I'll merge this one and close the other one.

@wolflu05 are you overall happy with this?

**Review by wolflu05 — APPROVED** [review]
LGTM for now

**Pull request merged**
