### PR TITLE
[PUI] Add permissions to groups

### PR DESCRIPTION
**Pull request by matmair**
This PR replaces the placeholder for group permissions with a row of accordions listing the permissions.
For this the PR:
- adds the `Group` model to various integrated rendering methods
- adds permissions and an admin button to the Group detail drawer
- adds permissions optionally to group serializers
- changes the creation of new groups to add no permissions by default (old default was view on everything)

## Screenshots
grafik

grafik

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat what is the current way to expose endpoint filters to the schema generator?

**Comment by SchrodingersGat** [comment]
> what is the current way to expose endpoint filters to the schema generator?

Sorry, what do you mean by "endpoint filters"?

**Comment by matmair** [comment]
@SchrodingersGat path parameters like `include_stock`?

**Comment by SchrodingersGat** [comment]
@matmair mostly they don't. There are a few "hidden" constructs in the API - which I am slowly working through and fixing. But, mostly the extra "detail" filters are handled manually and thus not exposed to the schema

**Comment by matmair** [comment]
Ok, so I do not need to expose them?

**Comment by SchrodingersGat** [comment]
> Ok, so I do not need to expose them?

No, no need to.

**Comment by matmair** [comment]
@SchrodingersGat @wolflu05 ready for review

**Comment by matmair** [comment]
@SchrodingersGat I have fixed the CI tests by adjusting to the changed defaults and adding the missing permissions to the test classes

**Comment by SchrodingersGat** [comment]
@matmair nice work, this is a good addition to the new interface.

**Pull request merged**
