### PR TITLE
Fix for SupplierPart API permissions

### PR DESCRIPTION
**Pull request by eeintech**
Missing `part_supplierpart` table permissions

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat Unfortunately this is was just a hacky fix...

`check_table_permission` method does not know how to fetch the `SupplierPart` permission because of the remaining link with the `part` app (in `SupplierPart` model `db_table = 'part_supplierpart'`) but in reality its permissions should be tied to the `company` app.

Do you have an idea how to fix this?

**Comment by SchrodingersGat** [comment]
@eeintech what exactly is the issue here? 

I see that the table name `company_supplierpart` is actually not valid, but what is the problem that you are fixing that led you here?

And is the `check_table_permission` function not performing correctly?

**Comment by eeintech** [comment]
@SchrodingersGat A user with edit `Part` and `Purchased Order` permissions (add/change) is not able to create a supplier item anymore... I think it has to do with #1363

**Comment by eeintech** [comment]
I have to admit this is quite an annoying issue as we are forced to use the Admin/superuser to create supplier items at the moment... Maybe I'll have some time tomorrow to do more debug but if you have any idea let me know @SchrodingersGat

**Comment by eeintech** [comment]
Was fixed by #1381

**Pull request closed without merging**
