### PR TITLE
Part responsible

### PR DESCRIPTION
**Pull request by miggland**
Fixes https://github.com/inventree/InvenTree/issues/5059

### CODE REVIEW

**Comment by miggland** [comment]
Good question, I didn't think about that.

I'll check and get back to you.

**Comment by SchrodingersGat** [comment]
I think this will need to be split into three separate migrations:

1. Add new field
2. Perform data migration
3. Delete old field

Additionally a unit test for the new data migration :)

**Comment by miggland** [comment]
Will be done (probably..)

**Comment by SchrodingersGat** [comment]
@miggland have you had a chance to look at the migration changes and unit tests for this?

**Comment by miggland** [comment]
I started, but got stuck with the migration and then other things came up..

If you know of migrations which do something similar that would be helpful, I'd have somewhere to start..

**Pull request closed without merging**
