### PR TITLE
[FR] Add tracing support

### LINKED ISSUE #6208: [FR] Add tracing support
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

It is hard to set up continous profiling / tracing without touching code. This makes usage of the official docker image unpractical in enterprise deployments.

### Suggested solution

Adding opentelemetry would aliviate this and is a vendor agnostic solution as it it a CNCF standard. The [adoption](https://opentelemetry.io/ecosystem/vendors/) is very wide reaching and consists of basically all popular APM plattform.

### Describe alternatives you've considered

Using sentry but running sentry on-prem can be a bit painful.

### Examples of other systems

_No response_

### Do you want to develop this?

- [X] I want to develop this.

### PR DESCRIPTION
**Pull request by matmair**
This PR adds OpenTelementry to support a host of APM services for tracing, logging and metrics collection.
Fixes #6208

### CODE REVIEW

**Comment by matmair** [comment]
I have tested this now with Elastic, New Relic, Grafana Cloud and Datadog and man, this format/standard is great. You can basically just switch metrics/tracing vendor by changing just endpoint and header

**Comment by SchrodingersGat** [comment]
@matmair looks pretty good to me - can you please add some information to the docs also?

**Comment by matmair** [comment]
@SchrodingersGat I added docs for the settings. Is this enough?

**Comment by SchrodingersGat** [comment]
Yeah, LGTM

**Comment by SchrodingersGat** [comment]
@matmair sorry I meant to loop back to this. Are you happy now to merge in? I'd like to discuss offline how we set this up for the demo instance

**Comment by matmair** [comment]
@SchrodingersGat yes, certainly!

**Pull request merged**
