### PR TITLE
Backport  Docs code links 

### PR DESCRIPTION
**Pull request by matmair**
This PR backports https://github.com/inventree/InvenTree/pull/7342 to 0.15.x as discussed in https://github.com/inventree/InvenTree/issues/7715#issuecomment-2248937221

It also adds detection of the current branch/commit to ensure the referenced files remain after the CI is run (branch references can shift)

### CODE REVIEW

**Comment by matmair** [comment]
I just saw that this defaults to master, I will have to include a fix for that.

**Comment by matmair** [comment]
@SchrodingersGat ready for merge! After this, I think we could release 0.15.7.

**Comment by matmair** [comment]
The change regarding stability of links is also here: https://github.com/inventree/InvenTree/pull/7745

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Cheers @matmair

**Pull request merged**
