### PR TITLE
Match fields

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Closes https://github.com/inventree/InvenTree/issues/2617

@eeintech please check this out, we now have a "generic" way of matching fields, using the API, which is much speedier.

The UI/UX is a bit different, but performs the same function. Let me know what you think.

### Screenshots

image

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2634"></a>

### TODO

- [ ] Fix BOM upload with empty cells (reported by @eeintech )
- [ ] Re-add option to "overwrite existing BOM"

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat Thanks for giving me the chance to review :+1: 

1. A BOM file with and empty cell will fail the field matching process.

Example file (D5 cell is empty):
image

Results in:
image

It does not happen if all cells are filled with data.

2. There used to be an option to overwrite the existing BOM, did you remove it intentionally?

image

This one is quite handy because it prevents getting this kind of error:
image

The only change I made in the BOM was changing this row from:
image

to:
image

All unchanged rows are generating this error I'm guessing so the overwrite would be really great for re-uploading BOM files.

3. I found a weird bug which maybe has nothing to do with the BOM import, upon deletion of all BOM items (which is currently necessary as mentioned in 2), the server is hitting an error 500:
image

Here is the traceback:

``` bash
Internal Server Error: /api/bom/49/
Traceback (most recent call last):
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.SerializationFailure: could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/rest_framework/generics.py", line 291, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
    return collector.delete()
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/models/deletion.py", line 429, in delete
    count = query.delete_batch(pk_list, self.using)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/models/sql/subqueries.py", line 43, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/models/sql/subqueries.py", line 23, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/francois/Desktop/github/InvenTree/env-inventree/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.
```

And even though I selected all items:
image

Some are not deleted after this operation:
image

After a second attempt, all items are deleted properly, I still hit this error... so it looks like it is easy to reproduce. It may have to do with the backend, maybe @matmair would understand it better?

**Comment by SchrodingersGat** [comment]
@eeintech not sure about the 500 error but I have addressed the other points. Please check again and let me know what you think.

**Comment by eeintech** [comment]
@SchrodingersGat Wow nice work and super quick fixes! I just did some more testing and everything looks good on my side. For the 500 error I will open a new issue as well as try to grab more information for debug. Thanks a lot! :beers:

**Review by eeintech — COMMENTED** [review]
Ready to merge!

**Pull request merged**
