### PR TITLE
Update LICENSE copyright year to 2024

### PR DESCRIPTION
**Pull request by dekhu48**

### CODE REVIEW

**Comment by matmair** [comment]
Updating the copyright year is completely meaningless in a legal sense. Because of that we stopped upping it

**Comment by SchrodingersGat** [comment]
@matmair would it be best to remove the dates entirely then?

**Comment by matmair** [comment]
@SchrodingersGat at the starting year can be interesting for disputes - I would just leave it as is

**Comment by dekhu48** [comment]
Closing PR

**Pull request closed without merging**
