### PR TITLE
Protected settings fix

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Closes https://github.com/inventree/InvenTree/issues/5227

### CODE REVIEW

**Comment by wolflu05** [comment]
Are you sure this covers every place where you can access settings? What is the expected behavior of get_setting?

**Comment by SchrodingersGat** [comment]
AFAIK the behaviour is to protect the setting from display in the interface / API, not prevent it from being accessed at all, right? Otherwise, how would it actually be used?

**Comment by SchrodingersGat** [comment]
@matmair any thoughts here? I have not ever used any protected settings in practice

**Comment by matmair** [comment]
One of the refactors in settings seems to have broken this. Maybe there should be a test for this.
The idea is to not let the values go out of the system - python code still needs to be able to access it though so this should work as intended.

**Comment by wolflu05** [comment]
> AFAIK the behaviour is to protect the setting from display in the interface / API, not prevent it from being accessed at all, right? Otherwise, how would it actually be used?

Oh yeah 🤦‍♂️ didn't thought about that. Makes totally sense, otherwise this feature isn't useful anyhow.

**Comment by SchrodingersGat** [comment]
> One of the refactors in settings seems to have broken this. Maybe there should be a test for this.

I'll add in a unit test

**Pull request merged**
