### PR TITLE
Pin django-stdimage to sub 6.0.0

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- 6.0.0 breaks model serialization for background worker task
- NFI why it does this

Ref: https://github.com/inventree/InvenTree/pull/3228

@matmair the recent update to requirements.txt boosted django-stdimage to [> 6.0.0](https://github.com/codingjoe/django-stdimage/releases) - which is a breaking change.

For some reason, this breaks model serialization (for django-q) for instances which do not have an image field (or have an empty image). This in turn causes task offloading to fail.

Very "lucky" to have a set of circumstances that conspired to even show this error up!

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3273"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair what do I need to do to get the pre-commit checks to work? I have updated the requirements.in file and the pre-commit checks work OK on my local PC..

**Comment by matmair** [comment]
@SchrodingersGat and the requirements.txt was not updated? Maybe run the dev setup command again - will provide a PR to fix this branch.
Any idea why our test did not catch this one?

**Comment by matmair** [comment]
@SchrodingersGat should be good to go

**Comment by SchrodingersGat** [comment]
> Any idea why our test did not catch this one?

Our existing unit tests did not ever test task offloading. I have added a very simple unit test, which I have confirmed breaks with `django-stdimage==6.0.0`

**Comment by matmair** [comment]
The more tests the better @SchrodingersGat 👍

**Pull request merged**
