### PR TITLE
fix link to MIT license

### PR DESCRIPTION
**Pull request by matmair**
Fixes the opensource.org link and ignores opensource.org as it seems to not wokr on CI

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat @wolflu05 this seems to work locally but not on CI - any idea why?

**Comment by SchrodingersGat** [comment]
The website may be rate limiting or blocking requests coming from github?

**Comment by matmair** [comment]
Seems like it, my tests in https://github.com/inventree/InvenTree/pull/8384 are failing because of this. Should we stop linting for this URL or wait a few days?

**Comment by SchrodingersGat** [comment]
Maybe we just stop linting this one?

**Comment by matmair** [comment]
@SchrodingersGat added an ignore

**Pull request merged**
