### PR TITLE
Add news reader

### PR DESCRIPTION
**Pull request by matmair**
This PR adds the possibility to show news that are represented on the new InvenTree website via RSS feed.
News items are only shown to staff users, a setting for it is included.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3445"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This is a very cool idea! Great to have this integrated with the new website :)

**Comment by matmair** [comment]
@SchrodingersGat anything you would like to be added here except tests?

**Comment by SchrodingersGat** [comment]
I don't think so, just some tests and confirmation of functionality once the new website is up.

**Comment by matmair** [comment]
@SchrodingersGat you can just replace the hard-coded path in the settings to check. If you want to see it rn.

**Comment by matmair** [comment]
@SchrodingersGat I resolved the merge conflicts, maybe we can include this in the 0.9.x release

**Comment by SchrodingersGat** [comment]
@matmair looks great :)

Once we "modernize" the home page, we can perhaps adjust how this looks but I like it!

**Pull request merged**
