### PR TITLE
[PUI] Lazy loading of global modals

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Slight improvement to initial loading time by lazy-loading some global modals

### CODE REVIEW

**Review by wolflu05 — APPROVED** [review]
Good idea, LGTM

**Review by matmair — APPROVED** [review]
LGTM; @wolflu05 do you think we could detect things like this in CI and highlight it?

**Comment by wolflu05** [comment]
Not sure how this would work. Maybe there is an eslint plugin, or the netlify analytics could detect that.

**Comment by SchrodingersGat** [comment]
I'm going to close this out for now - the gains are marginal and it is leading to a number of weird issues that are hard to debug. Not worth the effort currently.

**Pull request closed without merging**
