### PR TITLE
Feature: Supplier part pack size

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Adds the concept of "pack size" for the supplier part

- e.g. buy a single "bag" which contains 10 parts
- e.g. buy a single "tube" which contains 30mL vs a larger tube which contains 100mL

Closes https://github.com/inventree/InvenTree/issues/1435

### TODO

- [x] Add documentation for new feature - https://github.com/inventree/inventree-docs/issues/365
- [x] Add extra unit testing for 'on_order' quantity
- [x] Add unit testing for receiving items with pack_size != 1
- [x] Update demo dataset with supplier parts which have larger pack size - https://github.com/inventree/demo-dataset/pull/32
- [x] Update queryset annotation for `on_order` quantity (must include calculation of pack_size)
- [x] Update 'on_order' method for Part model
- [x] Update "on order" display for particular part page
- [x] Display pack size when adding lines to order via normal "Add Line Item" form
- [x] Display pack size when adding lines to order via "auto calculate" form
- [x] Ensure "units" are displayed appropriately for part quantity values in HTML views and forms

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3644"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@eeintech @matmair do you think that "pack_size" is the right nomenclature here?

**Review by matmair — APPROVED** [review]
Looks good. Am I right that the new field is only as a data point but without buisne3ss logic for splitting?

**Comment by matmair** [comment]
> @eeintech @matmair do you think that "pack_size" is the right nomenclature here? 

I think package_unit would be better.

**Comment by SchrodingersGat** [comment]
> Looks good. Am I right that the new field is only as a data point but without buisne3ss logic for splitting?

There will have to be some business logic added. Thinking about it, it becomes quite complex but should be attainable. For example, (and the use case I am trying to implement specifically for) say you have a part "thermal adhesive" which your units are "cc". You can buy it from one supplier in a tube of 30cc, and another in a tub of 500cc. The supplierpart quantity is "1" in each case, but the amount of "part" you are getting is markedly different.

So there needs to be logic in place to convert the incoming stock quantity from "supplier part units" to "part units". And then update every place where the "on order" quantity is reported to take this new pack quantity into account...

**Comment by matmair** [comment]
@SchrodingersGat sounds a lot like https://github.com/inventree/InvenTree/issues/1435

**Comment by derekwolfson** [comment]
This is nice -- can you add this as a context variable to reports?  Would be nice to show total quantity and total packs/sets on purchase orders.

**Comment by matmair** [comment]
@derekwolfson the PR is merged half a year. Please open new feature requests for new requests.

**Pull request merged**
