### PR TITLE
Don't ignore parts without stock in stocktake

### LINKED ISSUE #5621: Stocktake doesn't save parts with no stock
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Stocktake is ignoring active parts with 0 stock. (see https://github.com/inventree/InvenTree/blob/master/InvenTree/part/stocktake.py#L252-L254)

### Steps to Reproduce

1. Add a Part
2. Give it some Stock
3. Run stocktake
4. Sell all the Stock
5. Run stocktake again
6. In the Parts stocktake you'll see no new ("0") entry 

### Expected behaviour

If I have an active part and I run stocktake, I expect the Part to be noted down with "0 Stock at DateTime".

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.21
Commit Hash: 2b0d81f
Commit Date: 2023-09-25

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.0-82-generic-x86_64-with
Installer: DOC

Active plugins: False

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by lippoliv**
Fixes #5621

Currently in `Stocktake` (no matter if it's the export or update parts) we ignore `Part`s with 0 stock. This PR fixes that.

# Backport

I would love to see this being backported to 0.12.x, but it will not work automatically I guess. It's simliar lines, but in another file (https://github.com/inventree/InvenTree/blob/0.12.x/InvenTree/part/tasks.py#L317-L319).

### CODE REVIEW

**Comment by lippoliv** [comment]
I guess the CI fails for other reasons then my changes, right?

**Comment by SchrodingersGat** [comment]
@lippoliv looks like it - please merge in master once https://github.com/inventree/InvenTree/pull/5628 has been merged

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@lippoliv can you please merge in the changes from latest master so we can get this one merged?

**Comment by lippoliv** [comment]
@SchrodingersGat done

**Comment by SchrodingersGat** [comment]
Looks like some of the unit tests will have to be adjusted too :)

**Comment by lippoliv** [comment]
Missed that, try to fix it.  The VSCode integration is missing is that normal?

image

I can just execute the `tests` task, wait some time and then see the output of everything?

**Comment by SchrodingersGat** [comment]
@lippoliv what exactly are you running to get that error message?

You should be able to (from the command line in devcontainer) run something like:

```invoke test -r part.test_api``` (substitute `part.test_api` for whatever group of tests you need to run)

**Comment by lippoliv** [comment]
I set up VS Code as described in [devcontainers](https://docs.inventree.org/en/latest/develop/devcontainer/). Then I told it what python testing we use. I end up in the screenshot I showed before. In `Output > Python` I see

```log
Failed to import test module: users.test_migrations
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workspaces/InvenTree/InvenTree/users/test_migrations.py", line 5, in <module>
    from InvenTree import unit_test
  File "/workspaces/InvenTree/InvenTree/InvenTree/unit_test.py", line 11, in <module>
    from django.contrib.auth.models import Group, Permission
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/workspaces/InvenTree/dev/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 63, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

Is that a bug?


However I adapted your command line (thanks for the help) and ended up with `invoke test -r part.test_api.PartStocktakeTest.test_report_list` which I made pass and then step by step went "up" to see that everything works.

**Comment by SchrodingersGat** [comment]
LGTM, thanks for the contribution @lippoliv

**Pull request merged**
