### PR TITLE
List PO/SO/BO by reference in API

### LINKED ISSUE #3671: [FR] List PO/SO/BO by reference in API
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When accessing orders through the API, I always have to find the ID of the order first - ie list them, look for the reference I want, then get the ID.
If the API would accept a reference field, this would be reduced to one step, eg:
`https://demo.inventree.org/api/order/po/?reference=PO0006`

### Suggested solution

Compare to how Parts works: I can request an IPN directly using the URL:
`https://demo.inventree.org/api/part/?IPN=widget.blue`

### Describe alternatives you've considered

List -> search for reference -> return ID

### Examples of other systems

_No response_

### Do you want to develop this?

- [ ] I want to develop this.

### PR DESCRIPTION
**Pull request by miggland**
Fixes #3671:

Allows searching for a single PO/BO/SO in the API using a link such as:
```
https://demo.inventree.org/api/order/po/?reference=PO0006
https://demo.inventree.org/api/order/so/?reference=SO0001
https://demo.inventree.org/api/build/?reference=BO0001
```

Also adds a filter for customer to SO list:
```
https://demo.inventree.org/api/order/so/?customer=32
```

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4083"></a>

### CODE REVIEW

**Review by matmair — APPROVED** [review]
looks good

**Comment by SchrodingersGat** [comment]
@miggland looks great :) Can you please increment the API version also

**Comment by miggland** [comment]
Done!

**Comment by SchrodingersGat** [comment]
@miggland some conflicts from https://github.com/inventree/InvenTree/pull/4088/files - can you please address?

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @miggland

**Pull request merged**
