### PR TITLE
Money updates

### PR DESCRIPTION
**Pull request by matmair**
This PR implements everything needed to solve #1714:
- a new Field `InvenTreeModelMoneyField` - replaces `djmoney.models.MoneyField`; overrides default values for currency and choices to always be clean in migrations, also uses following field on render
- a new Field `InvenTreeMoneyField` - replaces `djmoney.forms.MoneyField`; re-enables usage of currency-settings
- adds in a database setting for default currency and a setting-switch in 'currencies'
- removes duplicate code regarding defaulft_currency_code for fields

Missing:
- [x] migration to get legacy settings into database

### CODE REVIEW

**Comment by matmair** [comment]
This is needed to fix #1674 and came up a lot during #1730

**Comment by SchrodingersGat** [comment]
@matmair looks good, I'm glad to see that the default currency can now be changed at run time. I'll pull this down tonight and have a look.

**Comment by matmair** [comment]
> @matmair looks good, I'm glad to see that the default currency can now be changed at run time. I'll pull this down tonight and have a look.

@SchrodingersGat still very WIP, probably a waste of your time rn

**Comment by SchrodingersGat** [comment]
Sure, let me know when you're happy with it then :)

**Comment by matmair** [comment]
@SchrodingersGat this should work now. Would be happy for you to take a look

**Comment by SchrodingersGat** [comment]
Nice work, seems to function as expected!

**Comment by matmair** [comment]
> 
> 
> Nice work, seems to function as expected!

Thanks @SchrodingersGat should be ok to be merged now. I just needed to add a migration and test a few cases to be sure it really works.

**Comment by matmair** [comment]
Closes #1714
Fixes #1674

**Comment by eeintech** [comment]
Nice work @matmair !

**Pull request merged**
