### PR TITLE
Add more tests for offload_task

### LINKED ISSUE #3005: Testing - Add unit test for background worker processes
https://github.com/inventree/InvenTree/pull/3004 has revealed a weakness in the unit testing processes.

We currently have no tests for functions that rely on the background worker. This has allowed a critical bug to creep into the code in the recent plugin refactor.

### PR DESCRIPTION
**Pull request by matmair**
This PR enables offload_task to use function references and adds more tests.
Closes #3005

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3014"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat this is ready after the current tests run through. All tests in /InvenTree/InvenTree are covered now - including the offloading task.
I strongly suggest to use direct function references for offloaded tasks - this will prevent them from breaking in refactors.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Nice work @matmair - moving away from calling functions based on the string name is a great step.

There are still some naked calls to `offload_task` being handled here: https://github.com/inventree/InvenTree/blob/master/InvenTree/plugin/base/event/events.py

In addition to converting these, I think it would be useful to add some unit tests to ensure that the *events* are correctly offloaded.

e.g. create a new Part instance, check that the event was registered to a plugin?

**Comment by matmair** [comment]
@SchrodingersGat there are multiple plugins that were introduced with no coverage (see #2992). My suggestion is to tackle those separately as there are more unit and e2e things missing there.
This PR is more focuses on unit and e2e tests for general tasks.

**Comment by SchrodingersGat** [comment]
Fair enough, happy to tackle plugin coverage as a separate PR. Will merge this one in once checks have passed

**Pull request merged**
