### PR TITLE
further translation de

### PR DESCRIPTION
**Pull request by mosenturm**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @mosenturm looks like there are some conflicts here with the translation files - please fix so I can review :)

**Comment by mosenturm** [comment]
Hi, @SchrodingersGat I have resolved the merge conflicts. Pls. review. Thanks!

**Comment by SchrodingersGat** [comment]
Thanks for adding the extra translated strings in the templates! Please fix the one error as above and I'll merge :)

**Comment by mosenturm** [comment]
Hi @SchrodingersGat I've fixed the typo.

**Pull request merged**
