### PR TITLE
SalesOrder Data Migration

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Adds data migration to update the missing "shipment date" of sales order 
- Ref: https://github.com/inventree/InvenTree/pull/8580
- Only applies to `0.17.0`

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair a bit of a strange one here. I am adding some data migration tests, and coming across a strange error related to the new custom status codes:

From https://github.com/inventree/InvenTree/actions/runs/12076386849/job/33677691064?pr=8585

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django_test_migrations/contrib/unittest_case.py", line 40, in setUp
    self.prepare()
  File "/home/runner/work/InvenTree/InvenTree/src/backend/InvenTree/order/test_migrations.py", line 243, in prepare
    order = SalesOrder.objects.create(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column "status_custom_key" specified more than once
LINE 1: ...der_currency", "address_id", "status_custom_key", "status_cu...
```

Any thoughts on this one? I have not been able to track it down. But it is adding the `status_custom_key` field to the model multiple times, for some reason?

**Comment by matmair** [comment]
@SchrodingersGat that seems to be very low level in the ORM, that will need need some time to debug; will try to ding into it over the weekend

**Comment by matmair** [comment]
No idea what is causing this; is this also reproducible with normal migrations?

**Comment by SchrodingersGat** [comment]
This is the first (and only) time I have seen this

**Pull request merged**
