### PR TITLE
Add new readme

### PR DESCRIPTION
**Pull request by matmair**
This PR modifies the Readme to be information-denser while also being pretty 🌟 

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2917"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat three open questions:
- do you want to have a screenshot in the readme
- leave in the roadmap section
- are there any acknowledgements we should add/remove?

**Comment by SchrodingersGat** [comment]
Thanks @matmair this is definitely needed - the "landing page" has been in dire need of a refresh 👍 

> * do you want to have a screenshot in the readme

I'm not sure if one screenshot can really capture everything the project is about, but I'd be happy to put one in if you can suggest something.

> * leave in the roadmap section

Either here in the readme, or on the website / doc site. Here for now is good, but once we have the website up and running I'd like to only have to maintain the roadmap in a single location

> * are there any acknowledgements we should add/remove?

I'm happy with what you have for now

**Comment by matmair** [comment]
@SchrodingersGat this is ready for review and merge!

**Comment by SchrodingersGat** [comment]
Fantastic work :)

**Comment by eeintech** [comment]
Great job @matmair, looks neat!

**Pull request merged**
