### PR TITLE
Task restructure

### PR DESCRIPTION
**Pull request by matmair**
Follow up to #3175

Heavily breaking - renames nearly all tasks and puts them into groups.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3177"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair not sure I see the benefit here. This breaks a lot of existing workflows (in this and other repos, e.g. python bindings / app / etc) and also will require serious overhaul of the documentation. Is the current task structure missing any functionality that this change brings?

**Comment by matmair** [comment]
@SchrodingersGat the idea is to restructure the commands in logical groups so it is better maintainable if/when it grows. The grouping into multiple namespaces also makes it easier for users to extend the commandset for custom deployments.
If this is is to heavy handed I would like to provide a leaner PR that removes the style command.

**Comment by SchrodingersGat** [comment]
> If this is is to heavy handed I would like to provide a leaner PR that removes the style command.

I think this would be a better idea for now. I'd rather not make the other changes

**Comment by matmair** [comment]
@SchrodingersGat I will create something new soon.

**Pull request closed without merging**
