### PR TITLE
Add custom InvenTreeDateFilter class

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Fixes issues with naive datetimei object
- Suppress warning
- Closes https://github.com/inventree/InvenTree/issues/5223

### CODE REVIEW

**Comment by LavissaWoW** [comment]
LGTM

The resulting TZ info will be based on the server's TZ, I presume. But if the value didn't arrive TZ-aware, I think that's a fair tradeoff.

**Comment by wolflu05** [comment]
Seems like this introduced an error into the code. The demo server shows 230+ [errors](https://demo.inventree.org/inv-admin/error_report/error/2/change/).
```

Traceback (most recent call last):

File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)

File "/home/inventree/InvenTree/InvenTree/api.py", line 306, in get
return super().get(request, *args, **kwargs)

File "/usr/local/lib/python3.10/site-packages/rest_framework/generics.py", line 239, in get
return self.list(request, *args, **kwargs)

File "/home/inventree/InvenTree/part/api.py", line 1050, in list
queryset = self.filter_queryset(self.get_queryset())

File "/home/inventree/InvenTree/part/api.py", line 1076, in filter_queryset
queryset = super().filter_queryset(queryset)

File "/usr/local/lib/python3.10/site-packages/rest_framework/generics.py", line 150, in filter_queryset
queryset = backend().filter_queryset(self.request, queryset, self)

File "/usr/local/lib/python3.10/site-packages/django_filters/rest_framework/backends.py", line 74, in filter_queryset
return filterset.qs

File "/usr/local/lib/python3.10/site-packages/django_filters/filterset.py", line 230, in qs
qs = self.filter_queryset(qs)

File "/usr/local/lib/python3.10/site-packages/django_filters/filterset.py", line 213, in filter_queryset
queryset = self.filters[name].filter(queryset, value)

File "/home/inventree/InvenTree/InvenTree/filters.py", line 24, in filter
if value is not None and not timezone.is_aware(value):

File "/usr/local/lib/python3.10/site-packages/django/utils/timezone.py", line 220, in is_aware
return value.utcoffset() is not None

AttributeError: 'datetime.date' object has no attribute 'utcoffset'
```

**Comment by SchrodingersGat** [comment]
@wolflu05 thanks, clearly did not test this well enough.

**Comment by LavissaWoW** [comment]
@SchrodingersGat The original warning is very present on the Dashboard page, aka."index.html" due to the amount of naive timestamps being passed to the backend. I'd focus my testing there, as every reload of that page sends several 30-day timestamps to the API.

**Pull request merged**
