### PR TITLE
Docker CI Updates

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Also, build docker image on PR if any docker-related files have changed

Ref: https://github.com/inventree/InvenTree/pull/5889

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair I got the docker image to at least build, by updating the base package requirements for the image itself. But now the unit tests are failing. Do you have any issues with plugin installation, running `3.11`?

**Comment by matmair** [comment]
@SchrodingersGat I use wheels for my installs and had no problems, I will look into this one (which we build).

**Comment by matmair** [comment]
This is an interesting problem, I still ger an error with an updated `minimum` every 5-10 times. Will need to investigate - maybe we push this to `0.14.0`?

**Comment by SchrodingersGat** [comment]
@matmair yes let's push the update - however I'll revert the python version and merge this in. The CI workflow updates are useful by themselves

**Pull request merged**
