### PR TITLE
possible fix for #1628

### LINKED ISSUE #1628: [BUG] Bootstrap pagination: NaN to NaN of undefined rows
To reproduce:

1. Navigate to a part list under a category
2. Select "All" for the number of items displayed
3. Refresh the page, it will show as:

image

### PR DESCRIPTION
**Pull request by matmair**
Fixes #1628

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks @matmair - I'm on vacation for a few days so I'll have a look as soon as I get back home

**Comment by matmair** [comment]
@SchrodingersGat great, enoy your time off! Will do some bigger stuff then till you are back.

**Comment by eeintech** [comment]
I just tried that fix but does not work on Chrome... You guys are using Firefox right?

**Comment by matmair** [comment]
@eeintech I can confirm that the bug seems to still persist in chrome but I failed so far to find what is causing it. Will investigate in the weekend.

**Comment by SchrodingersGat** [comment]
@matmair are you going to continue with this one in a new PR?

**Comment by matmair** [comment]
I have no idea what is causing it and a half working solution is kind of bad so I closed that.

**Comment by eeintech** [comment]
@matmair Don't mind me using another browser, if it solves it for part of InvenTree users, probably worth it!

**Comment by matmair** [comment]
@eeintech you represent 64% of the worlds browser users while we do under 4%
grafik
So this fix would mostly be of cosmetic nature.

**Comment by eeintech** [comment]
4% better than 0%? It does not hurt is what I mean :) No worries any way

**Pull request closed without merging**
