### PR TITLE
[PUI] form error fix

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Fixes bug introduced in https://github.com/inventree/InvenTree/pull/7678
- Reduce duplicate API queries when loading a form
- Add unit testing via playwright

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@wolffam please LMK if you spot any issues now :)

**Comment by matmair** [comment]
@SchrodingersGat did you mean to tag Lukas? Because that is not him

**Review by wolflu05 — COMMENTED** [review]
Thanks for that quick fix, that indeed fixes the error with the not showing errors, but I now found out, that that your initial changes have also broken the edit forms (see video), which is not fixed by this fix.

https://github.com/user-attachments/assets/3560d221-adc2-4fb1-adaf-91bf1df3067b

**Comment by SchrodingersGat** [comment]
@wolflu05 thanks, I think I have fixed this now and added some more end-to-end tests to cover it.

**Pull request merged**
