### PR TITLE
Add additional test fields

### PR DESCRIPTION
**Pull request by martonmiklos**
As we discussed in the #5995 I would like to add the following extra fields to the test results:
- test station name
- test start/finish time (to handle use cases where the test execution is asynchronous from the  logging)
- retest (for improving the performance of the statistics creation)

I have an another branch where I built some statistics UI on the top of this:
kép

Once we iron out this I will PR those changes as well.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
In general I am happy with these additions, except for the "retest" field. I think that this could be easily calculated dynamically by counting the number of test results (for a single stock item) which have the same test key...

**Comment by martonmiklos** [comment]
> In general I am happy with these additions, except for the "retest" field. I think that this could be easily calculated dynamically by counting the number of test results (for a single stock item) which have the same test key...

My intention with the retest "caching" is the fact that we are mainly interested in the retesting percentage per part/test type/build order. In these queries we could have a plenty of test results: sometimes we manufacture 1K Build orders atm. I have 270K serial numbers imported in InvenTree.

**Comment by martonmiklos** [comment]
> In general I am happy with these additions,

One more question came into my mind the (old) UI:
The new test station, test started/finished date columns are hidden by default:

kép

I would rather sort the results by the Test finished date (which is identical if no other date passed) and would rename the "Test date" to "Result save date" or something similar. This would always allow the test execution process to be overviewed in the "natural flow" regardless if the test results were uploaded asynchronously or mixed orders.

The test "Start date" and the "Result save date" columns could be hidden by default to spare "screen estate".

**Comment by martonmiklos** [comment]
> In general I am happy with these additions, except for the "retest" field. I think that this could be easily calculated dynamically by counting the number of test results (for a single stock item) which have the same test key...

@SchrodingersGat 
May I ask you reflect my comments above? I would like to push this through even without the retest field if you really against that.

**Comment by SchrodingersGat** [comment]
@martonmiklos I would like to see this move forward too. After another chance to look at it:

### Timestamping

We already have the `date` field (which records the datetime timestamp when the test was recorded). Is this sufficient for recording the "test end time"? Otherwise we are potentially duplicating this data. Would like to hear your thoughts on this.

### Retest Field

Would you be opposed to a dynamic calculation which calculates percentage of failed tests on the fly? I'm still not 100% sure on your proposed usage for this field

**Comment by martonmiklos** [comment]
> @martonmiklos I would like to see this move forward too. After another chance to look at it:
> ### Timestamping
> 
> We already have the `date` field (which records the datetime timestamp when the test was recorded). Is this sufficient for recording the "test end time"? Otherwise we are potentially duplicating this data. Would like to hear your thoughts on this.

The date field currently holds the date when the test was uploaded to InvenTree, which is not necessary the same as the execution start date. (In the case if the test result uploading is done asynchronously.) Storing the end date might also help making statistics (i.e. some operators performing testing way slower than others etc.)

> ### Retest Field
> 
> Would you be opposed to a dynamic calculation which calculates percentage of failed tests on the fly? I'm still not 100% sure on your proposed usage for this field

You are right, I will remove the field and do the calculations on the fly.

**Comment by SchrodingersGat** [comment]
@martonmiklos ok, happy if you keep the new date fields, and remove the "retest" field. Please address conflicts in the current PR.

Can you also update the new testresulttable in the react interface?

https://github.com/inventree/InvenTree/blob/master/src/frontend/src/tables/stock/StockItemTestResultTable.tsx

**Comment by martonmiklos** [comment]
> @martonmiklos ok, happy if you keep the new date fields, and remove the "retest" field. Please address conflicts in the current PR.
> 
> Can you also update the new testresulttable in the react interface?
> 
> https://github.com/inventree/InvenTree/blob/master/src/frontend/src/tables/stock/StockItemTestResultTable.tsx

@SchrodingersGat 

I managed to rebase to master. I originally planned to add the UI changes in a separate PR (of course I will update the new UI too). What do you think?

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@martonmiklos thanks for the contribution! Please submit a separate PR to add these new fields to the test result table in the react interface!

**Comment by martonmiklos** [comment]
> @martonmiklos thanks for the contribution! Please submit a separate PR to add these new fields to the test result table in the react interface!

Thank you for your patience and the merging!

**Pull request merged**
