### PR TITLE
Fixed the app/app link to point to the latest app version. #7193 

### PR DESCRIPTION
**Pull request by Petrox**
This is a oneliner HREF change

Closes https://github.com/inventree/InvenTree/issues/7193

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@Petrox thanks for the fix.

FYI the underlying issue was that the `0.14.5` docs build was not live - I have now fixed that.

However I agree that the "app" docs link should always point to stable as that is not pinned to a particular server version.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by Petrox** [comment]
> However I agree that the "app" docs link should always point to stable as that is not pinned to a particular server version.
Note: since there were multiple links pointing to **LATEST/app/app** I used that instead of the stable I mentioned first.

**Comment by matmair** [comment]
@SchrodingersGat you sure this makes sense? Linking to `latest` means any change to the docs structure in the future will break any number of deployed versions of InvenTree. Docs and core code are in the same repo so the potential for them to drift apart is far less likely when being referenced stably compared to pointing to the very latest version of docs.

**Comment by SchrodingersGat** [comment]
@matmair on second thoughts I think you are right - if (for whatever reason) we change the docs structure then this will break things. 

@Petrox note that I have addressed the upstream issue (in the documentation host), so I will revert this fix.

**Comment by Petrox** [comment]
No problems.

Btw linking to stable of the app is technically more accurate than linking
to the specific version. Since the mobile app is up to date or one version
behind the stable latest published version, while the inventree instances
are usually not updated every weekend. (I would guess)

And just fyi the codebase has links to the latest/app/app already (and
still).

May I help clean those up?

**Comment by SchrodingersGat** [comment]
> And just fyi the codebase has links to the latest/app/app already (and
still).

Can you link me to where those are?

I have been investigating another solution - adding static redirects on the documentation server for topics which are not linked to a particular "version" of InvenTree backend:

e.g.

- https://docs.inventree.org/app
- https://docs.inventree.org/python

These redirect to the "stable" docs at the appropriate page - and can be adjusted at any time if we move the page locations.

This way the docs links in the code can be kept static (for these items). Thoughts?

**Pull request merged**
