### PR TITLE
Add code128 template

### PR DESCRIPTION
**Pull request by matmair**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
It'd be a good idea to add a unit test which renders this template, just to check it renders without error

**Comment by SchrodingersGat** [comment]
Should we rename the barcode directory, or place it within a subdirectory of InvenTree? What other options do we have for resolving namespace issues?

**Comment by matmair** [comment]
@SchrodingersGat I moved the barcode stuff all into the plugin app. A bit of refactoring needs to be done but it should be better this way.

**Comment by matmair** [comment]
@SchrodingersGat could you review this and manually trigger postgres / mysql tests?

**Comment by SchrodingersGat** [comment]
I can't manually trigger those until it's merged, but looks good, thanks for the quick fix

**Pull request merged**
