### PR TITLE
Print multi part label

### PR DESCRIPTION
**Pull request by Guusggg**
Hi,

I recently had the need to print a lot of Part Labels and I notice this didn't exist yet in the 0.4.5 release.
I was browsing through the code and saw that the functionality was there, it just didn't have a button allocated to it yet, so I did just that.

Do note: I have checked out the commit history on the original project and didn't find a commit where this was added yet. If it is, please reject this request and I will update our current version (0.4.5) to the master repository.

Excuse me for the messy commit history, I'm maintaining our own version of Inventree in-house with some custom functionality that I don't want to implement in the original project because it is highly dependent on how we use this software. I will improve this in the future, as to have more direct commits so it's easier to merge this.

Kind regards,

### CODE REVIEW

**Comment by eeintech** [comment]
Works for me :+1: 

Probably a "merge squash" would be nicer :smiley:

**Comment by Guusggg** [comment]
@eeintech Thanks a lot for the tip! Do you know if I can still do it after the fact?

**Comment by eeintech** [comment]
@Guusggg Oliver can do it while merging :wink:

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @Guusggg - a great first time effort!

**Pull request merged**
