### PR TITLE
[PUI] Add image based QR code assigment

### PR DESCRIPTION
**Pull request by matmair**
Follow up to https://github.com/inventree/InvenTree/pull/7939

This adds a button to scan codes for barcode linking.
I am not sure about the styling and would be thankful for feedback.

New look for barcode linking
grafik

Current look for general QR scans:
grafik

### CODE REVIEW

**Comment by wolflu05** [comment]
This already looks pretty good. I like that there is a select to use a different camera (this is pretty useful in safari to use the iPhone camera as a scanner).

I have to suggestions to improve the design.
1. make the stop button as high as the input field (I think there is an extra size type for the action button in mantine for this
2. make the input at the bottom full width and add the icon to the inputs left section.

Maybe this component can be also used later for the related model field to just input barcode data there.

**Comment by matmair** [comment]
I have adapted it to this: 
grafik
Should we use this setup for all scanning purposes?

**Comment by matmair** [comment]
Ready for review and merge if @wolflu05 is happy

**Comment by SchrodingersGat** [comment]
@matmair looks good to me!

**Review by wolflu05 — APPROVED** [review]
Thanks for the design adjustments. It looks great now.

**Pull request merged**
