### PR TITLE
[CI] Enable python autoformat

### PR DESCRIPTION
**Pull request by matmair**
Follow up to https://github.com/inventree/InvenTree/pull/6167. Enables auto-formatting of python files with pre-commit.

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat I think this would be an improvement - what do you think?

**Comment by matmair** [comment]
Ready for review; adds autformating for python with ruff (similar to black - just a lot faster)

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Please address conflicting files and I am happy to merge

**Comment by matmair** [comment]
@SchrodingersGat the code base is moving faaaaaast right now ;-)

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat the code base is moving faaaaaast right now ;-)

Well, you have touched 13K lines of code 👍

**Pull request merged**
