### PR TITLE
Unit Test Improvements

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Select when migration tests are performed
- Compare how long the unit tests take

Closes https://github.com/inventree/InvenTree/issues/4821

Not running the migration tests shaves 10 minutes (25%) off the unit testing

### CODE REVIEW

**Review by matmair — APPROVED** [review]

**Comment by matmair** [comment]
@SchrodingersGat has slowtests a sizeable impact?

**Comment by SchrodingersGat** [comment]
@matmair in summary:

- Migration unit tests are broken out into a separate CI step, allowing them to run in parallel
- Migration unit tests only run when migrations are touched
- Migration unit tests take ~20 minutes by themselves
- Other unit tests have been reduced to ~20 minutes also

Overall this is a 50% reduction in unit testing time - further improvements can still be made but I suspect with diminishing returns.

**Comment by matmair** [comment]
Looks great @SchrodingersGat ! Is there any inherent reason to spilt out the migration tests into a separate file? The job could also be run parallel as a separate job in the main qc.yaml IIRC.

**Comment by SchrodingersGat** [comment]
No inherent reason, I just thought it made sense to keep them distinct. The ci checks file is getting very difficult to understand

**Comment by matmair** [comment]
Would you be open to merging the files? Having one QC file makes monitoring and automation easier downstream.

**Comment by SchrodingersGat** [comment]
I'm not opposed to it :) if you submit a PR I'll merge!

**Pull request merged**
