### PR TITLE
Purchase Order File Upload Update

### LINKED ISSUE #1826: Purchase Order import
- When I click "Purchase Order" -> "Upload File", left menu disappears.
- Can't upload file with non-ascii filename. `'ascii' codec can't encode character '\u0430' in position 62: ordinal not in range(128)`
- Field names selector width is limited by table column width. PO_import1
- On the second step wizard uses not my default currency but first in the list (Australian dollars)
- Decimal separator (comma) has been removed 
PO_import2

Anyway, great tool for table import.
FYI: I'm using latest pull from master.

### PR DESCRIPTION
**Pull request by eeintech**
Fixes #1826

### CODE REVIEW

**Comment by eeintech** [comment]
@matmair Any chance you can review this PR?

**Comment by matmair** [comment]
> 
> 
> @matmair Any chance you can review this PR?

@eeintech will do gladly, thank you for asking 👍

**Comment by matmair** [comment]
@eeintech seems to work fine

**Review by matmair — APPROVED** [review]

**Comment by eeintech** [comment]
Thanks for taking a look @matmair !

**Pull request merged**
