### PR TITLE
Possible fix for git messages

### PR DESCRIPTION
**Pull request by matmair**
This PR might fix https://github.com/inventree/InvenTree/issues/4428

### CODE REVIEW

**Comment by wolflu05** [comment]
Do you think this line is also responsible for these messages? 

https://github.com/inventree/InvenTree/blob/86b72549a2cc68a9262e7710e3dfd3e726906ac8/InvenTree/plugin/helpers.py#L119

**Comment by matmair** [comment]
@wolflu05 to a part - yes. Another big source was the lookup for commit number and date.

**Comment by matmair** [comment]
Strangely enough, the tests no longer throw the error - bare metal still does. @SchrodingersGat this def makes things better. Let's merge this in and I will submit another PR once I have determined the rest comes from.

**Comment by wolflu05** [comment]
> @wolflu05 to a part - yes. Another big source was the lookup for commit number and date.

So you won't add your check also to this usage of git?

**Comment by matmair** [comment]
> > @wolflu05 to a part - yes. Another big source was the lookup for commit number and date.
> 
> So you won't add your check also to this usage of git in this PR?

No, it broke in some tests with the check added. I need a better one for the packages.

**Comment by SchrodingersGat** [comment]
Very clever fix @matmair :)

**Comment by matmair** [comment]
Not really TBH but thanks

**Pull request merged**
