### PR TITLE
Internal price

### PR DESCRIPTION
**Pull request by matmair**
Adds internal prices (for usage in assembly pricing etc) and all needed views, tools etc. As in #1606.

At the moment missing:

- [x] tests
- [x] documentation
- [x] ~~better integration into pricing view (only one)~~ 
- [x] maybe a calculation tool

### CODE REVIEW

**Comment by matmair** [comment]
I will put the integration of all prices into one view into a ne PR after this in finished to keep the review phase shorter

**Comment by matmair** [comment]
closes #1606

**Comment by matmair** [comment]
Ready for review - docs will follow after merge

**Comment by SchrodingersGat** [comment]
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/part/174/order-prices/

Django Version: 3.2.4
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'build.apps.BuildConfig',
 'common.apps.CommonConfig',
 'company.apps.CompanyConfig',
 'label.apps.LabelConfig',
 'order.apps.OrderConfig',
 'part.apps.PartConfig',
 'report.apps.ReportConfig',
 'stock.apps.StockConfig',
 'users.apps.UsersConfig',
 'InvenTree.apps.InvenTreeConfig',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'crispy_forms',
 'import_export',
 'django_cleanup.apps.CleanupConfig',
 'mptt',
 'markdownx',
 'markdownify',
 'django_admin_shell',
 'djmoney',
 'djmoney.contrib.exchange',
 'error_report',
 'django_q',
 'formtools']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'InvenTree.middleware.AuthRequiredMiddleware',
 'error_report.middleware.ExceptionProcessor']



Traceback (most recent call last):
  File "/mnt/c/inventree/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/c/inventree/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/inventree/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/inventree/env/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/mnt/c/inventree/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/c/inventree/env/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/mnt/c/inventree/InvenTree/part/views.py", line 798, in get_context_data
    ctx = self.get_pricing(self.get_quantity())
  File "/mnt/c/inventree/InvenTree/part/views.py", line 850, in get_pricing
    if [True for a in bom_items if len(set(a['price'])) == 2]:
  File "/mnt/c/inventree/InvenTree/part/views.py", line 850, in <listcomp>
    if [True for a in bom_items if len(set(a['price'])) == 2]:

Exception Type: TypeError at /part/174/order-prices/
Exception Value: 'NoneType' object is not iterable
```

**Comment by SchrodingersGat** [comment]
Otherwise looks pretty good. Would you be able to have a look at the error above?

**Comment by matmair** [comment]
@SchrodingersGat I think I found the error altough I could not reproduce the bug itself. Please test with the new patch, that should fix that error.

**Comment by SchrodingersGat** [comment]
@matmair the error still exists, it errors out when you have one or more BOM items which do not have any pricing information:

```python
x = [True for a in bom_items if len(set(a['price'])) == 2]
```
But if `a['price'] is None`:

image

**Comment by SchrodingersGat** [comment]
I think a quick null check here will suffice for now, as this pricing view will need to be refactored when we overhaul the pricing display  / structure!

**Comment by matmair** [comment]
@SchrodingersGat I fixed this in a seperate PR #1679

**Comment by SchrodingersGat** [comment]
Ok, great. Now that the bug is fixed I'm happy to merge this in!

Please ping me when you have a documentation PR ready!

**Pull request merged**
