### PR TITLE
[PUI] Added Server Info Modal

### PR DESCRIPTION
**Pull request by matmair**
This PR adds a modal to view the system information, similar to the implementation in CUI. For this the `/api` endpoint is extended to contain all information needed for the 'System Information' panel.

### CODE REVIEW

**Comment by matmair** [comment]
I have not touched the mysql stuff @SchrodingersGat any idea what this is?

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
> I have not touched the mysql stuff @SchrodingersGat any idea what this is?

? sorry @matmair not sure what you are referring to here

**Comment by matmair** [comment]
I do not really understand that CI error. All other things are passing so maybe we can merge this?

**Comment by SchrodingersGat** [comment]
Yeah, I'll look into the CI separately.

**Pull request merged**
