### PR TITLE
UrlsMixin plugin update custom urls on load

### LINKED ISSUE #4052: Plugin UrlsMixin Issue referencing urls / django.urls.exceptions.NoReverseMatch : not a registered namespace inside 'plugin'
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

I've update my test/dev inventree instance, and I've got urls referecing issues.

The update leads to :

> InvenTree Version 	[0.9.0 dev](https://github.com/inventree/InvenTree/releases)
> Development Version
> Commit Hash	2f7be7028
> Commit Date	12/12/2022

ran invoke updates.

My composite plugin `PanelMixin/UrlsMixin`throw an error when trying to access/reverse urls in `get_custom_panels ` previously defined in `setup_urls`.
(see stack trace below and plugin code at [StockTrackPanel](https://github.com/Bbillyben/StockTrackPanel_plugin/blob/main/StockTrackPanel.py) )

As Element of debugging : 

the method `setup_urls` is called during server start, and paths seems well formed.
the property `urlpatterns` is not called at all. 

When I print in `plugin.urls.get_plugin_urls ` the plugins referenced in `registry.plugins.values`:
```
def get_plugin_urls():
    """Returns a urlpattern that can be integrated into the global urls."""
    urls = []
    print("get_plugin_urls")
    for plugin in registry.plugins.values():
        print("####### :"+str(plugin.slug))
        if plugin.mixin_enabled('urls'):
            print(      "urls :"+str(plugin.urlpatterns))
            urls.append(plugin.urlpatterns)

    return re_path(f'^{PLUGIN_BASE}/', include((urls, 'plugin')))
```
I only trace `builtin` plugins:

> get_plugin_urls
> ####### :inventreebarcode
> ####### :corenotificationsplugin

and after that, is called the `setup_urls` from my plugin without any error (not in the loop in `get_plugin_urls`, somewhere else, but I do not know where...)

**Strange behavior** : If I activate the `SampleIntegrationPlugin` It works again!!!!!
and the output from `get_plugin_urls `become:

```
get_plugin_urls
####### :inventreebarcode
####### :corenotificationsplugin
####### :sample
urls :<URLResolver <URLPattern list> (sample:sample) '^sample/'>
####### :stocktrack
[StockTrackPanel]-urlpatterns
urls :<URLResolver <URLPattern list> (stocktrack:stocktrack) '^stocktrack/'>
```
And urls are well referenced !!

I'm trying to search in plugin.registry as I can spot some recent commits for it.

If I comment all about urls in the code (path and elements for panel tempalte context), all works without error.

It works on my 'semi-prod' version : 
> InvenTree-Version: 0.9.0 dev
> Django Version: 3.2.15
> Commit Hash: fbc9925
> Commit Date: 07/10/2022

### Steps to Reproduce

Don't really know. I haven't tried with simple URLsmixin.

### Expected behavior

reference the url as it did before.

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.16
Commit Hash: 2f7be7028
Commit Date: 12/12/2022
Database: postgresql
Debug-Mode: True
Deployed using Docker: True
Active plugins: [{'name': 'CoreNotificationsPlugin', 'slug': 'corenotificationsplugin', 'version': '1.0.0'}, {'name': 'StockTrackPanel', 'slug': 'stocktrack', 'version': '0.1'}]

### Relevant log output

```shell
File "/home/inventree/data/env/lib/python3.9/site-packages/django/urls/base.py", line 71, in reverse
extra, resolver = resolver.namespace_dict[ns]
KeyError: 'stocktrack'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/inventree/InvenTree/plugin/views.py", line 26, in get_plugin_panels
panels += plug.render_panels(self, self.request, ctx)
File "/home/inventree/InvenTree/plugin/base/integration/mixins.py", line 704, in render_panels
for panel in self.get_custom_panels(view, request):
File "/home/inventree/InvenTree/plugins/StockTrackPanel_plugin/StockTrackPanel.py", line 55, in get_custom_panels
urlTrac=reverse('plugin:stocktrack:track-list')
File "/home/inventree/data/env/lib/python3.9/site-packages/django/urls/base.py", line 77, in reverse
raise NoReverseMatch(
django.urls.exceptions.NoReverseMatch: 'stocktrack' is not a registered namespace inside 'plugin'
```
```

### PR DESCRIPTION
**Pull request by Bbillyben**
For pure UrlsMixin plugin, invalidate the url to be able to trigger the update

should solve : https://github.com/inventree/InvenTree/issues/4052

why : For pure Custom UrlsMixinPlugin, the url seems not being loaded.

This (dirty ?) patch invalidate plugin parameters to force urls update (to trigger plugin.registry._update_urls => plugin.urls.get_plugin_urls)

That's explain why with an another AppPlugin everything works fine!

[edit] I've forgotten precommit tests... I will run them asap
[edit:matmair]
Closes #4052

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4065"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair does this make sense to you?

**Comment by matmair** [comment]
I mean this is one way to do it. I would prefer a separate activation method for UrlMixin TBH but this works technically. It would just be cleaner from a call structure perspective.

**Comment by Bbillyben** [comment]
Would prefer a separate method with it's own loop on plugin or manage a specific flag for URL invalidation in the same loop in this 'app' specific method?

**Comment by matmair** [comment]
@Bbillyben you suggested a change in the activation sequence for plugin_app - you could place it just below named something like `activate_plugin_url` - it needs also be placed in the activation caller below here: https://github.com/inventree/InvenTree/blob/2ca0e2eab472bb3951009ed79bd9174494dd008d/InvenTree/plugin/registry.py#L463

**Comment by Bbillyben** [comment]
Is that something like that you have suggested?

**Review by matmair — APPROVED** [review]
looks good!

**Comment by matmair** [comment]
@SchrodingersGat should be good to merge

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @Bbillyben

**Pull request merged**
