### PR TITLE
Exchange rate plugin

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR exposes the currency exchange functionality to the plugin interface.

This will allow custom exchange interfaces to be implemented if desired. For now, there is a "builtin" plugin which uses the frankfurter.app API

- Closes https://github.com/inventree/InvenTree/issues/5639
- Closes https://github.com/inventree/InvenTree/issues/5634

### CODE REVIEW

**Review by matmair — APPROVED** [review]
Interesting approach.

**Comment by SchrodingersGat** [comment]
> Interesting approach.

Good interesting, or interesting interesting?

**Review by matmair — APPROVED** [review]
Interesting approach.

**Comment by matmair** [comment]
A fast way to implement it.

This way we can only support one backend at the time and we are not utilizing the built in options to handle multiple backends as we are shimming that part of the functionality away.

**Comment by SchrodingersGat** [comment]
> A fast way to implement it.
> 
> This way we can only support one backend at the time and we are not utilizing the built in options to handle multiple backends as we are shimming that part of the functionality away.

Happy to receive a PR to extend functionality :)

**Pull request merged**
