### PR TITLE
option to hide related parts

### LINKED ISSUE #1733: Add option to hide "related parts" tab

### PR DESCRIPTION
**Pull request by matmair**
Fixes #1733

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks!

**Comment by eeintech** [comment]
@matmair @SchrodingersGat Do we actually want to keep this feature? I would say yes, we're using it lightly and was requested in #652 and implemented in #1048 but if all those "niche" features are clogging InvenTree I don't think we should keep them..?

**Comment by SchrodingersGat** [comment]
I'm happy to keep it for now. Minimal effort to keep it hidden - perhaps it should be the default?

**Comment by eeintech** [comment]
I'm okay with hidden as default, made me realize the "documentation" is buried in release notes: https://inventree.readthedocs.io/en/latest/releases/0.1.4/#related-parts

**Comment by lookme2** [comment]
I use it pretty heavily here at my place.  I vote to keep it.

**Comment by matmair** [comment]
Maybe we should make it a bit more visible in the docs.

I personally do not use this feature very much and have no strong feelings on how the default should be, just implemented the PR because I had some spare time after lunch.

**Pull request merged**
