### PR TITLE
fix part qr lable

### PR DESCRIPTION
**Pull request by skydiablo**
in ref to this issue: https://github.com/inventree/InvenTree/issues/8251

Closes https://github.com/inventree/InvenTree/issues/8251

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@skydiablo thanks for the fix  :)

**Comment by wolflu05** [comment]
Aren't other pages also affected by this now?


And isn't that introducing an xss, because we cannot trust the output of the barcode generator, since this can be influenced by how the barcode plugin is configured, or doesn't this matter since only admins can configure the barcode plugin?

**Comment by SchrodingersGat** [comment]
> Aren't other pages also affected by this now?

@wolflu05 you are correct, I misread the intent of the fix here and thought it was applied generically to all pages.

@skydiablo would you be able to submit another PR which addresses all instances of this? Perhaps even roll it into a custom template tag and make it generic.

> And isn't that introducing an xss, because we cannot trust the output of the barcode generator, since this can be influenced by how the barcode plugin is configured, or doesn't this matter since only admins can configure the barcode plugin?

As the data is encoded into a string, we just need to escape any `'` characters, to ensure it does not run as javascript, right?

**Comment by skydiablo** [comment]
hey, i would realy like to do a generic fix, but my python skills are equal zero ;) i think the problem is easy to addresse:

- find all occurrences that could be possible
- build a generic qr-code widget
  - define output to 'safe' but escape ''' characters

right?

**Comment by SchrodingersGat** [comment]
@skydiablo please refer to this PR - https://github.com/inventree/InvenTree/pull/8286

This has basically implemented what you suggested above, and runs the barcode data through bleach to ensure that it is "safe" to render into the templates

**Pull request merged**
