### PR TITLE
Plugin static files

### PR DESCRIPTION
**Pull request by wolflu05**
This PR fixes issue 1 and 4 from https://github.com/inventree/InvenTree/issues/7709#issuecomment-2244844925

This PR is marked as breaking to appear at the top of the changelog. Something like the following text should be added to the changelog for users to explain the change:

---

### ⚠️ Plugin static files (#7425) (#7763)

Previously if a plugin had the `AppMixin` and contained a `static` folder, static files where collected as part of `invoke static` like a normal django app directly in the `static` folder (e.g. `my-plugin/static/test.js` was accessible by `/static/test.js`). Now plugin static files are collected from every plugin that contains a `my-plugin/static` folder (No need for the `AppMixin` anymore) in `/static/plugins/<plugin-slug>/` meaning the `test.js` in the static folder from the previous example is now accessible from `/static/plugins/<plugin-slug>/test.js`.

The `{% plugin_static "test.js" %}` template tag from `{% load plugin_extras %}` can be used to get the correct path for a static file provided by a plugin. It is also backported to 0.15.x (#7764) and acts as a proxy to the normal `static` tag there. 

---

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@wolflu05 so with these changes are you happy that existing plugin static files are honoured, and also the new approach?

**Comment by wolflu05** [comment]
Sorry, but I don't understand your comment, could you please explain?

With this PR, the old approach using the AppMixin has no effect anymore, as the plugins get not loaded for the traditional Django static file collection. They only get copied with your added collectplugins script. That way there are no duplicated static files at two paths anymore.

Additionally I have fixed the issue with the recursive deletion.

**Comment by SchrodingersGat** [comment]
@wolflu05 sorry, was not very good description.

I mean, that the new approach allows for static file collection whether or not the plugin has "app" support. So, are we happy that this is sufficient and covers all cases?

**Comment by wolflu05** [comment]
Thanks for clarifying, Yes, I'm happy with it.

**Comment by SchrodingersGat** [comment]
Ok, well thanks for the additional fixes and insights :)

**Pull request merged**
