### PR TITLE
WIP [PUI] Migrate to Mantine v7

### PR DESCRIPTION
**Pull request by matmair**
This PR migrates the front end to Mantine v7. There were a lot of breaking changes with v7 so issues are to be expected and things need to be tested manually.

Main change: Instead of using emotion to create CSS classes, they are now pre-rendered. This should give some performance improvements.

Changes:
- Adds vanilla extract as a helper
- moves language/theme in the stack
- fixes various key errors
- updates typings
- switches colour schema manager to the new system
- switches spotlight to the new system
- migrates to new styling/parameter args
- updates all frontend dependencies
- updates tests to be a bit less flaky

### CODE REVIEW

**Comment by matmair** [comment]
@inventree/triage @SchrodingersGat this is nearly done - I only need to touch up the spotlight registering section, everything else should be stable.
I would appreciate some testing in the netlify environment as I am starting to get blind for smaller issues.

**Comment by matmair** [comment]
@SchrodingersGat ready for review

**Comment by SchrodingersGat** [comment]
@matmair a few small changes and also merged in master so it should work against netlify now

**Comment by matmair** [comment]
@SchrodingersGat I have fixed the errors

**Comment by SchrodingersGat** [comment]
@matmair looks like some conflicts have worked their way in

**Comment by matmair** [comment]
@SchrodingersGat I have fixed them again

**Comment by SchrodingersGat** [comment]
@matmair I am happy with this, it looks great!

Should we refactor the existing "recharts" graphs to use [Mantine Charts](https://mantine.dev/charts/getting-started/) before we merge?

**Comment by matmair** [comment]
I would rather merge this PR now and do that in a follow-up. I have to manually fix nearly any merge due to renaned props ins Stack, Group, Table, Button

**Comment by SchrodingersGat** [comment]
@matmair absolutely. Great work on this :)

**Pull request merged**
