### PR TITLE
Remove special character restrictions in parameter template names

### LINKED ISSUE #3852: [FR]Remove special character restrictions in parameter template names
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

I tried to add a parameter template with a name 'Current - Collector (Ic)' and it failed with: 'Illegal character in template name (()'
Are there any objections on removing this limitation like it was done in #3370?

### Suggested solution

Remove special characters limitation

### Describe alternatives you've considered

none

### Examples of other systems

I am working on an importer which transforms the data stored in the Arena and there the parameter names could have special characters like (-s

### Do you want to develop this?

- [X] I want to develop this.

### PR DESCRIPTION
**Pull request by martonmiklos**
Fixes #3852

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3883"></a>

### CODE REVIEW

**Comment by martonmiklos** [comment]
Hi @SchrodingersGat , @matmair 

This change is very similar to the #3370.
Could you help how can I generate the migrations (if necessary) for this change?

**Comment by SchrodingersGat** [comment]
Run `invoke migrate` - this should be sufficient - and then commit the new migration files

**Comment by matmair** [comment]
@martonmiklos just run inv update

**Comment by martonmiklos** [comment]
Thank you guys! I have managed to add the migrate scripts.

**Comment by SchrodingersGat** [comment]
@martonmiklos thanks for the contribution :)

**Pull request merged**
