### PR TITLE
Fix for faulty data migrations

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Replaces https://github.com/inventree/InvenTree/pull/4979

References:

- https://github.com/inventree/InvenTree/pull/4898
- https://github.com/inventree/InvenTree/pull/4961
- https://github.com/inventree/InvenTree/pull/4977

Implements a *new* fix which does not require any custom SQL, and adds a unit test.

Additionally this migration has been tested multiple times backwards / forwards / upside down

### CODE REVIEW

**Comment by miggland** [comment]
This looks the "proper" way to do it. :+1: 

I have tested this, starting at two different points (one of which caused problems with the other implementation), and from scratch, all worked.

**Review by miggland — APPROVED** [review]

**Comment by matmair** [comment]
It works on ubuntu + mariadb; I only have access to my production/staging environment with SE  Linux in a few hours but it should be good.

**Comment by SchrodingersGat** [comment]
@matmair any further input on this or happy for me to merge?

**Comment by matmair** [comment]
I have tested this in multiple instances now - should fix the issue finally

**Pull request merged**
