### PR TITLE
SO sale price

### LINKED ISSUE #1592: Add weight to a part and sum in sales orders and assemblies to calculate shipping
Add a weight parameter in such a way that the price for shipping can be estimated for assemblies or multiple part sales orders.

### PR DESCRIPTION
**Pull request by matmair**
Adds a total sale price for SOs and a checksum like in the BOM.

- [ ] total price calculation + adding weight to total sum for overhead etc.
- [ ] add global weight
- [ ] tests
- [ ] documentation

Closes #1592

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair why did you close this one?

**Comment by matmair** [comment]
@SchrodingersGat I am going to restructure this whole thing so I closed the draft

**Comment by SchrodingersGat** [comment]
Fair enough :) Sorry that there's so many open PR's that require attention. Busy time of year!

**Comment by matmair** [comment]
It's OSS, nobody gets paid so no worries

**Pull request closed without merging**
