### PR TITLE
first implementation of improved docker

### PR DESCRIPTION
**Pull request by ChristianSchindler**
Based on: https://github.com/inventree/InvenTree/issues/6303

### Improve Docker Image:

1) Run `invoke update` Automatically on image updates
2) Combine Server and Worker 1 container

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I have some concerns that this goes against [docker best practice](https://testdriven.io/tips/59de3279-4a2d-4556-9cd0-b444249ed31e/#:~:text=Docker%20best%20practice%3A,needed%20to%20handle%20more%20traffic.)

### Process Reliability

If one of the processes (web worker, background worker) fails - this may be obscured by this update. The docker container generally manages process state, and allows auto-restart of the process due to an error

### Logging

Again, running a background process in the docker container may obscure logs - which are crucial for debugging InvenTree performance.

### Scalability

While "simplifying" the docker container setup, this reduces the flexibility of the setup.

------------------

I'd like to hear your thoughts on the potential advantages. Maybe I am missing something here, but the `docker compose` file takes care of all of this abstraction anyway...

**Comment by ChristianSchindler** [comment]
@SchrodingersGat 
> Process Reliability
>
>If one of the processes (web worker, background worker) fails - this may be obscured by this update. The docker container generally manages process state, and allows auto-restart of the process due to an error

If I can do it so that if one fails, the complete container restarts, is this ok?

>Logging
>
>Again, running a background process in the docker container may obscure logs - which are crucial for debugging InvenTree performance.

I know that's why I made it so that both still print out and also add in front `Sever` or `Worker` to identify where the problem lays

>Scalability
>
>While "simplifying" the docker container setup, this reduces the flexibility of the setup.

If you want to scale, this is still entirely possible. Then you can use it without the script similar to it is now, but most will not need it, and that's a way for it to be as easy as possible.

**Comment by ChristianSchindler** [comment]
@matmair 
>Looks intresting @ChristianSchindler - could you expand the description of the PR a bit more?
Seems like a notable shift in the deployment strategy that would need concesus within @inventree/triage @inventree/maintainer and docs updates + release notes.


In gennerla ther are two changes:
1) Automatic updates if there is a new db version or on the first install
2) In general, you can remove the worker, and then it is entirely the same as before.

**Comment by matmair** [comment]
Please ammend your explaination to the PR description to make it easier to find

**Comment by matmair** [comment]
@ChristianSchindler  We will not merge this with a combined worker and server container in the compose due to the resons listed by @SchrodingersGat above.
If you are open to revert that change we are willing to review and merge the auto-update, which seems valueable.

**Comment by ChristianSchindler** [comment]
> @ChristianSchindler We will not merge this with a combined worker and server container in the compose due to the resons listed by @SchrodingersGat above. If you are open to revert that change we are willing to review and merge the auto-update, which seems valueable.

Sorry had no time will look at it next week

**Pull request closed without merging**
