### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by matmair**
This PR upgrades the way dependencies are handled.
## What?
Dependencies are described with their version requirements. If there is a need to pin a package to a specific or under/over a specific version that is defined, else the newest is used.
## How?
 The requirements are defined in a *.in file and then compiled by pip-tools to a normal *.txt file with each version pinned. So each time you want to update all requirements you just run the command 'pip-compile' and the most current versions matching is written to the *txt file.

## Changes
- Split requirements
- Update to pip-tools
- Remove pinning to the newest version
- Rewrite the version pinning where it is known

## Open questions
Do we need this package?
- django-admin-shell (also update from 0.1.2 -> [1.0.0](https://pypi.org/project/django-admin-shell/))
- django-cleanup (also update from 5.1.0 -> [6.0.0](https://pypi.org/project/django-cleanup/))
- pygments (also update from 2.7.4 -> [2.12.0](https://pypi.org/project/Pygments/))

Bigger updates:
- coverage 5.3 -> [6.4.1](https://pypi.org/project/coverage/)
- coveralls 2.1.2 -> [3.3.1](https://pypi.org/project/coveralls/)
- flake8 3.8.3 -> [4.0.1](https://pypi.org/project/flake8/)
- django-crispy-forms 1.11.2 -> [1.14.0](https://pypi.org/project/django-crispy-forms/)
- django-filter 2.4.0 -> [22.1](https://pypi.org/project/django-filter/)
- django-import-export 2.5.0 -> [2.8.0](https://pypi.org/project/django-import-export/)
- ~~django-markdownify 0.8.0 -> [0.9.2](https://pypi.org/project/django-markdownify/)~~
- django-mptt 0.11.0 -> [0.13.4](https://pypi.org/project/django-mptt/)
- django-sql-utils 0.5.0 -> [0.6.1](https://pypi.org/project/django-sql-utils/)
- django-stdimage 5.1.1 -> [6.0.1](https://pypi.org/project/django-stdimage/)
- qrcode[pil] 6.1 -> [7.3.1](https://pypi.org/project/qrcode/)
- rapidfuzz 0.7.6 -> [2.0.11](https://pypi.org/project/rapidfuzz/)

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3228"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat could you just 👍  or 👎 the updates and removals?

**Review by SchrodingersGat — APPROVED** [review]
Nice overhaul @matmair

**Comment by matmair** [comment]
@SchrodingersGat we will have to find those uncovered things anyways - my hope with reducing the decencies is to remove external sources of security problems and removing unneeded slack from installs and the admin ui.

Any objections to removing the listed packages? I do not see their functions included anywhere in the code / their functions seem to be oriented very much towards server admins - who should have shell access anyway.

**Comment by SchrodingersGat** [comment]
Django cleanup is crucial - it ensures that unused media files are correctly deleted.

I use django-admin-shell for debug, but there's no reason it should be a core requirement.

Not sure what pygments is used for, if anything. Can probably safely be deleted.

**Comment by SchrodingersGat** [comment]
In addition to removing `django-admin-shell`, can you please remove the `django-debug-toolbar` integration as part of this refactor...

**Comment by matmair** [comment]
> In addition to removing `django-admin-shell`, can you please remove the `django-debug-toolbar` integration as part of this refactor...

@SchrodingersGat I moved `django-debug-toolbar` to dev - should I completly remove it?

**Comment by matmair** [comment]
@SchrodingersGat this should be good to go - I moved django-debug-bar to dev; lmk if I should just purge it.

**Comment by SchrodingersGat** [comment]
Looks like the updates have killed our CI checks

**Comment by matmair** [comment]
@SchrodingersGat looks like there is a something more complex happening - looking into it rn

**Comment by matmair** [comment]
@SchrodingersGat turns out there were a few breaking changes in mayor updates. Should ironed out now.
Still working on two new migrations - looking if they can be reduced.

**Comment by SchrodingersGat** [comment]
@matmair good for review?

**Pull request merged**
