### PR TITLE
Switch to zoneinfo from pytz

### PR DESCRIPTION
**Pull request by matmair**
We target 3.9 which has zoneinfo for timezone info instead of pytz.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Nice. Should we also remove pytz from the requirements?

**Comment by matmair** [comment]
@SchrodingersGat sadly not, some of our dependencies still depend on it

**Comment by matmair** [comment]
I need to figure out why CI works on my machine but not on GH

**Comment by matmair** [comment]
This is more complex than initially thought. https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html
I am amazed we have not had problems with pytz before.

**Comment by SchrodingersGat** [comment]
Wow, what a deep dive!

**Comment by SchrodingersGat** [comment]
@matmair it would be great to get this one closed out if you have some time to assign to it :)

**Comment by matmair** [comment]
@SchrodingersGat this is more a skill not a time issue ;-) I can look into it after sso and selection lists

**Comment by SchrodingersGat** [comment]
Ok, LMK if you are banging your head against the wall on it!

**Comment by matmair** [comment]
@SchrodingersGat can you take a look at this? Especially the change in the test assertations. Maybe I am missing something but the previous assertations seem strangely off by a few minutes.

**Comment by 1337joe** [comment]
It looks like this is a somewhat known problem with pytz:
https://stackoverflow.com/questions/27531718/datetime-timezone-conversion-using-pytz
https://stackoverflow.com/questions/60996205/python-datetime-timezone-conversion-off-by-4-minutes

Long story short, using `replace(tzinfo=...` (what InvenTree was using) can make invalid assumptions, where `localize(time)` would try to correct for that.

For what it's worth, your updated test values all look correct to me.

**Comment by matmair** [comment]
@SchrodingersGat ready for review and merge; I have marked it as breaking as a precaution, I do not think it should break anything

**Comment by SchrodingersGat** [comment]
@matmair seems like a minimal change overall, in the end. Thank you for looking into this one.

**Pull request merged**
