### PR TITLE
Packager add 22.04 support

### PR DESCRIPTION
**Pull request by matmair**
WIP

Part of https://github.com/inventree/InvenTree/issues/3836

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3841"></a>

### CODE REVIEW

**Comment by matmair** [comment]
Currently running into a pretty big show-stopper: 
grafik
the SSL module is not available in the buildpack so pip installs are not working

**Comment by matmair** [comment]
This is a somewhat known issue; I would prefer to not build openssl on each packaging run: https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di

**Comment by matmair** [comment]
ok we need to get this package onto the build server: https://packages.ubuntu.com/focal/libssl1.1

**Comment by matmair** [comment]
Resting this for now; the build is pretty much not working rn; as we are rebuilding the env in the postinstall we might be able to just disable the compile step but that would not be very future proof.

**Comment by SchrodingersGat** [comment]
@matmair did you want this in 0.9.0?

**Comment by matmair** [comment]
@SchrodingersGat this is actually not needed anymore as the 20.04 package seems to run fine on 22.04

**Pull request closed without merging**
