### PR TITLE
One pricing view

### PR DESCRIPTION
**Pull request by matmair**
This is a quick draft for #1656 2.1 - One view for everything pricing.

Missing:
- [x] supplier cost table -> maybe merge in the views for manufacturer- and supplier-parts?
- [x] BOM cost item table
- [x] sale price history graph

Possible optimisations:
- [x] JS for price-breaks is really repetitive - refactor into function
- [x] add graphs to price breaks
~~- [ ] highlight currently active price-break-steps~~ -> not really a value-add
- [x] sort price-breaks on load
- [x] links to sections in pricing ranges
- [ ] general doc for prices and links in each section
~~- [ ] more permissions? -> RFC~~ -> not neccesary

### CODE REVIEW

**Comment by matmair** [comment]
@eeintech @SchrodingersGat would appreciate your thoughts, esp. if that is the right general direction. Would merge 3-5 pages into one.

**Comment by SchrodingersGat** [comment]
@matmair can you share a screenshot of what you have so far?

**Comment by matmair** [comment]
@SchrodingersGat here you go
grafik

**Comment by matmair** [comment]
Updated screenshot with tables added:
grafik

**Comment by SchrodingersGat** [comment]
That looks amazing! I really like that :)

**Comment by eeintech** [comment]
Wow I have to agree, great job on the pricing overall! :+1: 

Do you plan on removing the modal form accessible through the "dollar" icon button?

**Comment by matmair** [comment]
@SchrodingersGat @eeintech thank you. It is very 'packed', I will try to make it a bit cleaner.
I would like to keep the modal around for fast lookups but maybe refactor it a bit.

Anything missing you would like to see?

**Comment by SchrodingersGat** [comment]
> Anything missing you would like to see?

Nothing that immediately jumps out at me. Let us know when this is ready to pull and review :)

**Comment by matmair** [comment]
@eeintech @SchrodingersGat  current state:
grafik
only thing left is docs... will open a WIP in the doc repo tomorrow

**Comment by SchrodingersGat** [comment]
Looks fantastic! I'll pull and have a look through when I have some time later this week.

**Comment by SchrodingersGat** [comment]
For some reason the BOM pricing view isn't showing up?

Is there some option I need to set?

image

**Comment by matmair** [comment]
@SchrodingersGat this was a bug caues when there was no purchase price data, please try again

**Comment by SchrodingersGat** [comment]
Ok, that looks good now. I'm really liking how this has turned out!

Happy to merge this in now, thanks for all the great work @matmair 

If you can make a docs PR about the updated pricing structure at some stage, that would be great too.

**Comment by eeintech** [comment]
@matmair One question about the "Supplier Cost" section, what is the intent? It feels like this section is just combining both "Manufacturers" and "Suppliers" tab into one single place, and I don't really know what is the purpose :thinking:

**Comment by matmair** [comment]
@eeintech the idea is to unify all pricing info into one place. It is indeed a duplicate, as the BOM section.

**Comment by eeintech** [comment]
@matmair Where is the pricing data in that section? I'm not getting any price column or similar...

**Comment by matmair** [comment]
@eeintech have you disabled the column by any chance?

**Comment by eeintech** [comment]
I don't see any new column:

image

image

**Comment by eeintech** [comment]
@matmair What are you getting?

**Comment by matmair** [comment]
@eeintech sorry I thought about the BOM cost section, prices are already in there. The adapatations for price history and current cost for Supplier and Manufacturer table are still on my huge wish list #1656.

**Comment by eeintech** [comment]
I see, sounds good no rush!

**Pull request merged**
