### PR TITLE
Label printing unit test

### PR DESCRIPTION
**Pull request by matmair**
This PR increases the coverage for the internal (python) and external (web) label APIs.

Closes #3037

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3047"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat 👀

**Comment by SchrodingersGat** [comment]
Nice. Is this intended to replace https://github.com/inventree/InvenTree/pull/3037?

**Comment by matmair** [comment]
> Nice. Is this intended to replace #3037?

Working on it

**Comment by matmair** [comment]
Ref: https://github.com/inventree/InvenTree/issues/2992

**Comment by SchrodingersGat** [comment]
@matmair looks good, almost 1% increase in code coverage! Nice work :)

**Pull request merged**
