### PR TITLE
Adds a user-configurable setting to configure how dates are displayed

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Closes https://github.com/inventree/InvenTree/issues/2581

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2685"></a>

### CODE REVIEW

**Review by matmair — APPROVED** [review]
Looks good

**Comment by SchrodingersGat** [comment]
Requires https://github.com/inventree/InvenTree/pull/2684 to be merged first, as that PR introduces some new front-end date fields that will need to be formatted.

**Comment by matmair** [comment]
@SchrodingersGat sure that you want this to be 0.7.0? Might be a quite a time till we land that juding by the last one.

**Comment by SchrodingersGat** [comment]
@matmair i'd like to push the next stable release out quicker, which may mean we need to select some PRs to push back (again)

**Pull request merged**
