### PR TITLE
Tracing improvements

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Update code to ensure that the "tracing" is only enabled for the server process (not the worker process!)

### CODE REVIEW

**Comment by matmair** [comment]
I do not understand the value of this change; having spans of all server actions seems valueable. Can you be more specific what the benefit is here?

**Comment by SchrodingersGat** [comment]
The tracing only monitors external API function calls, right? Or do internal processes (e.g. the background worker) get traced too?

Aside from this question, I think it makes sense to disable tracing for other "temporary" processes like importing data or running migrations, yes?

**Comment by matmair** [comment]
@SchrodingersGat every general process get's traced - so background workers should show up too. That might depend on the data backend though.

**Comment by wolflu05** [comment]
(Even if we close that pr, I think we should keep the added invoke task (already would needed that a while ago) and the two guard functions.)

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat every general process get's traced - so background workers should show up too. That might depend on the data backend though. If tracing is enabled I would trace everything possible to be able to find performance bottlenecks. The overhead is not too high on performant machines (esp with fast network).

Ok, fair enough. What are your thoughts on disabling tracing for operations such as "import" or "migration"? My justification is to simplify the running code in these parts, as this is where we get a lot of problems.

**Pull request merged**
