### PR TITLE
Set Responsible User for a Part during creation or API

### LINKED ISSUE #1416: [FR] Cannot set Responsible User for a Part during creation or API
The responsible user can be set in the administrator interface. I found no way to set it during normal part creation. I also found no way to set it via API and python extension. Do I miss something?

### PR DESCRIPTION
**Pull request by matmair**
Closes #1416 

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4326"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SergeoLacruz would you mind checking if this satisfies your original FR?

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
I'll wait for feedback from @SergeoLacruz

**Comment by SergeoLacruz** [comment]
Hi,
Works great :+1: Thanks for the help. If I knew it was that easy...
Next time I will try on my own. 
Michael

**Comment by SchrodingersGat** [comment]
@SergeoLacruz we'd be happy to see you contribute! We are always happy to help out :)

**Comment by matmair** [comment]
@SergeoLacruz if you know where to look it is pretty simple. Like with most things. I think we could improve the contribution docs and lay out the architecture better.

**Pull request merged**
