### PR TITLE
Pricing reformat

### PR DESCRIPTION
**Pull request by matmair**
@eeintech Is that more like you think it should be?

### CODE REVIEW

**Comment by eeintech** [comment]
Sorry but I am still confused by the mix of information in this part detail page... In https://github.com/inventree/InvenTree/issues/1577#issuecomment-856314057 you said:

> Stock prices alone are not very informative. the quantity serves to help the user to get a feel how much (in total) they paid for the stock while the difference helps to show how much prices differ from the calling price for that supplier price 

The working of the tab is "Order Pricing", so I will think this is pricing information from sales and purchase orders.

Then the graph is called "Stock Pricing", so I am assuming this is pricing for the current stock, one has to know that this price was either set by:
- a purchase order
- manually on the stock item
The graph also uses some pricing information from the supplier part data (price breaks).

And there is the "Part Pricing" modal view, which exclusively uses supplier part data.

You've done a great work with this graph, however pricing strategy is missing clarity. I understand well how the mechanics of InvenTree work but for "casual" users, like my colleagues, are getting lost.

I _think_ we need to revamp the pricing into a single view called "Pricing". On top of my mind, it should break down into 2 sections: "Supplier Pricing" and "Stock Pricing" (as opposed to "Order"). The first section will feature what's in the "Part Pricing" modal view and the second features the "Stock Pricing".

The cohesion will help explain the logic.

What do you think?

**Comment by matmair** [comment]
@eeintech I am actually working towards one view put there are still a few pieces like internal prices(#1634 #1606 ) missing.
I already have a mock-up tested internally but there are functions missing in the system for making it all work right now. I envision graphs with the different kinds of prices to match them more easily. Also assistants for adding weighted (#1592 ) margins and alerts for adjusting sale and internal prices if the purchase prices or margins change. But all functions should be opt-in to make it slim by default. Plus revamped docs and permissions for prices.

I try to make the PRs smaller now as more than one change takes forever to discuss and get merged (see #1588).

**Comment by matmair** [comment]
@SchrodingersGat do you prefer big PRs or small single-issue incremental changes?

**Comment by SchrodingersGat** [comment]
@matmair smaller PRs are definitely easier to manage, where possible :)

**Comment by SchrodingersGat** [comment]
@matmair is this PR still relevant or is it going to be rolled in to the "pricing page" strategy?

Bottom line should we merge this in now, or close and await #1656

**Comment by matmair** [comment]
@SchrodingersGat  This was an intermidate fix for some valid ciritisms of the changed view - i would prefer this to be rolled in so that master is a bit more usable and cleaner.

**Pull request merged**
