### PR TITLE
Updated Dark Reader CSS for BS5

### LINKED ISSUE #2211: [FR] Refactor themes for Bootstrap 5
> Should we refactor the themes too?

Yes, to both these things. Let's address these with separate PRs.

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/issues/2205#issuecomment-955198167_

### PR DESCRIPTION
**Pull request by eeintech**
@SchrodingersGat @matmair Bootstrap 5 looks very nice!

Fixes #2211 

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2297"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@eeintech it seems like there is a new workflow in here?

**Review by matmair — APPROVED** [review]

**Comment by eeintech** [comment]
@matmair Sorry for that I had to force pull the master to erase my previous test of [CodeSee](https://www.codesee.io/)

**Comment by matmair** [comment]
Seems to be a nice tool. Does it work well for our codebase?
________________________________
Von: Francois ***@***.***>
Gesendet: Thursday, November 11, 2021 2:17:33 PM
An: inventree/InvenTree ***@***.***>
Cc: Matthias Mair ***@***.***>; Mention ***@***.***>
Betreff: Re: [inventree/InvenTree] Updated Dark Reader CSS for BS5 (PR #2297)


@matmair<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmatmair&data=04%7C01%7C%7C32761e3f0c094f1685a408d9a5159f93%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637722334549598603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=seBirKc%2B3nEH8CjOeMZjD2RmTt0D%2F4Y8LglGeTUN7JI%3D&reserved=0> Sorry for that I had to force pull the master to erase my previous test of CodeSee<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.codesee.io%2F&data=04%7C01%7C%7C32761e3f0c094f1685a408d9a5159f93%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637722334549608599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DAufAZFl7bcxc6l9%2B32UjNpVD6AU5fPJitMk3VAo6e4%3D&reserved=0>

**Comment by eeintech** [comment]
@matmair I wouldn't recommend it... you just get blobs of boxes, not very insightful on this project..

**Comment by eeintech** [comment]
Fixes #2211

**Comment by matmair** [comment]
> @matmair I wouldn't recommend it... you just get blobs of boxes, not very insightful on this project..

Can you share some screenshots? Maybe useful for refactoring or as an overview for @schrodingersGat

**Comment by eeintech** [comment]
Here are some screenshots:

image

image

image

**Comment by matmair** [comment]
@eeintech thanks. Seems helpful for refactoring but nothing else

**Comment by SchrodingersGat** [comment]
@eeintech thanks for the update, looks really nice :)

**Comment by eeintech** [comment]
@SchrodingersGat You're welcome, easy fix!

**Pull request merged**
