### PR TITLE
webp image support

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Currently the docker install does not support webp images, while *some* bare-metal installs do.

Given the popularity of webp images, especially among electronics distributors, this PR adds (and tests) support for webp

Closes https://github.com/inventree/InvenTree/issues/2988

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2993"></a>

### CODE REVIEW

**Review by matmair — APPROVED** [review]
Nice one - should catch some docker problems sooner

**Comment by SchrodingersGat** [comment]
@matmair interestingly some tests have already failed when building under docker

image

The environment variables test is failing.  Any thoughts on how to address this one?

**Comment by matmair** [comment]
@SchrodingersGat could you merge in recent changes? The import should work in alpines version of python3

**Comment by SchrodingersGat** [comment]
Annoyingly this `EnvironmentVarGuard` import issue is still hanging around. I can't import `test.support` in any version of python I try.. Any ideas?

**Comment by matmair** [comment]
@SchrodingersGat I will have a look at that.

**Comment by matmair** [comment]
@SchrodingersGat working on this on my fork:
https://github.com/matmair/inventree/tree/webp-support will ping you once it runs.

**Comment by matmair** [comment]
@SchrodingersGat can you try merging my branch into yours?

**Comment by SchrodingersGat** [comment]
@matmair still no luck. What version of python are you running?

**Comment by matmair** [comment]
3.8 - but this function was introduced in 3.2 . I do not get it

**Comment by SchrodingersGat** [comment]
Huh, it appears that the `inventree-python` library is installing a library "test" into the venv which is overriding the default test package install:

image

**Comment by SchrodingersGat** [comment]
Well progress, of sorts.. I've fixed the `inventree-python` issue, but now getting a new error message:

image

**Comment by matmair** [comment]
@SchrodingersGat python packages/imports are sometimes... flawed

**Comment by SchrodingersGat** [comment]
@matmair would you be ok with changing this test to not use `test.support` module? It is [not recommended for public consumption](https://docs.python.org/3/library/test.html)

Maybe something like [this](https://adamj.eu/tech/2020/10/13/how-to-mock-environment-variables-with-pythons-unittest/)?

**Comment by matmair** [comment]
@SchrodingersGat I was not aware of this option. Seems like a good solution.

**Comment by matmair** [comment]
@SchrodingersGat please merge again from my branch

**Comment by SchrodingersGat** [comment]
Let's see how we go this time

**Pull request merged**
