### PR TITLE
refactor custom file lookup

### PR DESCRIPTION
**Pull request by matmair**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Looks good, except that (unless there's a reason) I'd rather it be called `get_custom_file` over `get_cstm_file`?

**Comment by matmair** [comment]
@SchrodingersGat no problem, I will change this

**Comment by SchrodingersGat** [comment]
Thanks for the refactor :)

**Comment by SchrodingersGat** [comment]
@matmair bad news. This has broken *stuff*..

https://github.com/inventree/InvenTree/runs/7837878419?check_suite_focus=true

Basically, the `invoke` script makes use of this file and must run *before* django is installed. Classic chicken and egg.

I think we might have to revert this one? LMK if you can see a cleaner solution otherwise I'll rewind this.

**Comment by matmair** [comment]
@SchrodingersGat I will create a patch

**Pull request merged**
