### PR TITLE
Dynamic form fixes

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Addresses https://github.com/inventree/InvenTree/pull/936

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@eeintech this should fix the issues that you found!

**Comment by eeintech** [comment]
Oh wow, should have just asked you! Thanks!

**Comment by SchrodingersGat** [comment]
Haha no worries - it was a pretty subtle issue in the end. I've had to learn much more about web dev than I ever expected ;)

**Comment by eeintech** [comment]
Sounds like it! Sorry that I ended-up with a workaround instead of a proper solution. I'm still getting familiar with Django and working up my Python knowledge, soon I'm hoping to really dig into the Javascript world, although I really want to feel strong with those two first!

**Pull request merged**
