### PR TITLE
Improve reproduciblity of image

### PR DESCRIPTION
**Pull request by matmair**
This PR implements a few recommodations to get the docker image more reproducible - this is part 1 of x.

Details:
- pins all python requirements that go into releases and requires hashes for all of them
- moves form npm installing yarn to using the distro packages version of  yarn to remove the un-hashed dependency
- updates docs to suggest safe install commands
- attempts to make pip install command flags more regular

### CODE REVIEW

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair thanks, this looks like a good improvement to our build process

**Comment by SchrodingersGat** [comment]
@matmair unfortunately looks like this has killed our docker build:

https://github.com/inventree/InvenTree/actions/runs/8871817996/job/24355315797

Can you please look into this? We have the imminent `0.15.0` release which I'm hoping to do this week

**Comment by matmair** [comment]
Intresting, I am building with this config on my fork without problems https://github.com/invenhost/InvenTree/actions/runs/8866943340/job/24344952569 - will look into it

**Comment by matmair** [comment]
@SchrodingersGat it seems the image is now building: https://github.com/inventree/InvenTree/actions/runs/8872458471/job/24356836662

**Comment by SchrodingersGat** [comment]
@matmair odd, perhaps it was a temporary failure on the other build run. Let's keep a close eye on this.

**Pull request merged**
