### PR TITLE
Translation improvements

### PR DESCRIPTION
**Pull request by matmair**
This PR addresses #753 and adds translations to models and forms.

I also changed a few translation methods where necessary to enable multi-lingual use of the system (see [django docs](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#lazy-translations).

There are still a few things I would like to fix:
- [x] make object-states translatable (eg. filters on part states)
- [x] maybe cache translated JS-files to improve performance -> maybe new issue?
- [x] maybe we should go through all translations, I saw a lot of stuff that might cause issues with translations to not [romance languages](https://en.wikipedia.org/wiki/Romance_languages) eg: `<p>{{item.count}}{% trans ' elements found' %}</p>`

### CODE REVIEW

**Comment by matmair** [comment]
yeah the CI just reminded me I forgot to make the migrations, cool new system @SchrodingersGat

**Comment by matmair** [comment]
- [ ] translate action column in InvenTree/sorck/views.py > StockAdjust/get/titles

**Comment by matmair** [comment]
- [ ] translate calender

**Comment by matmair** [comment]
@SchrodingersGat I would be done with this but the CI throws an error which I cannot really understand, mind taking a look?

**Comment by eeintech** [comment]
@matmair You're just having styling errors in the following files:

``` bash
InvenTree/part/models.py:2163:33: E127 continuation line over-indented for visual indent
InvenTree/order/models.py:641:106: E203 whitespace before ','
InvenTree/build/forms.py:213:14: E251 unexpected spaces around keyword / parameter equals
InvenTree/build/forms.py:213:16: E251 unexpected spaces around keyword / parameter equals
```

**Comment by matmair** [comment]
@eeintech thank you, I was confused because my local flake8 did not catch those, seems like i setup vscode false

**Comment by eeintech** [comment]
No problem, looks stylish now!

**Comment by SchrodingersGat** [comment]
Great work, I like your idea about "caching" the translated javascript files. I've made a new issue for that.

Is your current translation effort in this PR ready to merge? :0

**Comment by matmair** [comment]
@SchrodingersGat This branch is done and can be merged, I am doing all the experimental stuff in own branches.
The caching-idea has some problems, I will share the results of my experiments in the issue.

**Comment by SchrodingersGat** [comment]
Many thanks for your contributions!

**Pull request merged**
