### PR TITLE
Add setting for enabeling reports

### LINKED ISSUE #2278: [FR] Turn off reports by default
**Problem**
A lot of report buttons do nothing on a fresh install

**Suggested solution**
Make reports a global setting and disable them by default.

**Describe alternatives you've considered**
We could also do nothing

**Do you want to develop this?**
Yes

### PR DESCRIPTION
**Pull request by matmair**
Fixes #2278

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2288"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat you wanted to add something about reports? The PR for disabling the buttons would be ready else.

**Comment by matmair** [comment]
Any idea how to detect if the instance is being set up new or just updated? Would need that for a migration to keep printing enabled if the instance is just updated.

**Comment by SchrodingersGat** [comment]
> Any idea how to detect if the instance is being set up new or just updated? 

Good question. We would also need this for the "getting started" guide, I would imagine.

This PR looks OK apart from this, your solution is a lot more elegant than the one I was thinking of :)

**Comment by matmair** [comment]
> 
> 
> > Any idea how to detect if the instance is being set up new or just updated?
> 
> Good question. We would also need this for the "getting started" guide, I would imagine.
> 
For getting started I thought of adding that in in parallel with a unique identifier file that I will need for some advanced security features and just probe if that is present. I can add that now. The sec feature will take a while as it will depend on the plugin system. Keyword: Federation 😇.
>
> This PR looks OK apart from this, your solution is a lot more elegant than the one I was thinking of :)
It does not disable the functionality as that will mess with labels but that would be only a few lines if you want it to be there.

**Comment by eeintech** [comment]
> > Any idea how to detect if the instance is being set up new or just updated?
> 
> Good question. We would also need this for the "getting started" guide, I would imagine.

Thought there could be an easy tip from Django doc on how to do this but don't see nothing... A custom flag would have to do I guess?

**Comment by SchrodingersGat** [comment]
It might be more effort than it is worth. 

Perhaps we just add a note in the docs that this setting must be turned on to enable reporting? We might have to answer a few bug reports about this, but I feel like that might be a simpler solution than potentially introducing a new bug vector.

**Comment by matmair** [comment]
Ready for merge then!

**Comment by SchrodingersGat** [comment]
@matmair could you please add a quick PR to the docs about this new feature?

https://inventree.readthedocs.io/en/latest/report/report/#report-options

**Pull request merged**
