### PR TITLE
Setting refactor

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Adds helper functions for "get" and "set" for server-side settings.

- Code reduction
- Improves "cyclical" imports

### CODE REVIEW

**Review by matmair — APPROVED** [review]
LGTM; should we add a pre-commit hook that ensures the new helpers are used / the model is not accessed directly?

**Comment by SchrodingersGat** [comment]
@wolflu05 @matmair any insights into why CI might be failing here, on SQLITE / python 3.9, but works on 3.12?

**Comment by matmair** [comment]
Not really sure - looks like the DB is not cleaned

**Comment by SchrodingersGat** [comment]
I cannot reproduce locally on a 3.9/sqlite setup...

**Comment by SchrodingersGat** [comment]
@matmair found the issue, a new setting was being created in the validator for a different setting.

**Comment by matmair** [comment]
That is a tricky one to find!

**Pull request merged**
