### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Simplify docker setup procedure
- Now uses a pre-baked custom Caddy container
- Closes https://github.com/inventree/InvenTree/issues/6920
- Ref: https://github.com/inventree/inventree-caddy
- Ref: https://hub.docker.com/r/inventree/inventree-caddy

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat what is not really clear to me is the plan regarding keeping the image up to date with both upstream (caddy and inventree). Will there be a release for each caddy release and each inventree release? How does a user determine if they have the right container if we need to change the settings (for https://github.com/inventree/InvenTree/pull/7724 for example)?

**Comment by wolflu05** [comment]
I personally find this setup much more complex than just downloading an extra Caddyfile, I mean I still have to download the extra .env file, why not also download an Caddyfile. We may could provide something like this to just copy to download all required files by one command:
```bash
curl --remote-name-all https://raw.githubusercontent.com/inventree/inventree/stable/contrib/container/{docker-compose.yml,.env,Caddyfile}
```

**Comment by SchrodingersGat** [comment]
All reasonable points. On balance I don't think this is worth pursuing any further.

**Comment by SchrodingersGat** [comment]
Another idea would be to generate a new `Caddyfile` into the shared volume (externally mounted) if one does not already exist (like we already do for `config.yaml` or `plugins.txt`), Then, the caddy image can make use of that when it launches

**Pull request closed without merging**
