### PR TITLE
Adds release.yml file for auto-generating release notes

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Ref: https://github.com/inventree/InvenTree/issues/3078

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3099"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair it looks like this will require some further work... I tried to auto-generate a release, and it added notes for every commit since `0.4.0`! Hopefully there are some options I can tweak to get it to work better than that...

**Comment by matmair** [comment]
@SchrodingersGat I will look into that

**Comment by SchrodingersGat** [comment]
Looks similar to the issues here: https://github.com/github/feedback/discussions/5975

**Comment by SchrodingersGat** [comment]
@matmair I have worked out what is happening. `0.4.0` was the last release which was tagged on the *master* branch. All subsequent releases have been branched off, and then tagged. So the release notes algorithm can't "see" those newer releases.

Going forward, a more consistent approach of tagging major releases on the master branch, and then creating release branches from there, should allow the system to work properly. So, this is how I'll do releases starting at `0.8.0`

**Comment by matmair** [comment]
@SchrodingersGat why not start with the next point release? Then we can test before releasing the next minor.

**Pull request merged**
