### PR TITLE
[Feature] Add RMA support

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds support for "RMA" or "Return Order" functionality.

Initial implementation may be somewhat "bare bones" and need fleshing out in greater detail in subsequent PRs.

- Closes https://github.com/inventree/InvenTree/issues/3298

### TODO

- [x] Add setting to enable / disable `Return Order` functionality (default = off)
- [x] Implement "detail" screen for individual Return Order
- [x] Implement API endpoints for attachments
- [ ] ~~Implement "calendar view" for Return Order List~~ - future work
- [x] Enable search results in quick-search bar
- [x] Enable search results in search page
- [x] Add "line item" model
- [x] Add "extra line item" model
- [x] Add functionality for returning goods
- [x] Clean and add database migrations
- [x] Add models for return reports (and implement functionality for this)
- [x] Generate a "nice" basic report for return orders
- [x] Unit testing for ReturnOrder API endpoints
- [x] Unit testing for Contact API endpoints
- [x] Unit testing for returnorder report generation
- [x] Unit testing for page permissions
- [x] Split `order.js`
- [x] Reinvigorate `contact` model
- [x] Add "point of contact" to purchase order and sales order modesl
- [x] Add dataset for new "Contact" model - https://github.com/inventree/demo-dataset/pull/40
- [x] Add dataset for ReturnOrder - https://github.com/inventree/demo-dataset/pull/41
- [x] Add app issue for supporting "point of contact" - https://github.com/inventree/inventree-app/issues/285
- [x] Add app issue for supporting return orders - https://github.com/inventree/inventree-app/issues/286
- [x] Add documentation for "contacts" - https://github.com/inventree/inventree-docs/issues/455
- [x] Add documentation for "Return Order" - https://github.com/inventree/inventree-docs/issues/458
- [x] Update documentation for "Purchase Order" - https://github.com/inventree/inventree-docs/issues/455
- [x] Update documentation for "Sales Order" - https://github.com/inventree/inventree-docs/issues/455
- [x] Add python integration for new return order functionality - https://github.com/inventree/inventree-python/issues/177

### CODE REVIEW

**Comment by matmair** [comment]
Very intresting PR!

**Comment by matmair** [comment]
Nice!

**Comment by SchrodingersGat** [comment]
@matmair already used it in anger. Seems to work well, I'm sure there'll be additional things to add.

I'll put up a blog post soon

**Comment by mabroens** [comment]
Hi All, the RMA feature sounds great. any idea when it will be released?

Br Martijn

**Comment by matmair** [comment]
We do not give out release dates as the project is developed in spare time.

**Pull request merged**
