### PR TITLE
P-UI: Admin UI

### LINKED ISSUE #4962: [FR] Expose user / group management to "Settings" page
Currently user and group management needs to be done by the low-level "admin" page. 

In general, it would be good to move any required activity away from that page - including user / group management.

Reference: https://github.com/inventree/InvenTree/issues/3978

### LINKED ISSUE #5016: [FR/P-UI] New admin UI
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

The current admin (global settings) UI is using HTML templates. This means you can not use all admin features headless and the UI needs to be fully rendered on the server side before being shown.

### Suggested solution

Switch to new UI #5011

### Describe alternatives you've considered

N/A

### Examples of other systems

_No response_

### Do you want to develop this?

- [X] I want to develop this.

### PR DESCRIPTION
**Pull request by matmair**
The idea is to split up the UI into separate user and server settings/admin pages. The new admin page should be a full admin page with all the information an admin needs: version info, system checks, quick links to often-used elements and user/group management. It should not be necessary to use the Django admin page.

```[tasklist]
### Existing features
- [x] User settings
- [x] Global settings
- [x] Plugins settings
- [x] Old user settings
- [x] Old global settings
``` 

```[tasklist]
### New features
- [ ] System checks https://github.com/inventree/InvenTree/issues/3740
- [x] User managment
- [ ] Config lookup (related to #4173)
- [ ] Backup managment
- [ ] Background tasks (UI for #5158)
``` 

Closes #5016
Closes #4962

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair looks good, and I like that you get a notification when something changes.

The "accordion" style makes for a lot of scrolling, and things can be hard to find. Can we add in a sidebar (like the current implementation) for nav? Happy to put this off for a future PR if you just want to get this one merged in

**Comment by matmair** [comment]
@SchrodingersGat this is only meant as a technical preview (how the REST API is handled). I imagine the admin view to be a landing page with a small stats section, followed by 3 or 4 action tiles for admin docs, user management, often-used actions etc and then multiple pages for all the above-listed sections. With the headers on the left and the content on the right similar to the current setup.

**Comment by SchrodingersGat** [comment]
Ok, I'm happy with that. Get the framework in place and the UX can follow.

**Comment by SchrodingersGat** [comment]
@matmair I completely forgot that you had started an implementation of this - it looks like it also got further along than https://github.com/inventree/InvenTree/pull/5679

Let me re-open and review this properly

**Comment by matmair** [comment]
implemented in follow up PRs that were merged recently

**Pull request closed without merging**
