### PR TITLE
[PUI] Details Panel components

### PR DESCRIPTION
**Pull request by LavissaWoW**
Creating components for rendering Details panels.
Design aimed to be generic allowing wrappers for each type of details panel.

### CODE REVIEW

**Comment by LavissaWoW** [comment]
@SchrodingersGat Any preferences?
Alignment of non-square thumbs in the "Select part image" modal.
(Filename and usage count is always bottom-aligned)

Center:
image

Top:
image

**Comment by SchrodingersGat** [comment]
I prefer "center" aligned

**Comment by LavissaWoW** [comment]
Lovely, I agree

**Comment by LavissaWoW** [comment]
@SchrodingersGat The backend workings of the old thumbnail select table doesn't work with PUI. 
For CUI, the swap is performed in `part/views.py`:`PartImageSelect.post`

In PUI, I have to use the API endpoints, and they serialize off of `part/serializers.py`:`PartThumbSerializerUpdate`. These do some Django Field validation checks preventing the ability to directly replace the URL of `part.image` with a new one. This seems linked to the serializer field being defined as a `FileField`. 

I was considering overriding the `to_internal_value` of `PartThumbSerializerUpdate` so that the Image is loaded on validation, but that might just save a new instance of the image. 

You made a small change last week allowing for CUI calls to find an identical file and use that. But with the serializers for the `part_thumb_*` endpoints, I can't directly replace the `Part.image` string, as it looks to me. Any ideas?

**Comment by SchrodingersGat** [comment]
I would suggest not using the `PartThumbSerializerUpdate`. The `PartDetail` serializer now has an `existing_image` field. Once you select the image, you should just be able to patch the part detail API endpoint.

As for selecting the images, we should duplicate the thumbnail list endpoint over to `/api/` in preparation for removing the old one in due course

**Comment by LavissaWoW** [comment]
Aah, I didn't notice the change to the Part serializer. They should work perfectly.

The Thumbnail list is already present in the API. It's under part_thumb_list (GET /api/part/thumbs). However, some of the API endpoint filters don't work as they should. I'll sort that in this PR too. It's that endpoint I used to generate the images I added above. The CUI version looks to me like doesn't affect PUI. So that can just exist as a CUI exclusive until CUI is phased out.

**Comment by SchrodingersGat** [comment]
Hey @LavissaWoW where are you at with this one? I'm back from holiday now, happy to review this whenever you are ready

**Comment by LavissaWoW** [comment]
@SchrodingersGat I took a bit of a holiday hiatus myself.
With the existing_ image PATCH PR sorted, I'm about 70% done with the structure of the Details Panel.

Should be done in not too long now.

**Comment by LavissaWoW** [comment]
@SchrodingersGat Here's the current progress. Reproducing the functionality of the image from CUI took some thinking.

chrome_stxoof9WkG

**Comment by SchrodingersGat** [comment]
@LavissaWoW starting to look pretty good :)

**Comment by LavissaWoW** [comment]
@SchrodingersGat I want to test the robustness of the final component framework. I'm working on refining type guards atm.
I'll mark this as ready when I'm finished with the polish, without implementing any other Details pages.
Could you and possibly others attempt to implement other Details pages to see if you run into issues?

**Comment by matmair** [comment]
@LavissaWoW you have changes in the API in the PR - please bump the version

**Comment by LavissaWoW** [comment]
@matmair will do!

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@LavissaWoW LGTM - any further requests from @matmair @wolflu05 ?

**Comment by matmair** [comment]
LGTM

**Review by matmair — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@LavissaWoW thanks for tackling this one! It will be a great template for other "details" pages.

**Pull request merged**
