### PR TITLE
Worker thread fix

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Closes https://github.com/inventree/inventree-brother-plugin/issues/35
- Fixes critical bug which prevented worker thread from loading plugins

### CODE REVIEW

**Comment by wolflu05** [comment]
Why do we skip the initialization of the registry if we are NOT in a worker thread?

**Comment by SchrodingersGat** [comment]
@wolflu05 - https://github.com/inventree/InvenTree/pull/5005

**Comment by wolflu05** [comment]
Sorry I don't get it. Maybe I understand something wrong, but doesn't this change mean that if we run invoke server, the plugin registry will not be initialized?

**Comment by SchrodingersGat** [comment]
@wolflu05 I can confirm that the plugins *do* get loaded / installed correctly  from the following entry points:

- `invoke server`
- `invoke gunicorn`
- `invoke worker`

**Pull request merged**
