### PR TITLE
Make tests faster

### PR DESCRIPTION
**Pull request by matmair**
This WIP targets to make tests faster by applying small patches that are common recommodations.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2997"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair how is this one looking? Speed improvements for the CI testing are sorely needed!

**Comment by matmair** [comment]
@SchrodingersGat running the tests in parallel created some errors that I did not really understand. Might take some time to figure them out.

**Comment by matmair** [comment]
This was more thought of as a test - I will open a new PR if I find a way to solve concurrency problems

**Comment by SchrodingersGat** [comment]
What about the other changes? Did the simpler password hasher make a significant difference?

**Comment by matmair** [comment]
@SchrodingersGat not significantly. Around 30secs for the whole thing

**Comment by SchrodingersGat** [comment]
Interesting. Might need to look at profiling the tests and trim some of the fat

**Pull request closed without merging**
