### PR TITLE
Separate unit cost and purchase price in BOM

### PR DESCRIPTION
**Pull request by mattbnz**
(not opening a bug for this, as the current behaviour may be intentional, but even if it is, I think this change is reasonable and does not break anything). 

It's possible for a part to have purchase price information, but not supplier
pricing (aka unit prices), but the current BOM price display logic will only
show the purchase prices when supplier prices are also available.

It seems reasonable to separate these two pieces of information - even when no
supplier pricing is available, seeing the purchase prices for BOM components is
useful on its own.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3141"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@mattbnz this does seem reasonable. FYI the entire "pricing" structure is going to have a major overhaul for the next major release:

- https://github.com/inventree/InvenTree/issues/1656
- https://github.com/inventree/InvenTree/issues/2507
- https://github.com/inventree/InvenTree/pull/2196

The current way we iterate over pricing is *extremely* expensive, and needs addressing! If you are interested in helping out with that, given your interest in the pricing structure, then let us know :) Help is always appreciated

**Comment by mattbnz** [comment]
Thanks, I'd seen #1656, but the other two references are new to me, I'll have a look.

I don't know how much time I can commit, but if there's clear requests/tasks that you can lay out, I'm happy to try.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @mattbnz

**Comment by matmair** [comment]
Pricing needs a lot of love.
I tried to fix it but had to switch to an external timeseries database to get a reliable and fast backend for the daily operations I needed. If the codebase had been on today's level of coverage, documentation and cleanliness I might have tried to do it here but now I am in production with another system that I cannot just switch. Would love to get my code in here but that would make setup at least twice as difficult as it is now.

**Pull request merged**
