### PR TITLE
total price column as per #1660

### PR DESCRIPTION
**Pull request by matmair**

### CODE REVIEW

**Comment by matmair** [comment]
Closes #1660

**Comment by matmair** [comment]
grafik
For illustration

**Comment by SchrodingersGat** [comment]
@matmair fantastic, this looks great!

**Comment by SchrodingersGat** [comment]
Can we do the same thing for sales orders?

**Comment by matmair** [comment]
@SchrodingersGat sure, give me 10 minutes.

Not #1659 is for the option to safe a total for a SO in the databse - for example if you add 12% onto a total for shipping or the customer got a discount. This PR and the next one just sum up the totals

**Pull request merged**
