### PR TITLE
Use whitenoise for static file handling

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Fixes https://github.com/inventree/InvenTree/issues/5948
- Uses [whitenoise](https://whitenoise.readthedocs.io/en/latest/django.html) as a replacement for django's built-in static file server
- Still really only useful for "development" - as whitenoise is not a recommended solution for serving media files

### Example

- Running local dev server at `http://localhost:8000`
- vite server running at `http://localhost:5173`
- allows CORS requests for static files

image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@LavissaWoW @wolflu05 @matmair after much reading, this seems like the only reliably way around this issue. Even though it is a very small target for the issue (static file CORS in dev mode, from the vite server), this seems like a reasonable solution.

I looked into whether this would be a good solution for serving static / media files in general - however it does not handle media files. So, stuck with Caddy (or similar) solution for now

**Comment by LavissaWoW** [comment]
@SchrodingersGat Probably unrelated, but should we fix the `favicon` 404 too?

**Comment by SchrodingersGat** [comment]
@LavissaWoW I've forgotten the favicon issue, can you remind me?

**Comment by LavissaWoW** [comment]
@SchrodingersGat I'm not able to reliably reproduce the console error message.
But any tab showing PUI lacks the favicon on its tab icon. And I regularly get a 404 error in the console for `/favicon.ico`

**Comment by SchrodingersGat** [comment]
Ok if you see it again please raise an issue :)

**Pull request merged**
