### PR TITLE
[FR] Sign artifacts with sigstore

### LINKED ISSUE #3077: [FR] Sign artifacts with sigstore
**Problem**
We are not signing our artefacts (docker images, pypi packages) right now.

**Suggested solution**
The big players are working together on a framework for this called sigstore.
This article describes how to do it on docker: https://dev.to/n3wt0n/sign-your-container-images-with-cosign-github-actions-and-github-container-registry-3mni
I am looking into pypi right now.

**Describe alternatives you've considered**
The current way works - it would be cool to be on the leading side of security in the industry though.

**Do you want to develop this?**
Yes if now one else wants to

### PR DESCRIPTION
**Pull request by matmair**
Fixes #3077

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3347"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat this should add the required steps for signing. Could you maybe test it before merging with docker hub? Not sure how that could be done.

**Comment by SchrodingersGat** [comment]
@matmair what are the details of the credentials used here? Is this against an account of yours?

**Comment by matmair** [comment]
@SchrodingersGat it uses the github token / OIDC to get credentials on the fly. It signs using the repo itself.

**Comment by SchrodingersGat** [comment]
Oh sweet! I can't see how we test this without pushing, so I'll merge and cross my fingers

**Comment by SchrodingersGat** [comment]
Should have crossed more than my fingers. Fix incoming at https://github.com/inventree/InvenTree/pull/3363

**Pull request merged**
