### PR TITLE
Update django-allauth lib version

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Closes https://github.com/inventree/InvenTree/issues/4139

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/4141"></a>

### CODE REVIEW

**Review by matmair — APPROVED** [review]
Nice, generalised OIDC.
Should we maybe create a shortcut to add OIDC SSO via web interface/config? Is probably the most universal SSO method out there.

**Comment by gueldenstone** [comment]
@matmair I'd love that! The current process is a little complicated imho.

**Comment by gueldenstone** [comment]
Would it be possible to include this change into a point release?

**Comment by SchrodingersGat** [comment]
@gueldenstone just released 0.9.2

**Comment by matmair** [comment]
> @matmair I'd love that! The current process is a little complicated imho.

the feature is mainly meant for business/enterprise users, they can mostly handle 4 steps. You can also set up everything in the config, that is just very inflexible.

**Pull request merged**
