### PR TITLE
[PUI] Quick commands pallet

### PR DESCRIPTION
**Pull request by matmair**
This adds a quick command palette with (at least now) simple actions to navigate to a few parts of the UI without the mouse.

https://github.com/inventree/InvenTree/assets/66015116/fad52d2b-86b3-4c4a-bfd1-726f2f4368b1

Clsoes #5888

### CODE REVIEW

**Comment by matmair** [comment]
This is now feature complete and ready for review; I still have to figure out why the keyboard-based tests keep failing but that is probably something with the testing framework

**Comment by matmair** [comment]
OK the tests are solved (stupid issue on my side, is documented by playwright very clearly) - I will try to get coverage of new lines to 100% and than it should be ready

**Comment by matmair** [comment]
Coverage of new code is at 90%+, this is ready for review @SchrodingersGat

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair really happy with this, it looks great. In the future I would love to see some custom actions for various context (i.e. "create a new build order").

Additionally, should we update "search" panel to the same visual style (spotlight vs drawer)? Or keep them visually separate.

In any case, happy to merge, nice work :)

**Comment by matmair** [comment]
I think search works fine as is, I would leave it till we have the minimal function set of CUI reached in PUI. Flashing out this while there is nearly no usage seems like a waste.

There could be integrated search in the command line, context actions, maybe plugins. At some point I would like this to become similar to command + shift + P in vs code or Command + K in Linear but we will probably have to shift libraries for that.

**Pull request merged**
