### PR TITLE
Package use uv

### PR DESCRIPTION
**Pull request by matmair**
This PR switches to uv for installs - 1 for speed and 2 for cleaner logs to make debugging easier.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please address the conflicts here :)

**Comment by matmair** [comment]
@SchrodingersGat ready for review and merge

**Comment by SchrodingersGat** [comment]
@matmair LGTM - we have had some teething issues with uv before, have you tested this thoroughly?

**Comment by matmair** [comment]
I have been running with/on uv since the first changeset. Not exactly this code but very close and I have tested a new deployment on Ubuntu 20.04 and Debian 12 with this exact code.

**Pull request merged**
