### PR TITLE
Move get_scheduled_tasks call into register_tasks function

### PR DESCRIPTION
**Pull request by 30350n**
The documentation of the `get_scheduled_tasks`:
https://github.com/inventree/InvenTree/blob/5dbd3030d1e983a63812dfe32f6951d977496fbc/InvenTree/plugin/base/integration/ScheduleMixin.py#L105-L109 function in the `ScheduleMixin` states that you can override it, if you want the scheduled tasks to be "dynamic" i.e. influenced by plugin settings.

Doing this breaks settings initialization pretty badly though, because the `get_scheduled_tasks` function gets called in `__init__.py`. That means any `get_setting` calls in it, will be resolved **before** any Mixins (most importantly the `SettingsMixin`) are actually loaded. The setting will still be created, but it won't be initialized correctly, thus it's `default` value won't be set which can then result in errors in the `ScheduleMixin` code which essentially completely lock up the server.

Moving the relevant code to the `register_tasks` function resolves this.

### CODE REVIEW

**Comment by 30350n** [comment]
Also sorry for the rambling, but I feel like the [`BaseInvenTreeSetting`](https://github.com/inventree/InvenTree/blob/5dbd3030d1e983a63812dfe32f6951d977496fbc/InvenTree/common/models.py#L183) class could use some refactoring. The whole passing-around-`**kwargs`-everywhere thing makes it some of the most opaque spaghetti code I've ever seen, took me quite a few hours to trace the bug through that mess.

**Comment by matmair** [comment]
If you find an easier way to handle all the different setting types ( that can also be defined by plugins so changing the python API is not great) I am happy to review a PR. I think kwargs is one of the better ways to handle this as we have to support an arbitrary amount of filters in the base class.

**Comment by SchrodingersGat** [comment]
@30350n the code is admittedly very complex. As @matmair says, if you have a cleaner way of implementing this, please submit a PR :)

**Review by SchrodingersGat — APPROVED** [review]

**Comment by 30350n** [comment]
(Tests still need fixing, do not merge yet please.)

**Comment by 30350n** [comment]
> If you find an easier way to handle all the different setting types ( that can also be defined by plugins so changing the python API is not great) I am happy to review a PR. I think kwargs is one of the better ways to handle this as we have to support an arbitrary amount of filters in the base class.

Yeah I'll try to look into that.

Will adjust the tests.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @30350n

**Pull request merged**
