### PR TITLE
Adds "stock value" calculation to stock table

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Uses purchase_price data where available
- Otherwise reverts to part pricing estimates
- Aggregate total in footer

### CODE REVIEW

**Comment by anonkwe** [comment]
how do i enable this column? sorry to bother that much

**Comment by SchrodingersGat** [comment]
You will need to update to the latest master (development) version, and then you can select the column via the columns selector:

image

**Comment by anonkwe** [comment]
am i in the good version? doesn't show up on mine 
image
image


# Version Information:
InvenTree-Version: 0.11.0 dev
Django Version: 3.2.18
Commit Hash: 93a2d612e
Commit Date: 2023-03-09
Database: sqlite3
Debug-Mode: False
Deployed using Docker: False
Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'Zebra', 'slug': 'zebra', 'version': '0.2'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.6.0'}]

**Comment by SchrodingersGat** [comment]
Try hard-refreshing the page a few times (so the javascript files aren't running from browser cache)

**Comment by anonkwe** [comment]
could you show me a screenshot, even a private windows does not do the trick

**Comment by anonkwe** [comment]
it just worked! thank you so much. but somehow it mixed up cureencies values, i wonder why.. total value doesn't render with 2 decimals also.
image

Is there a way i Can add some line of code somewhere to do the stock total on the footer as well?
image


here are the mixed currency values as well, the rates are reversed
image

**Comment by anonkwe** [comment]
@SchrodingersGat is there a way to change the total stock value currency on the footer? It stays at USD as of now. Thanks

**Comment by matmair** [comment]
Currencies should use the default currency when multiple are present, try changing the default in the global settings.

**Comment by anonkwe** [comment]
Default currency is at CAD, not sure how it interacts. Maybe total is is trying to use line's default currency else USD then using USD so since the line is empty, it is then using USD somehow?

**Comment by anonkwe** [comment]
@SchrodingersGat

> it just worked! thank you so much. but somehow it mixed up cureencies values, i wonder why.. total value doesn't render with 2 decimals also. image
> 
> Is there a way i Can add some line of code somewhere to do the stock total on the footer as well? image

@SchrodingersGat 
sorry to bother, any toughts?

**Comment by SchrodingersGat** [comment]
Use `footerFormatter` function, e.g.

https://github.com/inventree/InvenTree/blob/324a47ba17fce1792ddf69c71c8d3f6bc25514f2/InvenTree/templates/js/translated/stock.js#L2095

**Comment by SchrodingersGat** [comment]
It renders into your selected default currency. You can see exactly where the currency for rendering is selected here:

https://github.com/inventree/InvenTree/blob/324a47ba17fce1792ddf69c71c8d3f6bc25514f2/InvenTree/templates/js/translated/stock.js#L2138

**Comment by anonkwe** [comment]
[image: image.png]

I don't get what i'm supposed to see.. is there any place in the code where
i can force my base currency ? footer remains usd no matter what
[image: image.png]
[image: image.png]
what am i missing?

**Comment by anonkwe** [comment]
never mind, the error is in the config_yaml template 
image
 for some reason , i have to go specify INVENTREE_BASE_CURRENCY value to the good one in the admin panel

**Comment by anonkwe** [comment]
> never mind, the error is in the config_yaml template image for some reason , i have to go specify INVENTREE_BASE_CURRENCY value to the good one in the admin panel

anything about this that breaks and has to be entered everytime we pull a commit?

**Comment by anonkwe** [comment]
image


could it be possible to incorporate such value ?

**Pull request merged**
