### PR TITLE
sales order price and validation

### LINKED ISSUE #807: Add "empty" line to Purchase Order and Sales Order
Might want to add a line item against something not in the database. This could be simply because the item has not been entered, or because it requires a line for "consulting fee" or something non tangible.

### PR DESCRIPTION
**Pull request by matmair**
Adds items from #1727, #807 (like described in #1656 )

This PR adds:
- a `sale_price` for sale orders
grafik
- a `checksum` for the price
- a validation dialog for the price
grafik
- additional line items (including editiong dialog)
grafik
grafik

Closes #807

### CODE REVIEW

**Comment by matmair** [comment]
Should also fix #807, 1592

**Comment by matmair** [comment]
Closes #807

**Comment by matmair** [comment]
Missing: predefined additional line items

**Comment by matmair** [comment]
@eeintech mind looking at this? No hurry though, I can not find a bug preventing a merge anyway.

**Comment by eeintech** [comment]
@matmair Looks like you need to add your new model `SalesOrderAdditionalLineItem` to the `users/models.py -> RULESET_MODELS` list, I believe it will be `order_salesorderadditionallineitem` or something similar

**Comment by eeintech** [comment]
@matmair I took a look and reporting for duty!

1. I found that the sell price validation is persistent even when it is changed, to reproduce:
- Set the "Sell price" field with an initial value then validate the order
- Change the "Sell price" to different value, tag shows the sell price hasn't been validated (red)
- Reset the "Sell price" field to the initial value, tag shows the sell price has been validated (green) although there was a change in the sell price

Is that wanted? I would expect not.

2. Looks like the calculated price is not automatically updated after either a "Sales Order Item" or "Additional Order Line" is added, the page needs to be refreshed. Any chance the page can be reloaded automatically every time a new item is added?

3. Ran into issues with currencies, for instance when adding two additional line items with different currencies (CAD and EURO in this case) then refreshing the page I got this error:

image

I had to go in the Admin section to change the currency back to the default (CAD), I don't think the conversion is working on this table and the total price is based on the second currency instead of the default currency:

image

Same result with the "Sales Order Items" table too...

4. That one is a bug :bug: 

User can still add "Sales Order Items" and "Additional Order Lines" after the order was shipped:

image

5. That one too :bug: 

Sell price validation is reset after order is marked as "shipped" (the screenshot follows the one above, after page is reloaded):

image

6. That one is aesthetic only :smile: 

Why is my difference of $1 showing in green color? Feels like it should be red (as assuming user messed up!)

image

Looks like it's red when the "sale_price" is lower than calculated price though:
image

Also should "validate" be capitalized? (eg "Validate")

**Comment by matmair** [comment]
@eeintech huge thanks, gone hash those out.
Regarding 6: The color is intended to warn if the users tries to sell below the calculated price. That's intended. The rest not really.

**Comment by matmair** [comment]
1: this is expected, as the value is the same as was validated
2: Fixed, js-function now updates on each change
3: Fixed, currencies were not implemented in the total - function
4: Fixed in view - maybe should also be done in api - any ideas how @SchrodingersGat 
5.: Fixed
6: No fix required

**Comment by SchrodingersGat** [comment]
>  Fixed in view - maybe should also be done in api - any ideas how @SchrodingersGat

Can you expand on that? I'm not exactly sure what you're askign

**Comment by matmair** [comment]
> 
> 
> > Fixed in view - maybe should also be done in api - any ideas how @SchrodingersGat
> 
> Can you expand on that? I'm not exactly sure what you're askign

Where in the whole process should we stop user updating lines in a order that has been shipped?

**Comment by SchrodingersGat** [comment]
Unless you have another suggestion I think the current option of disabling the "edit line item" buttons when the order has been shipped should be sufficient?

**Comment by matmair** [comment]
@SchrodingersGat for applications using the API that could present a problem as they will need to check that and we need to trust that. I would feel more easy if it was not possible to change orders after they are marked shipped in any way.

**Comment by SchrodingersGat** [comment]
Sure, well there are a couple of ways we could do this.. I would suggest setting certain fields as "read_only" if the referenced SalesOrder has been shipped. Could be done in the serializer or DetailView endpoint classes?

**Comment by eeintech** [comment]
I don't know much of the meaning of "price validation" but I am still concerned that the "validation" has memory instead of being immediately deleted if sell price is set to another price, it feels like re-validation should always be done.

**Comment by matmair** [comment]
@eeintech the validation ensures that the sell price is the same as when it was entered and that a few parameters that might influence the price are the same.
That's why I think this pattern makes sense: if I enter 200€ and validate that I expect only 200€ with the same delivery date and the same items at the same quantities and prices to be valid. With each change - which do not happen automatically - I expect to be asked again to validate the price.

**Comment by matmair** [comment]
@eeintech @SchrodingersGat any idea how to solve [this error](https://github.com/inventree/InvenTree/pull/1730/checks?check_run_id=3108489350#step:5:289)? I have been fiddeling with this for a week.

**Comment by SchrodingersGat** [comment]
@matmair I'll have a look into this one next week

**Comment by eeintech** [comment]
@matmair Looks like the error is the extra `files` argument of the `patch` api test method:
https://github.com/inventree/InvenTree/blob/bcfb3ac067f28b0ec416fdb839829441f45dcd33/InvenTree/InvenTree/api_tester.py#L138

I don't see it in the `APIClient.path` method (rest_framework -> test.py):
``` python
def patch(self, path, data=None, format=None, content_type=None, follow=False, **extra):
```

Maybe we want something like this instead?

``` python
response = self.client.patch(url, data=data, format='json', **{'files': files}) 
```

**Comment by SchrodingersGat** [comment]
@matmair try this:

```
---
 InvenTree/InvenTree/serializers.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/InvenTree/InvenTree/serializers.py b/InvenTree/InvenTree/serializers.py
index 58d33697..8ec98cd7 100644
--- a/InvenTree/InvenTree/serializers.py
+++ b/InvenTree/InvenTree/serializers.py
@@ -46,7 +46,7 @@ class InvenTreeMoneySerializer(MoneyField):
             amount = None
 
         try:
-            if amount is not None:
+            if amount is not None and amount is not empty:
                 amount = Decimal(amount)
         except:
             raise ValidationError(_("Must be a valid number"))
-- 
2.30.2.windows.1

```

**Comment by SchrodingersGat** [comment]
@matmair I've fallen behind on this one - is it ready for review?

**Comment by matmair** [comment]
> 
> 
> @matmair I've fallen behind on this one - is it ready for review?

@SchrodingersGat let me merge in the last changes and check again but should be.

Maybe there should be a more general discussion between you, @eeintech and me if this feature is ready for master like this or if the both of you would like to see additional stuff. I want to reduce the number of half-ready features I submit into master 👼. Just irritates users.

**Comment by matmair** [comment]
@SchrodingersGat should be good to go technically

**Comment by eeintech** [comment]
@matmair Just took another look.

1. Sell price has 4-digit while calculate price has only 2-digit. Also space out the validation label from the closing bracket (better yet would be at the right-hand side of the cell like the "admin" label above):

image

2. Total in sale order line items adds up prices with different currency **ignoring** conversion rate (here 14.5 CAD + 120.1 USD shouldn't give a result of $134.6 USD but rather closer to $131.7 USD, or better yet should be in the default currency which is CAD):

image

3. PO column shows "undefined" for stock unrelated to POs (instead of blank). Underlying stock item information shows "undefined" instead of the name of the location (URL points to location):

image

Other than that it looks good!

**Comment by matmair** [comment]
@eeintech thanks for the testing, will fix!

**Comment by SchrodingersGat** [comment]
@matmair I'm getting some new form errors when trying to add a line item to a sales order:

image

**Comment by eeintech** [comment]
@matmair Seems like this PR is stalling a bit. Was it a highly demanded /desired feature or should it be pushed to `0.6.x` releases?

**Comment by matmair** [comment]
> 
> 
> @matmair Seems like this PR is stalling a bit. Was it a highly demanded /desired feature or should it be pushed to `0.6.x` releases?

@eeintech there will be some unittesting required and maybe it should be redone so I vote to target 0.6.x and to make that about pricing.

**Comment by tse-tarn-france** [comment]
@SchrodingersGat @matmair, don't know if this takes place here but for parts that are "Purchaseable" AND "Salable" price may appear automatically when creating a sale order line. For build parts of course price is almost never the same, however a "reference sale price" could also appear and be modified.

This is a nice to have, absolutly not a priority.

Regards.

**Comment by eeintech** [comment]
Didn't want it anymore @matmair ?

**Comment by matmair** [comment]
@eeintech I will rewrite the whole pricing system and this PR just got ugly with how long 0.6.0 took. I will take some inspiration but do it a bit cleaner. Hashing should be a generator for example - so plugins can use the same function as prices and BOMs to validate. Is going to take a while but the current system is just not performant enough.

**Pull request closed without merging**
