### PR TITLE
Export Orders as iCal calendars

### PR DESCRIPTION
**Pull request by miggland**
This is related to issue #3031.

I'm adding this draft PR so that you can follow along in my code, I'll also need some input.

I've implemented an export for purchase orders only so far, available at: `/order/purchase-order/calendar.ics`.

I've attached an example output (as .txt, because of Github).
[calendar.txt](https://github.com/inventree/InvenTree/files/9169190/calendar.txt)

Problems/todo:
- [ ] This seems not to support authentication in a calendar viewer, such as Thunderbird, at the moment. 
- [x] The URL, which is automatically added, is correct except for the `http://https://`at the beginning. Any ideas? 
- [ ] Extend the exports to Sales Orders
- [ ] Extend the exports to Build Orders
- [ ] Apply InvenTree permissions, to make sure orders are not displayed to users without permissions to view.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3391"></a>

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
> The URL, which is automatically added, is correct except for the http://https://at the beginning. Any ideas?

Not sure, may it be to do with how `django_ical` is rendering here?

>  This seems not to support authentication in a calendar viewer, such as Thunderbird, at the moment.

The mail client will need to authenticate against the server somehow. Does `django_ical` support that?

**Comment by miggland** [comment]
> Not sure, may it be to do with how `django_ical` is rendering here?

I'm guessing it's from django_ical - I haven't actually added a URL, which is an option. It could also be caused by the syndication feed framework. Looks like it defaults to the [django SITE_ID](https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-SITE_ID).

> The mail client will need to authenticate against the server somehow. Does `django_ical` support that?

Normally ICS files are just web resources, meaning they are protected by basic HTTP auth. The way it is now, the user get's forwarded to a login page instead - which is fine in a browser, but not for an automatic download.

At the moment, I can't even get around this, as every page (?) needs authentication.. my knowledge of the Django & InvenTree authentication methods is very limited.

Looks like an [approach similar to this](https://www.djangosnippets.org/snippets/2468/) could work, according to [this thread](https://stackoverflow.com/questions/152248/can-i-use-http-basic-authentication-with-django).

Further permissions are another question - the orders shouldn't be displayed to users who do not have access. I've added this to the list above..

**Comment by matmair** [comment]
@miggland auth seems to work with outlook

**Comment by matmair** [comment]
@miggland I submitted a few small fixes - please check if it works this way

**Comment by miggland** [comment]
The URL issue is fixed, marked as such above.

**Comment by matmair** [comment]
@miggland feeds are generally not authenticated. You can use the function you mentioned to filter for the authenticated user.
I am not really sure that you can add auth to a feed.

**Comment by SchrodingersGat** [comment]
Is this what we want from a data security POV then? Am I understanding correctly that the `.ics` endpoint does not require login?

**Comment by matmair** [comment]
@SchrodingersGat in this state no but once filtering is introduced you just get an empty response. I am also looking into wrapping the view rn.

**Comment by miggland** [comment]
> @miggland feeds are generally not authenticated. You can use the function you mentioned to filter for the authenticated user. I am not really sure that you can add auth to a feed.

That makes sense - but how do I make the authenticated user actually be recognised? At the moment, it's unauthenticated even if I send authentication headers.

**Comment by matmair** [comment]
@miggland I am having a hard time finding good answers. I might need some time to understand the whole feed framework better before I can help with this one.
@SchrodingersGat Suggestion: Move this to 0.9.0

**Comment by miggland** [comment]
> @SchrodingersGat Suggestion: Move this to 0.9.0

It's OK to leave it at 1.0.0 as in the FR, even ;)

It's not extremely important, we should get it right. Doesn't need to be in the next release for sure.

**Comment by SchrodingersGat** [comment]
Still important, thanks bot

**Comment by miggland** [comment]
I've been trying around a bit more. It seems that this problem is not necessarily limited to the feed framework.

I modified InfoView to return the username and whether or not the user is authenticated:
`'user': f'Username: {str(request.user)}, logged in ({request.user.is_authenticated})',`

When I open this page (`http://ubuntuvm:8000/api/`) in the browser, where I am logged in to InvenTree, I get this:
```
{
  "server": "InvenTree",
  "version": "0.9.0 dev",
  "instance": "My very first InvenTree Instance",
  "apiVersion": 76,
  "worker_running": true,
  "plugins_enabled": true,
  "active_plugins": [],
  "user": "Username: TheUser, logged in (True)"
}
```

However, when I download the page from the command line, using either Basic or Token auth like this:
`curl -H 'Authorization: Token 87b----d885' http://ubuntuvm:8000/api/`
`curl -H 'Authorization: Basic bW.........pbg==' http://ubuntuvm:8000/api/`
this is returned:
```
{
   "server" : "InvenTree",
   "version" : "0.9.0 dev",
   "instance" : "My very first InvenTree Instance",
   "apiVersion" : 76,
   "worker_running" : true,
   "plugins_enabled" : true,
   "active_plugins" : [],   
   "user" : "Username: AnonymousUser, logged in (False)"
}
```

To change the behaviour for this API, it has to be based on a different class, RetrieveAPI - then I get the InfoView to show me if I am logged in or not, for basic and token authentication:
```
user@computer:~$ curl -H 'Authorization: Basic bW________bg==' http://ubuntuvm:8000/api/
{"server": "InvenTree", "version": "0.9.0 dev", "instance": "My very first InvenTree Instance", "apiVersion": 76, "worker_running": true, "plugins_enabled": true, "active_plugins": [], "user": "Username: TheUser, logged in (True)"}

user@computer:~$ curl -H 'Authorization: Token 87b______________85' http://ubuntuvm:8000/api/
{"server": "InvenTree", "version": "0.9.0 dev", "instance": "My very first InvenTree Instance", "apiVersion": 76, "worker_running": true, "plugins_enabled": true, "active_plugins": [], "user": "Username: TheUser, logged in (True)"}

user@computer:~$ curl http://ubuntuvm:8000/api/
{"server": "InvenTree", "version": "0.9.0 dev", "instance": "My very first InvenTree Instance", "apiVersion": 76, "worker_running": true, "plugins_enabled": true, "active_plugins": [], "user": "Username: AnonymousUser, logged in (False)"}
```





All the changes for the example can be seen here:
```
diff --git a/InvenTree/InvenTree/api.py b/InvenTree/InvenTree/api.py
index 8aa15be33..9e611aec4 100644
--- a/InvenTree/InvenTree/api.py
+++ b/InvenTree/InvenTree/api.py
@@ -10,7 +10,7 @@ from rest_framework import filters, permissions
 from rest_framework.response import Response
 from rest_framework.serializers import ValidationError
 
-from InvenTree.mixins import ListCreateAPI
+from InvenTree.mixins import ListCreateAPI, RetrieveAPI
 from InvenTree.permissions import RolePermission
 from part.templatetags.inventree_extras import plugins_info
 
@@ -20,7 +20,7 @@ from .version import (inventreeApiVersion, inventreeInstanceName,
 from .views import AjaxView
 
 
-class InfoView(AjaxView):
+class InfoView(RetrieveAPI):
     """Simple JSON endpoint for InvenTree information.
 
     Use to confirm that the server is running, etc.
@@ -38,6 +38,7 @@ class InfoView(AjaxView):
             'worker_running': is_worker_running(),
             'plugins_enabled': settings.PLUGINS_ENABLED,
             'active_plugins': plugins_info(),
+            'user': f'Username: {str(request.user)}, logged in ({request.user.is_authenticated})',
         }
 
         return JsonResponse(data)
```

I don't quite understand the difference between AjaxView and RetrieveAPI, but it seems that AjaxView relies on "SessionAuthentication" and does not include "BasicAuthentication" and "TokenAuthentication".

I have not found a way to get the ical feed class to use these two yet.

**Comment by miggland** [comment]
BTW, ignore the new commits. I made a mess when trying to update to the new version.

And also, you don't have to think too much about what I wrote before.

Going back from the API to general views, I have now found the solution to the problem!

**Comment by matmair** [comment]
@miggland so what was the solution? I am very intrigued, I tried to get this working myself for half an hour and gave up.

**Comment by miggland** [comment]
Well, not a perfect solution (yet), but working partially. I was wrong though, it's in the API view. In the other view, it works with Token auth, and not Basic.

This version works with Basic auth in curl:
`curl -H 'Authorization: Basic bW___________bg==' "http://ubuntuvm:8000/api/order/calendar/purchase-order/"`

The solution is to overload the call method, and perform authentication there - login in again, if necessary.

This should probably be able to support Token login as well, if the header is handled differently.

```
def __call__(self,request,*args,**kwargs):
        """Overload call in order to check for authentication.
        This is required to force Django to look for the authentication,
        otherwise login request with Basic auth via curl or similar are ignored,
        and login via a calendar client will not work.
        
        See:
        https://stackoverflow.com/questions/3817694/django-rss-feed-authentication
        https://stackoverflow.com/questions/152248/can-i-use-http-basic-authentication-with-django
        https://www.djangosnippets.org/snippets/243/
        """
        from django.http.response import JsonResponse
        from django.contrib.auth import authenticate, login
        import base64
        # ~ print(f"{request.META = }")
        
        if request.user.is_authenticated:
            return super().__call__(request,*args,**kwargs)
        
        # No login yet - check in headers
        if 'HTTP_AUTHORIZATION' in request.META:
            auth = request.META['HTTP_AUTHORIZATION'].split()
            if len(auth) == 2:
                # NOTE: We are only support basic authentication for now.
                #
                if auth[0].lower() == "basic":
                    uname, passwd = base64.b64decode(auth[1]).decode("ascii").split(':')
                    user = authenticate(username=uname, password=passwd)
                    if user is not None:
                        if user.is_active:
                            login(request, user)
                            request.user = user
        
        # Check again
        if request.user.is_authenticated:
            return super().__call__(request,*args,**kwargs)
        
        # Still  nothing
        return JsonResponse({"message": "Login required"})
```

This is for testing, the imports shouldn't be there later of course..

**Comment by matmair** [comment]
@miggland no, just create a new PR and link this one there.

**Pull request closed without merging**
