### PR TITLE
Add flag to API which allows using pack size

### PR DESCRIPTION
**Pull request by miggland**
Intended for use when adding stock items manually, see #4310 

This adds a flag `use_pack_size` to the stock create API, which when set to True, multiplies the given quantity by the pack size of the supplier part before adding stock.

Additionally, a check that the defined SupplierPart exists is added.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@miggland I like this approach! The PR will need to address the following:

**Forms** - Ensure that the user is provided a 'use_pack_size' checkbox in forms *if a supplier part is specified*
**Unit Tests** - Will need some unit tests for the various edge cases / etc
**Documentation** - Some docs around this feature will be needed as it is quite subtle and might lead to some confusion

**Comment by miggland** [comment]
@SchrodingersGat: Tests added, and a field is in the form. It's static though, and I need to check that it actually works properly still.

More coming :)

**Review by matmair — APPROVED** [review]

**Comment by miggland** [comment]
@SchrodingersGat @matmair : Docs added, tests as well.

Regarding this: "checkbox in forms if a supplier part is specified"
I have added a checkbox after supplier. It is always there, but doesn't have any effect unless there is a pack size != 1 defined. Do you really want it to be dynamic? (I'm not sure how this would be best done - however, it requires more calls to the API, which IMO is unnecessary)

**Comment by matmair** [comment]
@miggland would this PR be ready for review or is there something else missing?

**Comment by SchrodingersGat** [comment]
@miggland sorry for the delayed review on this one.

Looks like the "purchase unit price" does not take pack size into account 

For example if you buy a reel of wire, with a pack size of 500m and a purchase price of $1000 the final unit purchase price for the wire should be $2/m and not $1000/m

Might need a slight tweak to divide purchase price through by pack quantity

**Comment by matmair** [comment]
And maybe a unit test for this case

**Comment by miggland** [comment]
You're right, the issue is fixed. No test (yet)

**Comment by SchrodingersGat** [comment]
@miggland thanks, I'll merge once a simple unit test is added :)

**Comment by miggland** [comment]
I've added tests now.

**Comment by SchrodingersGat** [comment]
@miggland thanks :) Only remaining thing is to increment the API version

**Comment by miggland** [comment]
> @miggland thanks :) Only remaining thing is to increment the API version

Of course, forgot about that :) Done

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @miggland

**Pull request merged**
