### PR TITLE
Add metadata model to Company

### PR DESCRIPTION
**Pull request by miggland**
Applying same methods as used in Orders, add Metadata to Company.

This gives a better base for plugin creation.

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3895"></a>

### CODE REVIEW

**Review by matmair — APPROVED** [review]

**Comment by matmair** [comment]
@miggland looks good! Is this ready for review/merge? You can run the style checks locally in your dev environment, that way you do not have to commit to get the errors. Instructions [here](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md#setup-devtools).

**Comment by SchrodingersGat** [comment]
So simple! The power of mixins :)

**Comment by miggland** [comment]
> @miggland looks good! Is this ready for review/merge? You can run the style checks locally in your dev environment, that way you do not have to commit to get the errors. Instructions [here](https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md#setup-devtools).

I should probably do that. What I'm missing is an instruction on which other tools check the files - ie the requirements.in, the import headers etc. I figured it out once, but didn't write it down and forgot about it..

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@miggland as this exposes a new endpoint to the API, please increment the API version number with a brief description:

https://github.com/inventree/InvenTree/blob/master/InvenTree/InvenTree/api_version.py

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@miggland thanks for the contribution :)

**Pull request merged**
