### PR TITLE
Label sheet printer

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR implements a new "builtin" plugin which prints multiple labels onto a single sheet, and then renders to a PDF

- Automatically array the labels onto the page
- Multiple sheets printed as required

------------------

@martonmiklos please review and LMK what you think, I have based this heavily on your PR 👍 

------------------

- Replaces https://github.com/inventree/InvenTree/pull/4805
- Closes https://github.com/inventree/InvenTree/issues/4167
- Closes https://github.com/inventree/InvenTree/issues/4626

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@martonmiklos I have taken your great work over at #4805 and re-implemented as a plugin.

Note that none of the existing models / templates are touched.

@wolflu05 your "printing options" functionality is used here too :)

**Comment by SchrodingersGat** [comment]
Example output:

Screenshot 2023-11-09 at 12 50 34 am

**Review by wolflu05 — APPROVED** [review]
This looks great as a starting point. Already looking forward to have more options and a template database in the future.

**Comment by MixasikM** [comment]
Hello, are there options to adopt label generation to different sheet formats?
Like different padding between labels or from the beginning/top of the page.
As not always label sheets are the same + some printers are not able to print without any border

**Comment by SchrodingersGat** [comment]
The default sheet plugin is pretty generic. What sheets are you working with? I have started work on a plugin for standard sheet sizes (for various commercial brands) but has not progressed very far to date.

**Pull request merged**
