### PR TITLE
Provide setup keys for two-factor authentication alongside QR codes

### LINKED ISSUE #6132: [FR] Provide setup keys for two-factor authentication alongside QR codes
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

Two-factor auth is obviously very important, but not all devices have cameras. Most services that offer 2FA via QR codes also offer keys you can manually copy to set up your 2FA.

### Suggested solution

Add the setup code for manual usage alongside the QR code.

### Describe alternatives you've considered

This is pretty standard, not having it is unusual.

### Examples of other systems

_No response_

### Do you want to develop this?

- [ ] I want to develop this.

### PR DESCRIPTION
**Pull request by matmair**
This PR adds the TOTP setup code below the setup QR code as seen in the picture below.
grafik

Closes #6132

### CODE REVIEW

**Comment by matmair** [comment]
@HammyHavoc currently doing some work in this area of the code - could you check if this fullfils your original request in https://github.com/inventree/InvenTree/issues/6132?

**Review by SchrodingersGat — APPROVED** [review]

**Comment by matmair** [comment]
@SchrodingersGat anything missing here?

**Comment by SchrodingersGat** [comment]
No, was just giving hammy a chance to respond. Happy to merge.

**Comment by HammyHavoc** [comment]
You are beautiful human beings.

**Pull request merged**
