### PR TITLE
Fixes to make compatible with Python 3.12

### PR DESCRIPTION
**Pull request by matmair**
This PR:
- Changes the code base to work with python 3.12
- Adds a matrix to the coverage tests to make sure upper and lower bounds are covered

Closes https://github.com/inventree/InvenTree/issues/6424
Contains #5777

### CODE REVIEW

**Comment by matmair** [comment]
@wolflu05 could you check if this changeset impacts any of your plugins? For me everything seems to work.

**Comment by wolflu05** [comment]
@matmair definitely, I'll test it out tomorrow. Do I need to run it explicitly with python 3.12 or can I also do the tests with 3.11?

**Comment by matmair** [comment]
the tests would need to be done on 3.12 to ensure nothing breaks

**Review by SchrodingersGat — APPROVED** [review]

**Comment by matmair** [comment]
Great, so from my POV we could merge this than and consider moving the image to Python 3.12 for the 0.16.0 release. I would not change it for 0.15.0 as plugins might need changes.

@theacodes thank you again for the initial PR, I have worked that into this and retained your authorship

**Comment by SchrodingersGat** [comment]
Many thanks everyone. @matmair do you want to take charge of updating our base Python version for next release?

**Comment by matmair** [comment]
@SchrodingersGat yes, I will test it with the hardned image and submit a PR once I am confident nothing important breaks

**Pull request merged**
