### PR TITLE
Fix completeSalesOrderShipment typo in sales_order.js

### LINKED ISSUE #4906: Shipping items from sales order fails due to typo
https://github.com/inventree/InvenTree/blob/master/InvenTree/templates/js/translated/sales_order.js#L399

Should be completeSalesOrderShipment instead of completeSalseOrderShipment, now gives the error "cant find variable completeSalseOrderShipment"

I know creating a PR would be the way to go, but im on mobile atm.

### PR DESCRIPTION
**Pull request by martonmiklos**
Fixes #4906

### CODE REVIEW

**Review by matmair — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Nice catch @martonmiklos - we really need to get some CI testing on the front end code ASAP

**Comment by martonmiklos** [comment]
> Nice catch @martonmiklos -

Credits goes to @jelgersma

> we really need to get some CI testing on the front end code ASAP

What is the plan for that (what technology do you prefer)?

**Comment by SchrodingersGat** [comment]
> What is the plan for that (what technology do you prefer)?

I don't really have enough knowledge about the unit testing frameworks available to make a call on that! Have to read some more. Can you make any recommendations?

**Comment by wolflu05** [comment]
I would say some linting would be enough for the first, as there is anyway the plan to switch to react with typescript?

Linting, eg with eslint would cover the undefined function references.

**Comment by SchrodingersGat** [comment]
We already do run eslint - https://github.com/inventree/InvenTree/blob/master/.eslintrc.yml - so we should look into why it did not catch this incorrect function

**Pull request merged**
