### PR TITLE
Plugin clean config

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Remove PluginConfig objects which have not been matched with a valid for 30 days.

Prevents potential "accumulation" of old plugin configuration objects in the database if the plugin has been removed,
without clearing them out too aggressively.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair LMK what you think of this approach

**Comment by wolflu05** [comment]
Would that mean if a instance is running for 30 days without any restart, the plugin config gets deleted?

I would rather add a toggle to the uninstall dialog which says remove all data.

**Comment by matmair** [comment]
I am not sure I see how this is a real improvement of resources. This adds a lot more compute usage with the constant calculations and task runs for saving then a few KB of storage for database settings.
Not to forget that this is a change in the default behavior and therefore will probably have unforeseen consequences.

**Comment by SchrodingersGat** [comment]
Fair points - this has been replaced by https://github.com/inventree/InvenTree/pull/5653

**Pull request closed without merging**
