### PR TITLE
Bootstrap 5

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR upgrades bootstrap to v5.1.3

As the original bootstrap integration was kinda hacked-in, this implementation will be a lot more methodical and conformant to the bootstrap "standards".

(Read: Previously I had no idea what I was doing...)

**Note:** This will most likely be a long-running PR as there will be a *lot* of changes required...

Closes https://github.com/inventree/InvenTree/issues/2111

### TODO

- [x] Navbar
- [x] Search input
- [x] main drop-down menus
- [x] Refactor sidebars (remove dependency)
- [x] Refactor API forms (client side)
- [x] Refactor modal forms (server side)
- [x] Fix dropdown-toggles for menus
- [x] Fix button callbacks (e.g. "cancel" button in forms)
- [x] Fix hover actions for thumbnail images
- [x] Table CSS fixes
- [x] Fix panels
- [x] Refactor "card" display for part table
- [x] Refactor "label" classes (very different in v5)
- [x] Refactor "detail" panel for major screens to be more "bootstrappy"
- [x] Enforce "breadcrumb" view for each page (and standardize)
- [x] Search results page
- [x] Index page
- [x] Settings page
- [x] Refactor "button group" instances - perhaps a html template here?
- [ ] ~~Refactor "table filters" UI (see comment below)~~ (*will leave for a separate PR*)
- [x] Use CSS [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) to allow for easier theming
- [x] Replace all instances of "data-toggle" with "data-bs-toggle"
- [x] Remove all instances of "action-buttons" class
- [x] Remove all instances of "btn-default"
- [x] Remove all references to "two_column.html" template
- [x] Replace "media" and "media-left" with "card"
- [x] Replace "panel" with "card"
- [x] Replace "label" width "badge" - https://getbootstrap.com/docs/5.0/components/badge/
- [x] Fix action buttons in "part category" and "stock location" display (see comment below)
- [x] Remove all instances of "{% block menubar %}"
- [x] Remove all instances of "enableNavbar" (replace with enableSidebar)
- [x] Remove all instances of "attachNavCallbacks"
- [x] Remove all instances of "sideNav"
- [x] Replace "tree view" for parts and stock
- [x] Refactor all existing "admin" buttons

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair @eeintech I'm pretty happy with this now, can you guys please pull this down and see if anything obvious stands out? It is a pretty major overhaul of the front-end visuals, so feedback is appreciated!

**Comment by matmair** [comment]
> @matmair @eeintech I'm pretty happy with this now, can you guys please pull this down and see if anything obvious stands out? It is a pretty major overhaul of the front-end visuals, so feedback is appreciated!

Already have done that throughout the process, there seem to be some problems with wrapping on upright iPads - will submit a PR to fix that

**Comment by matmair** [comment]
Looks really nice by the way. Should we refactor the themes too?

**Comment by SchrodingersGat** [comment]
> there seem to be some problems with wrapping on upright iPads - will submit a PR to fix that

> Should we refactor the themes too?

Yes, to both these things. Let's address these with separate PRs.

**Comment by matmair** [comment]
@SchrodingersGat is it intentional that the treeview for parts and stock locations is not there anymore? I found that feature very handy.

**Comment by SchrodingersGat** [comment]
@matmair the "tree view" is now implemented in the subcategory and sublocation tables, like so:

image

You can toggle this view in the top-right of the table:

image

Does this meet your needs? The dedicated tree views could be added back in but I'd do it a different way now, the old method was very inefficient.

**Comment by matmair** [comment]
@SchrodingersGat we should document any major UI shifts in the release notes so nobody gets confused

**Comment by sintech** [comment]
> Does this meet your needs? The dedicated tree views could be added back in but I'd do it a different way now, the old method was very inefficient.
@SchrodingersGat, sorry to intrude, but I also find this treeview very helpful for quick navigation. As a suggestion, what do you think about adding a drop-down list with part subcategories near the current breadcrumbs. In this way it will consume only one line of vertical screen space and you still be only one click away from any subcategory.

**Comment by SchrodingersGat** [comment]
@sintech @matmair happy to add it back in, as it seems it was appreciated.

@sintech can you describe your idea further? Maybe an example diagram?

**Comment by matmair** [comment]
@matmair I am happy with the current solution. Just needed to be pointed to the filter.

**Comment by sintech** [comment]
@SchrodingersGat, I have created new FR with mockups #2250.

**Pull request merged**
