### PR TITLE
Stock previous / next serial 

### LINKED ISSUE #1081: Navigate to next/previous serial number button
When on the stock item page for a given serial number, a button to navigate to the next serial number stock item would be handy, especially if it stayed on the same subpage (e.g. tests).

### PR DESCRIPTION
**Pull request by matmair**
Closes #1081

This PR implements a previous / next button next to the serial number of a stock that navigates to the stock item with the shown serial with the current view.

### CODE REVIEW

**Comment by matmair** [comment]
grafik
@jnewlands is that what you had in mind?

**Comment by SchrodingersGat** [comment]
Looks pretty good, but I would like to have the current serial number more prominent somehow

**Comment by matmair** [comment]
@SchrodingersGat do you think making it bold would do the job? I was not sure if that would make it to prominent. Or make the prev/next smaller?

**Comment by SchrodingersGat** [comment]
Maybe both?

**Comment by matmair** [comment]
@SchrodingersGat did both now

**Comment by SchrodingersGat** [comment]
Thanks @matmair this looks pretty nice now. Happy with merging this in.

**Comment by eeintech** [comment]
@matmair Sorry to be late to the party but it looks like it does not work for 2-digit serial number:

image

Can it be supported?

**Comment by matmair** [comment]
@eeintech see #1802 👼

**Comment by eeintech** [comment]
Nice 👍

**Pull request merged**
