### PR TITLE
Stable package

### LINKED ISSUE #3929: [MR] cherry-pick packaging stuff
@SchrodingersGat I would like to cherry-pick the packaging stuff to `stable` to enable a test package-release before the release and notifications for `0.9.0` go out.
Is that ok?

### PR DESCRIPTION
**Pull request by matmair**
This PR moves the needed files for packaging into stable before the next release- enabling testing of delivery before the first stable release to packager.io
Closes #3929

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/3972"></a>

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat nice; all CI ran through. Stable is ready for a package release!

**Comment by SchrodingersGat** [comment]
image

**Comment by SchrodingersGat** [comment]
Looks like it worked!

**Comment by matmair** [comment]
@SchrodingersGat already installed it on a virtual server, seems to work fine.

**Pull request merged**
