### PR TITLE
Add API change detection

### LINKED ISSUE #6269: [FR] API schema tracking in QC
I would like to create a new org repo that holds all API schemas from now on and maybe a few versions back(starting from the point where it was possible to create OpenAPI schemas).
Additionally, I would like to add a CI check that generates the schema of the current PR and checks it against the latest one from the new repo to ensure API changes do not go unnoticed.
Thoughts? @inventree/triage

_Originally posted by @matmair in https://github.com/inventree/InvenTree/discussions/5861_

### PR DESCRIPTION
**Pull request by matmair**
This PR is a follow-up to https://github.com/inventree/InvenTree/pull/6319 and adds a CI step that checks if the API schema was changed. If the api_version file was not changed but the diff between the published version of the schema and the worktree version of the schema is not clean the Job fails.
If the api_version file was changed and the CI runs on master the new schema is pushed to the reference repo (it needs a PAT for that).

Closes #6269
Closes #5861

### CODE REVIEW

**Comment by matmair** [comment]
@SchrodingersGat this is ready for review once #6329 is done and  was functionally tested here https://github.com/matmair/InvenTree/actions/runs/7823154486/job/21343712429 see result here https://github.com/inventree/schema/commit/2227b4956e70ae0b6869e6b06c3c80b2882e3479

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
@matmair LGTM - let me know what you need setup in terms of tokens. Do you want me to merge now, or more testing required?

**Comment by matmair** [comment]
@SchrodingersGat I have the needed token already prepared (also in 1password), I will send you a link directly. This was already tested on my fork, can be merged after the repo secret is added.

**Comment by SchrodingersGat** [comment]
@matmair many thanks for this addition - it will be a great feature to be able to track API schema files in this manner.

**Pull request merged**
