### PR TITLE
Assign to customer

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Fixes https://github.com/inventree/InvenTree/issues/2369

<a href="https://gitpod.io/#https://github.com/inventree/InvenTree/pull/2436"></a>

### CODE REVIEW

**Comment by rikimasorati** [comment]
what exactly is the Assign to customer for? I thought it would assign so i can later create a sale and ship those but i found that they immedialty count as shipped when assigned. and without being able to attach them to a sale. I dont really understand what this would be good for. 
Is there and similar option I can assign multiple serialized stock items to a sale?

**Comment by SchrodingersGat** [comment]
The "assign to customer" option allows you to bypass the salesorder process, if required. Following the sales order process is the recommended way to get a stock item to a customer, though

**Comment by turist79** [comment]
Ahh, so this is what "assigning to the customer" does... Frankly speaking i have expected the same as the original poster - some kind of customer reservation on our own stock.

I tried to revert this action by performing stock transfer on such an item but it seems to be impossible despite the fact that Stock transfer form opens correctly and allows to provide new stock location etc - it returns "StockItem cannot be moved as it is not in stock". Is there a way to get the part somehow back to the stock from  this state?

The ultimate end result of "assigning" part to the customer via SO and via "assign to customer" look the same - part is listed on the customer`s page under "Assigned stock items" (which is already misleading because of the word "stock", "Shipped items" would make much more sense here). Additional problem is that it seems to be impossible to differentiate which parts have been manually assigned and which - peoperly shipped since there is no reference to the SO or shipment on this page.

**Comment by matmair** [comment]
I am locking this;
If you have an issue please raise a new issue or discussion, we will probably miss comments on a closed PR from 3 years ago more often then not.

**Pull request merged**
